### ISSUE TITLE
Models created in GIMS crash upon Import

### ISSUE THREAD

**Issue by lumoize** [Skylumz/Sollumz#103]
Steps to reproduce:

1. Open Blender with Sollumz
2. Get a mesh assembled in Gims EVO (demo file attached)
3. Get the ydr.xml of said mesh
4. Import file into Blender. Blender will crash upon trying to import

[Demo File.zip](https://github.com/Skylumz/Sollumz/files/7481211/Demo.File.zip)

**Comment by Skylumz** [comment]
![image](https://user-images.githubusercontent.com/35295214/140686228-7d5fc842-9009-4579-8139-7a8cd02ccef3.png)
 
Fixed, sorry for the wait
