### ISSUE TITLE
Import YBN - Wrong Rotation on Geometry.

### ISSUE THREAD

**Issue by Denis-3D** [Skylumz/Sollumz#109]
Tested on file - hei_dt_20_0.ybn

After importing some geometry is placed wrongly (rotation issue) 

One of the visible problems on the image below. (Vanilla file on the right from RPF explorer)
![image](https://user-images.githubusercontent.com/7430830/140703255-e3ddf5b4-ae52-4f8b-8ff5-ada7ec4263ee.png)

**Comment by CFox04** [comment]
I can't find that file, can you attach it as an XML?

**Comment by Denis-3D** [comment]
My bad, not sure why 1 got yeeted

hei_dt1_20_0 full name and file in zip (cant upload xml directly)
[hei_dt1_20_0.ybn.xml.zip](https://github.com/Skylumz/Sollumz/files/7497968/hei_dt1_20_0.ybn.xml.zip)

**Comment by CFox04** [comment]
Nvm I found it. It's hei_dt1_20_0.ybn, looks like you forgot the "1"

**Comment by CFox04** [comment]
Lol the timing
