### ISSUE TITLE
Installation broken on latest Blender version

### ISSUE THREAD

**Issue by EvESpirit** [Skylumz/Sollumz#115]
Attempting to enable this plugin after installation as per user manual results in failure:

![image](https://user-images.githubusercontent.com/40306186/141098712-4e8aa011-ee37-45c0-86ac-4f0ea972664f.png)

Please shout at me asap if I did something wrong, being a Python scripter, this error seems trivial.
Using Blender 2.93.1 w/ DragonFF and io_scene_owm.

**Comment by soryy708** [comment]
Looks like it's because the folder is called `Sollumz-main`. If I rename it to `Sollumz` it works for me.

**Comment by EvESpirit** [comment]
https://user-images.githubusercontent.com/40306186/141101557-9ac89159-2552-4b71-8150-eddfb229a677.mp4

What am I doing wrong then?

**Comment by EvESpirit** [comment]
@soryy708 What am I doing wrong then?
https://www.youtube.com/watch?v=3yoy_LQLAco

**Comment by Rigonkmalk** [comment]
In the zip file you will find the folder Sollumz-main inside, rename it and try again.

**Comment by EvESpirit** [comment]
Thanks and sorry for opening the issue, I'm used to Blender addons to come in premade zips. Thanks for your help.

**Comment by soryy708** [comment]
should probably add the missing step to the instructions in the readme: https://github.com/Skylumz/Sollumz/blob/main/README.md
