### ISSUE TITLE
YFT skel_meshes lack meaningful names

### ISSUE THREAD

**Issue by soryy708** [Skylumz/Sollumz#116]
When importing a YFT, the `skel_mesh`es are placed under `Sollumz Drawable Model`, and inside there are Vertex Groups with meaningful names.
Looks like the Vertex Groups are given names by the `<Name>` of the bone `<Item>`,
and are grouped in to `skel_mesh`es via the `<ParentIndex>`.
I think that the name of the `skel_mesh` should be the `<Name>` of the bone `<Item>` that's the root of the hierarchy of bones.

**Comment by Skylumz** [comment]
Please join the discord (link in wiki) and explain more in detail?
