### ISSUE TITLE
Drawable mesh needs to be triangulated on export

### ISSUE THREAD

**Issue by CFox04** [Skylumz/Sollumz#139]
If the mesh contains n-gons, ``mesh.calc_tangents()`` will throw an error. ``mesh.calc_loop_triangles()`` does not fix this error, so it must be triangulated either through bmesh or the triangulate operator (if its possible to do so without affecting the original mesh).

**Comment by MoosheTV** [comment]
A possible hack for this is to apply the triangulate modifier, use `bpy.context.object.to_mesh(bpy.context.scene, True, 'PREVIEW')` to generate a new mesh without applying the modifier to the original mesh, and do the calculations after that. Once that's finished, dump the triangulate modifier.

I've not tested this but I'll give it a go later today.

**Comment by CFox04** [comment]
I ended up fixing it by just doing
```py
tempmesh = bmesh.new()
tempmesh.from_mesh(mesh)
bmesh.ops.triangulate(tempmesh, faces=tempmesh.faces)
tempmesh.to_mesh(mesh)
tempmesh.free()
```
