### ISSUE TITLE
YBN - Linked Materials

### ISSUE THREAD

**Issue by Denis-3D** [Skylumz/Sollumz#154]
Not sure if the bug or not been implemented yet.

Every object with the same COLLISION MATERIAL is linked and uses the same flags and properties.
The screenshot show example of one BOX that by default has no flags but in Blender have way more. 

Files used for testing: hei_dt1_20_0

![image](https://user-images.githubusercontent.com/7430830/141946873-f97e6117-3894-422a-87e7-abfd7b71f811.png)

**Comment by Skylumz** [comment]
will be looked into thanks, have you checked exporting?

**Comment by Denis-3D** [comment]
Yes, I tried with a custom object that I made the same results. Everything is linked even if i UNLINK material and change flags.
And same with Imported -> Exported vanilla game object example: hei_dt1_20_0 it makes all MATERIALS using same flags.
