### ISSUE TITLE
After ydr.xml export, Material Shader has been shuffled

### ISSUE THREAD

**Issue by Rigonkmalk** [Skylumz/Sollumz#158]
Tested on :

- main branch
- Release 1.0.a posted on Discord

Step to reproduce :

I used a mesh with 16 Materials (no spec / no alpha / no normals)
- Create a drawable
- Use Convert Material to Shader Material

On this photo you will see all the Materials sorted in a good way

![material_converted](https://user-images.githubusercontent.com/12967235/142231409-8697470d-5f33-42f6-b84e-4cf03d2d6941.png)

Looking like this :

![mesh_right_material](https://user-images.githubusercontent.com/12967235/142231540-ead7fa82-d6b9-44a3-b0e6-b1e1ca9e05a2.png)

After export, I saw all of my Materials shuffled in a random sort :

![material_shuffled_after_export](https://user-images.githubusercontent.com/12967235/142231631-d1c5095c-4b7a-4469-ae91-8868a53ce669.png)

After exporting ydr.xml on cw, not looking the same than blender render :

![after_exporting](https://user-images.githubusercontent.com/12967235/142231721-26ce5d2f-8e45-4ec3-ab30-7b3b62094b39.png)

**Comment by Rigonkmalk** [comment]
Ok, after few tries, every time I export my model, all the Materials has been shuffled in another random sort :

![image](https://user-images.githubusercontent.com/12967235/142232147-ea69a0ed-d26a-42af-bd98-9827caee134a.png)

**Comment by Skylumz** [comment]
Do you have every single material on each object? If so try removing all of them except for the needed material
