### ISSUE TITLE
RoomID missing on Import / Export

### ISSUE THREAD

**Issue by Denis-3D** [Skylumz/Sollumz#159]
Testing file:

v_gun.ybn

Scenario 1: After importing to Blender directly from CodeWalker XML RoomID are reset to 0
Scenario 2: Setting up RoomID by hand then exporting to game/CodeWalker shows RoomID as 0 again.
Scenario 3: Setting up RoomID by hand then exporting and importing back to Blender shows correct RoomIDs

**Comment by Skylumz** [comment]
strange will look into this thanks
