### ISSUE TITLE
Import .ydr.xml error  : key "Normal Map" not found

### ISSUE THREAD

**Issue by LowZhangBao** [Skylumz/Sollumz#165]
When I processed this file, a problem occurred.

file name : ch_chint01_reception_desk.ydr.xml
file drive : 
https://drive.google.com/drive/folders/1DFtUeRCwRdOZ_8Gp7lsKoDXIBu5zEN4J?usp=sharing

I get this error message .
 
![image](https://user-images.githubusercontent.com/39294308/143083526-dece17a1-194f-4990-82dd-bef2ac280d2f.png)

What should I do to deal with this problem?

**Comment by Skylumz** [comment]
I will look into this as soon as i can

**Comment by Skylumz** [comment]
This error seems to have been fixed
