### ISSUE TITLE
Correct display GTA5 Normal Maps in Blender

### ISSUE THREAD

**Issue by kirill-mapper** [Skylumz/Sollumz#166]
Since GTA uses DirectX normal map. To display it correctly in Blender, you need to convert DX normal to OpenGL, for this you need to invert the green channel, through the Math / Subtract or Invert node
![изображение](https://user-images.githubusercontent.com/95088806/143593480-caf97c1c-aa64-46ab-b354-9ae0eecc799c.png)
ATI2 Normal Maps does not use the blue channel, it is always completely black. For the correct display of the ATI2 normal map, the blue channel must also be inverted in this case, or simply put a node with white color( _ATI2.dds is not readable by Blender, so the modified display will not work for this type of texture. It is necessary to convert in advance to another format_ )
![изображение](https://user-images.githubusercontent.com/95088806/143593541-7825eb88-294f-461f-8c71-55acce872103.png)

**Comment by dolutattoo** [comment]
What do you guys think about `RGB Curves` node?
The only usefull thing (imo), is to do is invert the green channel.
Look at the difference:
https://streamable.com/mpm2g4

**Comment by coltfox** [comment]
Implemented in d502eb0e97e708a4c4199a7f080fd8bd373b5e4b
