### ISSUE TITLE
YDR export with vertex groups causes issues

### ISSUE THREAD

**Issue by MoosheTV** [Skylumz/Sollumz#167]
Exporting YDRs with vertex groups causes an issue where the assigned vertices to a vertex group will default to the origin position.

How to reproduce on latest version (90df333):
- Create a drawable with some (not all) vertices assigned to a vertex group
- Export drawable to `*.ydr.xml`
- Import into codewalker
- The vertices assigned to the vertex group will all be at the origin position

Currently the workaround for this is to unassign all vertices from vertex groups before exporting.

How it looks when exported with vertex groups:
![image](https://user-images.githubusercontent.com/41531803/144338824-7fbdb92f-74ab-47ad-9619-766e4bccb27e.png) ![image](https://user-images.githubusercontent.com/41531803/144339219-795dddc6-a08e-47e6-9eb0-2dc4ce6c8c02.png)

How the vertex groups are assigned:
![image](https://user-images.githubusercontent.com/41531803/144339254-5a84d07f-e22b-4511-8c82-a54d5f62cf0e.png) ![image](https://user-images.githubusercontent.com/41531803/144339268-d5bc2eeb-8548-45c3-b25e-180ff87318fa.png)

How it looks by removing the vertex groups when exported:
![image](https://user-images.githubusercontent.com/41531803/144339307-9de2ca11-4532-481e-96eb-fbb56c91a2ce.png) ![image](https://user-images.githubusercontent.com/41531803/144339326-e9a6b36b-1f48-47e8-b329-e648d267078c.png)

**Comment by CFox04** [comment]
Could you send .blend file? If you don't wanna drop it here my discord is colton#5371
