### ISSUE TITLE
Funding?

### ISSUE THREAD

**Issue by soryy708** [Skylumz/Sollumz#168]
Sollumz is a large undertaking, and since it's FOSS (MIT License) it's extremely valuable to the modding community.
I'm confident that some people are willing to pledge money to accelerate progress.
Some projects (like [webpack](https://webpack.js.org/)) actually raise funds to fund the development and maintenance of their open source project.

What do you think about setting up a way for people to fund Sollumz and create additional incentives for maintainers/contributors?
For example, funding bug/feature bounties or paying contributors proportionally to how much they contributed.

Some options:
* [opencollective](https://opencollective.com/)
* [github sponsors](https://github.blog/2019-05-23-announcing-github-sponsors-a-new-way-to-contribute-to-open-source/)
* [patreon](https://www.patreon.com/)

**Comment by Skylumz** [comment]
what more do you want done?
