### ISSUE TITLE
Empty/Missing Vertex/Poly data on export

### ISSUE THREAD

**Issue by TheOfficialDroid** [Skylumz/Sollumz#169]
Exporting (attached) model, results in everything but Mesh/Poly/Vertex data being exported.

[apa_stairs_01_stla.zip](https://github.com/Skylumz/Sollumz/files/7652361/apa_stairs_01_stla.zip)

**Comment by CFox04** [comment]
You have a drawable inside of a drawable. The hierarchy goes ``Drawable > Drawable Model > Geometry(s)`` https://github.com/Skylumz/Sollumz/wiki/Importing-and-Exporting#exporting
