### ISSUE TITLE
Clothing 

### ISSUE THREAD

**Issue by xXPassiveRolePlayerXx** [Skylumz/Sollumz#173]
Clothing Issue
Lower converted to XML and Imported back = No Issue
XML imported into blender. exported out fine. Imported back to CodeWalker Fine = *issue
Issue = clothing item looks fine in the RPF. but in game. its broken. ( dosent show )

Version
I tried all version in #releases  and non could export clothing apart from 1.1.A
all test wer tried numerous times 
not sure if your all aware but yeah

file
Materials
High Detail 1 (2 geometries)
3640 verts, ped (ped sps)
953 verts, ped (ped sps)

file though blender
High Detail 1 (2 geometries)
3637 verts, ped (ped sps)
936 verts, ped (ped sps)

only difference i can find
nothing was touched in blender only import > export

**Comment by Loyalists** [comment]
Which file is the one you attempted to import?

**Comment by xXPassiveRolePlayerXx** [comment]
[First lower that failed.zip](https://github.com/Skylumz/Sollumz/files/7661190/First.lower.that.failed.zip)

**Comment by Skylumz** [comment]
> [First lower that failed.zip](https://github.com/Skylumz/Sollumz/files/7661190/First.lower.that.failed.zip)

![image](https://user-images.githubusercontent.com/35295214/144969566-bf1b2fa1-6071-418f-a647-5d76d3197b41.png)

Works fine for me

**Comment by Skylumz** [comment]
Also exports fine

**Comment by Skylumz** [comment]
Reimo
