### ISSUE TITLE
Blender 3.0 | Issue with convert material to shader material

### ISSUE THREAD

**Issue by tiwabs** [Skylumz/Sollumz#188]
When I try to convert a blender standard to Shader material I got an issue 
My material got Diffuse, Normal, Specular
I've never try this feature with 2.9X
![error](https://user-images.githubusercontent.com/48737497/145856852-545074ef-a771-40f1-bcde-4b4db6b34fdc.png)
![shader](https://user-images.githubusercontent.com/48737497/145856855-61141b28-6220-43af-8233-ad379e1594f4.png)

**Comment by Skylumz** [comment]
This should be fixed now please let me know if you have any issues :)
