### ISSUE TITLE
YDD import ignores any drawables which have similar names

### ISSUE THREAD

**Issue by MoosheTV** [Skylumz/Sollumz#204]
**Issue:**
If a drawable dictionary includes multiple drawables with similar names (which seems to be a common occurrence in Drawable Dictionaries), it will not load the drawables with re-occurring names outside of the first one.

**Current workaround:**
Edit the XML file and append `_{n++}` to the name, so each drawable has a unique name. This allows Sollumz to load them up. Then, once finished, re-edit the drawable names, removing the appendage.

**Example:**
Here's what the hierarchy looks like loading up `lr_sc1_02_sc1_emissive_slod_children.ydd.xml` without making any modifications:
![image](https://user-images.githubusercontent.com/41531803/146667366-37ce4943-cfd7-4f5b-ba62-9aca3023f72e.png) ![image](https://user-images.githubusercontent.com/41531803/146667428-42b47967-9d77-4bf5-9666-56501ec6b803.png)

Here's what it looks like when appending the names so they're unique:
![image](https://user-images.githubusercontent.com/41531803/146667351-1560c244-8f58-484e-9335-5293bbd34f4c.png) ![image](https://user-images.githubusercontent.com/41531803/146667419-5a260cbd-25b6-42cd-8d6c-ab2d20207177.png)

**Comment by Skylumz** [comment]
@CFox04 you made drawable dictionaries act as python dictionaries guessing this is because the keys are the same
