### ISSUE TITLE
Issue with importing YDR prop in blender, exported with CodeWalker

### ISSUE THREAD

**Issue by theM4RI0** [Skylumz/Sollumz#212]
Hey, i exported prop from rpf explorer by searching it in the search bar, (prop name - imp_prop_impexp_postlift_up) 
![image](https://user-images.githubusercontent.com/40245545/147074546-facd4cf2-916d-4d3e-94e3-d70302a4f493.png)

added to Shared textures folder in the preferences folder with the textures from car lift 
![image](https://user-images.githubusercontent.com/40245545/147073741-8c5956c8-7160-4dae-9228-0843383f8c48.png)

but it appears with different color and collision being broken? (placed in world origin)
![image](https://user-images.githubusercontent.com/40245545/147074978-a4f22120-2f3e-4316-bf4b-6dfda2b948fc.png)

and if i select tintPaletteSampler texture in blender, it still doesn't show correct colors/texture
![image](https://user-images.githubusercontent.com/40245545/147075175-71ba2085-7828-4566-8694-83fc669f77b6.png)
![image](https://user-images.githubusercontent.com/40245545/147075249-b7f98535-3690-410e-8f0e-9e6c45b2ef66.png)

**Comment by CFox04** [comment]
The collision issue is fixed in https://github.com/Skylumz/Sollumz/pull/218. We will look into the tint issue

**Comment by coltfox** [comment]
Fixed on yft branch (will be merged soon)
