### ISSUE TITLE
anims support

### ISSUE THREAD

**Issue by ilovefisitng** [Skylumz/Sollumz#221]
How is the animation work going? When the information appears, I have heard that Sollumz will support custom animation, but I have not found any information on whether work is underway on this and at what stage it is.

**Comment by CFox04** [comment]
Skylumz and I are working on fixing bugs and getting yft import/export working—those are our highest priorities. There is another contributor who has been working on animations on his own, but I am not sure where he is I haven't heard from him in awhile. It is in on the todo-list but not our top priority at the moment.

**Comment by Hancapo** [comment]
You can use AnimKit if you need to do custom animations.
