### ISSUE TITLE
YFT import does not support "damaged" part

### ISSUE THREAD

**Issue by MARK2580** [Skylumz/Sollumz#23]
I have no idea if this is the fault of CodeWaker or your script, but after importing yft.xml, only the model and its loots are loaded into Blender, but there is no model simulating a broken model.
![TSurptk7Z7](https://user-images.githubusercontent.com/11617079/119851706-4eac4d80-bf17-11eb-9300-0b6cbdb5de05.png)
![f3sPtL060o](https://user-images.githubusercontent.com/11617079/119851721-50761100-bf17-11eb-8d2f-62495d1db22e.png)

**Comment by Skylumz** [comment]
hm good find, if you find any other bugs or things that are not importing correctly feel free to join codewalkers server and report them - https://discord.gg/BxfKHkk

**Comment by MARK2580** [comment]
> hm good find, if you find any other bugs or things that are not importing correctly feel free to join codewalkers server and report them - https://discord.gg/BxfKHkk

I would be happy to report, I am even a member of this community, but 99% of chats are closed for me, I can not write anything there

**Comment by MARK2580** [comment]
> hm good find, if you find any other bugs or things that are not importing correctly feel free to join codewalkers server and report them - https://discord.gg/BxfKHkk

A whole year has passed, the plugin still does not know how to import "damaged" parts of models ???
