### ISSUE TITLE
Size values are hot passed to the shape panel

### ISSUE THREAD

**Issue by d1n3301** [Skylumz/Sollumz#231]
Parameters are not transferred to the panel, it says that 0 although there is not 0
This can be seen in the screenshots, it is also necessary to check on other "Bound objects".

The name of this particular collision: ch3_10_0
But you can also check for others where there are spheres, capsules and more from the list "Bound"

![KfpmtuvyAS](https://user-images.githubusercontent.com/94755823/149943060-82920083-7318-4e85-a7a9-a43558500876.png)
![HeylGToDOI](https://user-images.githubusercontent.com/94755823/149943073-a155dc96-3f79-4a9d-81c6-c32aefd2accb.png)

**Comment by Skylumz** [comment]
hmm, is it set to 0 on import? and then if you change it export and import again its 0?

**Comment by d1n3301** [comment]
I imported this collision (with others that are also standard from GTA), and the radius or other parameters are equal to zero.
Haven't tried exporting and then importing.

**Comment by CFox04** [comment]
That's weird. Must have broken something, because it was working fine before. I'll look into it
