### ISSUE TITLE
Exporting YDR with normal_spec_detail

### ISSUE THREAD

**Issue by Denis-3D** [Skylumz/Sollumz#232]
Issue:

Exporting a file from Blender that contains normal_spec_details shader that uses 'ENV_*' texture seems to do something weird. At first, it seems to works fine in CodeWalker, In-game, and I can easily import-export it again. But when I'm trying to open the file inside OpenIV it crashes the program. I know that we don't like OpenIV but still seems like an odd thing and might cause problems in the long run and prevent edits by people using GIMS/Max combo.

**Example of a file that I edited _id2_07_gar1_b.ydr_**

_After a small research, I noticed that Sollumz create an extra line for that specific shader (screenshots attached)_

**Software used while testing:**

Blender 3.0
CodeWalker Dev41
Sollumz most recent from GitHub

**Before editing in Sollumz**
![image](https://user-images.githubusercontent.com/7430830/150167109-6a539dfe-f4b2-4922-933a-b85cd4032686.png)
**After editing in Sollumz**
![image](https://user-images.githubusercontent.com/7430830/150166357-639a2f3e-6899-47b1-a6cd-71d6b8ce68aa.png)
**OpenIV Crash Errors**
![image](https://user-images.githubusercontent.com/7430830/150166099-e296b39a-aba6-4055-a969-c1478d13dc60.png)

**Comment by Poker2Duo** [comment]
This is trouble OpenIV

**Comment by Lucas7yoshi** [comment]
OpenIV has had issues reading files via sollumz for a while. it is not intentional but the issue isn't easy to solve because oiv is closed source


I'm not a sollumz dev though but I'm pretty sure I brought it up a while ago

**Comment by Denis-3D** [comment]
Yeah make sense, but still, this extra line displaying even in CW is kinda a sus. 

It's not there in non-edited files.

**Comment by Lucas7yoshi** [comment]
> Yeah make sense, but still, this extra line displaying even in CW is kinda a sus.
> 
> It's not there in non-edited files.

I see that

I think was a PR to fix case sensitivity for some shaders, perhaps that will fix it.

the parameter got screwed up. I guess maybe OIV is not as resilient as CW

try checking the XML that comes out of sollumz to see if you can see what that thing is before it gets hashed
