### ISSUE TITLE
Error when exporting Drawable with geometries that contain multiple materials and some that dont

### ISSUE THREAD

**Issue by CFox04** [Skylumz/Sollumz#235]
If you export a Drawable where one of the geometries has multiple materials and other geometries only have one you will receive this error: 
```
Error exporting: Cube.ydr.xml 
 Traceback (most recent call last):
  File "sollumz_operators.py", line 230, in export_object
    export_ydr(self, obj, filepath, self.export_settings)
  File "ydrexport.py", line 724, in export_ydr
    drawable_from_object(exportop, obj, filepath, None, None,
  File "ydrexport.py", line 689, in drawable_from_object
    drawable_model = drawable_model_from_object(
  File "ydrexport.py", line 401, in drawable_model_from_object
    if child.sollum_type == SollumType.DRAWABLE_GEOMETRY:
ReferenceError: StructRNA of type Object has been removed
```
![image](https://user-images.githubusercontent.com/46362482/150428767-75618c5d-76ae-462b-8ceb-5945a09306b0.png)

This has to do with all the objects getting joined here: https://github.com/Skylumz/Sollumz/blob/main/ydr/ydrexport.py#L409. During this loop, it will discover the object with multiple materials, split that object, but then join ALL the remaining child objects of the drawable model. This causes the ``child`` object on the next iteration to be none which produces the error. I think the real solution here is to change the way we split objects by material because it's kind of hacky and affects the Blender objects in the scene without making copies which is dangerous. This is also the reason why materials are "shuffled" on export when the objects are split.

**Comment by whotter** [comment]
Im sorry, i did not quite get how to resolve this problem or is there any solution?

**Comment by coltfox** [comment]
@whotter This was fixed over a year ago. Just update Sollumz and make sure to download from the GitHub https://github.com/Skylumz/Sollumz/wiki#installation
