### ISSUE TITLE
Should get_direction_of_vectors (a, b) crash or return if a == b?

### ISSUE THREAD

**Issue by ZiDeveloper** [Skylumz/Sollumz#240]
As found in "sc1_00c_0.ybn" it appears that one capsules rotation could have been stored by the same vector.

`[...] <Capsule m="0" v1="8" v2="8" radius="0.0537596084" /> [...]`

This might be an corrupted piece from R* development since CodeWalker and OpenIV return the same here ~~(could still be something with the export)~~. This will result in crashing the import at calculating the angle.

One way of fixing this would be setting the direction to the axis align vector in case both **a** and **b** equal each other. And ofcouse this will return an angle of zero but should it? _CodeSource Fabian here_

If it did we (thanks to V3ryH1GH) would not have found this broken collision and might result in further problems down the line.

What are your thoughts on this?

**Comment by Skylumz** [comment]
does your pr fix this
