### ISSUE TITLE
LOD exporting is bugged.

### ISSUE THREAD

**Issue by WinterPsycho** [Skylumz/Sollumz#245]
So when when I (latest versions of both codewalker and this tool) export a LOD to edit, the export works fine, you can edit it and save it just fine, but when you go to stream it to a fiveM server, the edit just shows at all times, instead of only when far.

The lod in question I tried editing is cs4_06_l1_slod1_children.ydd

I did notice between the two XMLs (Edited and unedited) a few flags don't get saved, I tried manually adding the flags that were removed, but that also didn't fix the problem unfortunately. 

I can provide any other information that's required if it means this problem could be fixed.

**Comment by WinterPsycho** [comment]
I'll also note, I had set the lod to "depth LOD" at first trying to see if that'd work, it didn't change anything, and if I tried changing the drawable models lod level to medium, that just crashed the local area.

**Comment by Skylumz** [comment]
are you just replacing the ydd file?

**Comment by WinterPsycho** [comment]
May I ask what you mean by replacing? Because this is meant to be a fivem streamable change, not a single player mod

It might be easier for us to communicate over discord if you'd like to move there, I could provide images that way.

**Comment by WinterPsycho** [comment]
Hello, I've further understood the issue. Somehow, after editing the SLOD1 meshes, SLOD1 now gets forcefully enabled over LOD and HD.

I will attach a video to hopefully make it easier to understand.

[This is a google drive link, please let me know if you're uncomfortable with it.](https://drive.google.com/file/d/13Po64_wW1MmKW5OmlQ76ehwrjFIo6SyE/view?usp=sharing)

**Comment by CFox04** [comment]
This appears to not be a Sollumz issue. I exported the .ydd file in question into my mods folder and reproduced what you did in the video. I had the same result. SLOD1 was appearing in ORPHANHD, HD, and LOD modes. I didn't make any changes to the ydd in Sollumz. You should make a post in the CodeWalker discord, they would be more helpful.
