### ISSUE TITLE
lights flags reset after exporting

### ISSUE THREAD

**Issue by NekMonn** [Skylumz/Sollumz#248]
the light flags value are reset to 0 after exporting and time flags too

**Comment by ZiDeveloper** [comment]
For some reason the **Total** of all flags it not updated/calculated on import or at least not stored correctly.

For now you can update it yourself. Just go through each light object and toggle at least one flag in **Flags** and **Time Flags** to calculate to total.

https://user-images.githubusercontent.com/6891250/151644471-c748b93d-41c4-4f39-9eab-818e8b138597.mov
