### ISSUE TITLE
Better Material Editor and conversions

### ISSUE THREAD

**Issue by Hancapo** [Skylumz/Sollumz#252]
Right now the current material workflow can be really frustrating, due to the lack of several options that could potentially improve user usability, some useful functions could be: 

**1. Select a material from a mesh and convert it to the desired material, instead of having to setup a whole new material.** (_A dedicated window just for materials could be a good idea too, so we can select and convert multiple ones to whatever shader we want (if applies)._)

![image](https://user-images.githubusercontent.com/20731612/151712831-5321c839-f846-4d59-b823-ca13a9391a05.png)

**2. Change shader materials dynamically**

![image](https://user-images.githubusercontent.com/20731612/151713067-936d16b1-bb47-495f-94a0-f8aef78eec9b.png)

**3. Auto Render Bucket values for shader materials, (example: non zero BR values for `cutout_fence`, `cutout`, `decal`, etc.)** 
![image](https://user-images.githubusercontent.com/20731612/151713301-6b335e94-3e74-4f1b-acdd-f21590da2035.png)

**4. Detect if there's something linked to the alpha node and then when doing the material conversion it became something like decal or cutout/cutout_fence, ask the user or whatever.**

**5. Convert Sollumz material to standard ones, so the models can be exported outside Blender properly**

**Comment by Skylumz** [comment]
Each shader is so unique it would almost be impossible for me to be able to to know what textures to assign which texture parameters from when converting to a sollumz shader or converting to a different sollumz shader... so 1, 2, 4 are pretty much outta the picture. As for auto setting render bucket it is something I am going to look into. as far as materials not exporting correctly when they are not a sollumz shader Im not sure I know what you mean? also this kinda is in the same category as 1,2,4 because each shader is so unique. Ill leave this here for now maybe I can think of a way to do it.

**Comment by Hancapo** [comment]
There is no need to know the parameter as they all have exactly the same name for each parameter if it exists in the other shader in the first place. For example:

If we need to change a shader that is `decal_tnt` to `normal`, ignoring the part where we don't have a BumpSampler, we still have the DiffuseSampler in both shaders, it just has to take from one shader to another the Samplers/Parameters which exists, I think that you just have to bring the Samplers, and everything should be default values to make it simpler.

![image](https://user-images.githubusercontent.com/20731612/151722830-984217b1-511d-4c14-88e0-0e1a90133c6f.png)

With (5.) I meant to use Blender as a proper bridge to bring V assets elsewhere, not to back to V, since I tried to do so but for some reason, the UV maps were not existent.

**Comment by Skylumz** [comment]
> 

I know how it would work lol, its just that some shaders dont have a diffuse sampler but a texture sampler for the main texture etc.. anyway like I said I may think of a way to do it. hm uvs should always be existent unless you delete them they are created just how you would create any other model for any other game / engine so sounds like you made an error somewhere maybe in the export settings?

**Comment by Skylumz** [comment]
Latest commit added some of these features :)
