### ISSUE TITLE
Improvements for Collision Edition/Creation

### ISSUE THREAD

**Issue by Hancapo** [Skylumz/Sollumz#256]
### 1.

When I have finished splitting my meshes to prepare collisions I always find myself in this situation where I have to create several `Sollumz Bound Composite` to fully export my mesh by parts, but this process can be tedious when you have, let's say 50 meshes. 

So one idea that I already make true outside Blender was to create a UI where users can select all the mesh parts and decide how many `Sollumz Bound Composite` AKA `"YBNs"` will be created based on the division of (`How many parts per composite / current parts`)

500 meshes divided by 50 will create 10 "`YBNs`"
![image](https://user-images.githubusercontent.com/20731612/152492063-d81195b1-653a-41aa-8af8-89cc5c6b0cbb.png)
Along with a collision, a basename to set the names of the `Bounds` to the decided name with an incremental numeric suffix.

### 2.

Following the last idea which involved converting selected materials to selected Sollumz' one, (which was implemented to Shader conversion stuff within `Drawables Tools`)

This could apply to collision materials, so I don't have so much to explain, is the same.

### 3.

A button/checkbox that creates a default embedded collision to an already setup `Sollumz Drawable` (by default I mean with the default flag applied and the default collision material too.)

### 4.

Something to remove every single material in selected meshes and assign (this happens automatically when exists just one material on the material list) the selected Collision Material

![image](https://user-images.githubusercontent.com/20731612/152495295-d80446f3-6483-46b3-a53d-47706124b43f.png)

![image](https://user-images.githubusercontent.com/20731612/152495312-cb8c707d-b134-4460-ae26-9145fb2d117a.png)

**Comment by CFox04** [comment]
implemented
