### ISSUE TITLE
Blender Import

### ISSUE THREAD

**Issue by Xivkyn** [Skylumz/Sollumz#257]
Hii. I can import and export things using CodeWalker and Sollumz from the rpf that are in the game's root. But not from Update/x64/dlcpacks/patchday8ng/dlc.rpf/x64/models/cdimages/weapons.rpf.

Is there maybe something I'm missing?

![image](https://user-images.githubusercontent.com/36720089/152645436-ad6652d2-b4da-4239-9178-968b930a63fa.png)

I'm sorry in advance if this is the incorrect place to post this.

**Comment by ZiDeveloper** [comment]
Does this happen to every .ydr or just some?

Which .ydr gives you this error?
