### ISSUE TITLE
Support animation future? 

### ISSUE THREAD

**Issue by Iknowyou808** [Skylumz/Sollumz#261]
Will sollumz support animations? I'm curious to know how you can add mocap (motion Matching), animation in gta 5, since there are a lot of free mocap animation on the Internet, I hope you will do about this wiki someday, should we expect support this year?

Check rokoko Library / actorcore Library.

**Comment by kemperrr** [comment]
https://github.com/Skylumz/Sollumz/wiki/YCD-%7C-Animations---Introduction

https://github.com/Skylumz/Sollumz/wiki/YCD-%7C-Import-&-Edit-&-Export

🤔
