### ISSUE TITLE
multiple error exporting ydr.xml

### ISSUE THREAD

**Issue by kathryn2101** [Skylumz/Sollumz#263]
I keep getting these errors when im exporting the ydr.xml that ive been working on

i dont understand why im getting it but it pops up even when im not importing props

how do it fix this issue

https://i.imgur.com/3kYm1kn.png

**Comment by dolutattoo** [comment]
You need to have at least one UV, like this:
![image](https://user-images.githubusercontent.com/47056777/154170151-71015f53-d0d5-4006-b01a-17acaf459378.png)

**Comment by kathryn2101** [comment]
that didnt work https://i.imgur.com/vVyszuX.png

**Comment by kathryn2101** [comment]
ok i fixed that issue but now i got this erro
![blender_SWowRbg1aB](https://user-images.githubusercontent.com/89110153/154280587-63fc1495-2ddf-42ba-a8f5-ed49466aaf5d.png)
r

**Comment by Skylumz** [comment]
please join the discord at https://discord.gg/sD9ckSd6
