### ISSUE TITLE
Update Texture Dictionary for each archetype

### ISSUE THREAD

**Issue by theM4RI0** [Skylumz/Sollumz#265]
If you have multiple archetypes, like a lot (more than 50), and you need to add name of the texture dictionary aka YTD to it by hand rn, which can be painful and time consuming to go through each of them. Would be easier, faster and better to have a button may be to "Sync" or "Update" each Texture Dictionary for each archetype. That will save a ton of time.

![image](https://user-images.githubusercontent.com/40245545/155001267-aa5232e4-7e86-4dd0-b8c9-dd7b2941cf5f.png)

**Comment by Hancapo** [comment]
Added in #394
