### ISSUE TITLE
Blender crashes on export of this file

### ISSUE THREAD

**Issue by Walter-00** [Skylumz/Sollumz#268]
We've found this one lod file that seems to crash blender when you try to export it. Here is the: [file](https://cdn.discordapp.com/attachments/910313619537952809/946134841244647464/dt1_lod_slod3_children.ydd.xml)

3 different people on the discord have tried this, and all have had the same result of blender just freezing up/stalling.
Even without modifying this file at all, we're unable to export it.

**Comment by CFox04** [comment]
This is strange. It also seems to crash when switching to edit mode.

**Comment by CFox04** [comment]
Fixed with commit 4e4873ef38e2b0299cfb473ded4a48e4b5609e48 . Although we will have to get to the bottom of why some of these meshes are invalid in the first place I'll make a new issue.
