### ISSUE TITLE
Importing cloth props (YFT) empty

### ISSUE THREAD

**Issue by MARIO228** [Skylumz/Sollumz#269]
Tried importing cloth props, that has physics, and it imports empty in blender in the latest version of sollumz from github.
Names of 2 props that i tried importing - dt1_02_cloth1, prop_airdancer_2_cloth.
Blender 3.0

![image](https://user-images.githubusercontent.com/40245545/155813558-0779ea6b-2ae7-4e66-ac30-9259907a6fc3.png)
^^^this is prop_airdancer_2_cloth, another pic of it down

![image](https://user-images.githubusercontent.com/40245545/155813575-fe80dee1-ab5b-4b27-93fa-981c9d89e644.png)

**Comment by CFox04** [comment]
This is not implemented yet.
