### ISSUE TITLE
Issue with exporting Lights with Sollumz

### ISSUE THREAD

**Issue by MARIO228** [Skylumz/Sollumz#270]
Added lights, embedded them to drawable, added all flags and changed all the values that i needed
![image](https://user-images.githubusercontent.com/40245545/155862374-63555f84-9667-4068-98ba-a52f3d8f2448.png)

but getting this error (version of sollumz is latest up to 25.02.2022)
![image](https://user-images.githubusercontent.com/40245545/155862367-d978a04f-f30a-47f1-ab2a-6f73ddea24bd.png)

Would like to use that tool, since it's very easy to setup in blender and quick to adjust.

**Comment by CFox04** [comment]
The lights should be directly under the drawable, not under a drawable model.
