### ISSUE TITLE
Issue with material and exporting

### ISSUE THREAD

**Issue by AdrianKhorany** [Skylumz/Sollumz#275]
I was experimenting with the Sollumz plugin and I am pretty new to blender and decided to port a minecraft world in there and try export it to a ydr xml. I am unsure why it is saying that I don't have a material on the objects. Kinda need help with this
![image](https://user-images.githubusercontent.com/54457761/156167752-cffebe31-74ac-47d8-88c0-158089f0e8db.png)

**Comment by MARIO228** [comment]
Show us sollumz tab in material tab, and did you convert shader?
Also wgat version of sollumz and blender are you using?

**Comment by Hancapo** [comment]
You're supposed to use the lastest Blender version, that's the issue.

**Comment by CFox04** [comment]
Did you create these materials through the Sollumz "Create Shader" panel? If you did and you are still getting this error then send your blend file.

**Comment by CFox04** [comment]
Since this has been inactive for a while and looks like it's not a bug I'm going to close this. If you try our suggestions and still have issues feel free to repost.
