### ISSUE TITLE
Broken exterior UVs on .YFTs (Vehicles)

### ISSUE THREAD

**Issue by KaesarZZ** [Skylumz/Sollumz#28]
I'm just trying to import some vehicles and I am having problems on the exterior UV's, and that's weird because for example most other UV's work fine....

Just imported the .xml on blender:
https://i.gyazo.com/aca62aa0b54ad5192f9a6dbf1ef59d77.png

On 3DS max (since I use it more than blender):
https://i.gyazo.com/a7cd5fcb41fe8f20766a80eb971c393f.png

Other UV's works perfectly: 
https://i.gyazo.com/c95be14e44886599ea3c57c60b783073.png

Example Model: https://www.gta5-mods.com/vehicles/1999-ford-crown-victoria-taxi

But I repeat myself, I am having these problems in 2-3 previously tested models so seems common. Something fixable or am I doing something wrong?

**Comment by Skylumz** [comment]
plugin is wip, a major update is on the way
