### ISSUE TITLE
Light : Color issue on export

### ISSUE THREAD

**Issue by Rigonkmalk** [Skylumz/Sollumz#285]
Version of Sollumz used : Last version of Sollumz (git pull 10 minutes ago)

Issue : Light

After tweak light in 255 / 255 / 255 RGB value for white color, I found an issue on export

![image](https://user-images.githubusercontent.com/12967235/158840623-71f5dca8-6264-4946-a714-bb6e1bd1f089.png)

On .ydr.xml file, colour line for every light (duplicated) :

`<Colour r="65025" g="65025" b="65025" />`

On CodeWalker RPF Explorer, the Colour attribute is black :

![image](https://user-images.githubusercontent.com/12967235/158841630-de649f10-626d-48f2-bd76-f09298c453c6.png)

**Comment by CFox04** [comment]
Why are your RGB colors from 0-255? Thought they were always from 0-1? 
![image](https://user-images.githubusercontent.com/46362482/159168111-d191d1a7-0e7c-438e-a835-2114e791a987.png)
