### ISSUE TITLE
Embedded Collisions bugged

### ISSUE THREAD

**Issue by Denis-3D** [Skylumz/Sollumz#286]
Issue: Importing then Exporting files with embedded collisions bugs them.

Software:
- Blender 3.1
- Sollumz GitHub version downloaded today (19.03.2022)
- CodeWalker v42

Very easy to reproduce, and happened to me on many objects. 
For this test I grabbed 2 vanilla GTA files with two different Bound types:
- tr_prop_tr_door2 with Bound Geometry
- tr_prop_tr_iaa_base_door_01a with Bound Composite

Nothing else to this object is done except RPF Export XML -> Sollumz Import -> Sollumz Export -> RPF Import XML.

The collision of these objects looks fine in the RPF viewport with 'Show collision meshes' enabled. But in-game they act not properly. Like they are 'scaled' or something. So the camera can clip and bullets only hit in the middle of the object.

I feel like the problem occurs on 'Import' to Sollumz and it exports objects badly. When I create everything from scratch in Blender & Export with Sollumz usually there are no problems unless I mess up.

Bullets appear only on this part
![image](https://user-images.githubusercontent.com/7430830/159131573-0804be4d-da2c-4daf-9b40-8644e711886a.png)
Camera Clipping
![image](https://user-images.githubusercontent.com/7430830/159131628-e2855bc0-7c1b-493e-8f76-db9f43d9e7c5.png)

**Comment by Hancapo** [comment]
This is something I've noticed some time ago, this also happens with static collisions, there's a precision issue and the decals are the worst part.
