### ISSUE TITLE
Textures added from Sollumz Material panel appear black

### ISSUE THREAD

**Issue by Denis-3D** [Skylumz/Sollumz#287]
Adding texture/changing textures from the Texture Parameters panel appears black or not updated at all in the Blender viewport. (screen1)

Export seems to work fine (screen2)

Another thing I noticed is that adding the same texture creates a 'duplicate' in the Blend file unnecessary bloating Blend file size and a mess (screen3)

![image](https://user-images.githubusercontent.com/7430830/159155390-d94f5a85-5663-4557-b8a2-ac0afd659ccd.png)

![image](https://user-images.githubusercontent.com/7430830/159155499-a7e8fe9b-a5c2-478e-bc32-510c62e10288.png)

![blender_4839](https://user-images.githubusercontent.com/7430830/159155680-6b9da837-fb7c-46a0-b41d-4a26525b6307.png)

**Comment by CFox04** [comment]
Pushing a fix for the first issue mentioned. When you set the texture path, it's not creating a new image, but just changing the path of the image data block being used by the Image Texture node. So if the image exists in the file already you would want to delete the currently used image and select the desired image using the dropdown in the image texture node (the one you have open in the last screenshot).
