### ISSUE TITLE
Suggestion: Create Drawable at object location

### ISSUE THREAD

**Issue by Denis-3D** [Skylumz/Sollumz#289]
Currently pressing Create Drawable on objects that are not placed at 0,0,0 Creates Drawable and Drawable Model (empties) at 0,0,0. 

Right now we need to move Object to 0,0,0 make Drawable and move it back where it was to keep the position on YTYP/YMAP

Would be handy to make a toggleable option to use 'Object position' for creating Drawable so we can skip the process of moving objects left & right and just keep it where we want.

Also, I tried to just move (Transform Parents) Drawable & Drawable objects to Drawable Geometry as a workaround, but then YTYP generates completely wrong BBs

**Comment by MARIO228** [comment]
good idea, especially for YMAP 👍
