### ISSUE TITLE
On Export, UV Mapping connects unconnected vertices

### ISSUE THREAD

**Issue by MoosheTV** [Skylumz/Sollumz#29]
When exporting a drawable as a YDR.XML file, it appears to mess up the UV Map and connect vertices which are normally unconnected.

Here is what the original UV Map looks like:
![](https://i.imgur.com/SFFdCEq.png)

Here is what happens when exported:
![](https://i.imgur.com/Uv3B7FX.png)

From the looks of it, this seems to be caused by UV Map islands. I did a quick test, and it appears UV Maps where there is no separate vertices, it exports just fine.

I tried to rule out whether it is Codewalker causing the issue, but it appears I cannot re-import the same YDR.XML I exported.

**Comment by Skylumz** [comment]
the plugin is wip, a major update is on the way
