### ISSUE TITLE
Portal count not being calculated

### ISSUE THREAD

**Issue by dunham94** [Skylumz/Sollumz#298]
I wanted to give you a hint , 
"Someone should make a program that when we export the YTYP we can edit the PortalCount directly from the plugin or it can do it automatically, because every time we have to re-open externaly YTYP and go there to manually edit the portalcount from limbo!  "

**Comment by CFox04** [comment]
Portal count is automatically calculated now make sure you are updated.

**Comment by dunham94** [comment]
my limbo every time is 0 !

**Comment by CFox04** [comment]
When is the last time you updated? This used to be a bug but was recently resolved. If you updated and are still having this issue, then send a blend file to reproduce the issue.

**Comment by dunham94** [comment]
Thanks for ur sollution !!
