### ISSUE TITLE
Vehicle YFT Import Issues

### ISSUE THREAD

**Issue by MidgetHD** [Skylumz/Sollumz#301]
I get this when importing non _hi vehicle models. Example used was the base Penumbra.yft. (And yes I know YFT is not supported)

From what I can tell it has something to do with the shattermaps. I ain't no code expert <3

> Error importing: C:\Users\Midget2\Desktop\NP Cars\penumbra.yft.xml 
>  Traceback (most recent call last):
>   File "C:\Users\Midget2\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Sollumz-main\sollumz_operators.py", line 66, in import_file
>     import_yft(filepath, self.import_settings)
>   File "C:\Users\Midget2\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Sollumz-main\yft\yftimport.py", line 244, in import_yft
>     fragment_to_obj(yft_xml, filepath, import_settings)
>   File "C:\Users\Midget2\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Sollumz-main\yft\yftimport.py", line 204, in fragment_to_obj
>     lobj = create_lod_obj(fragment, fragment.physics.lod1,
>   File "C:\Users\Midget2\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Sollumz-main\yft\yftimport.py", line 117, in create_lod_obj
>     wobj = create_vehicle_window_obj(window, group.name, materials)
>   File "C:\Users\Midget2\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Sollumz-main\yft\yftimport.py", line 35, in create_vehicle_window_obj
>     mat = shattermap_to_material(window.shattermap, name + " shattermap.bmp")
>   File "C:\Users\Midget2\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Sollumz-main\tools\fragmenthelper.py", line 36, in shattermap_to_material
>     img = shattermap_to_image(shattermap, name)
>   File "C:\Users\Midget2\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Sollumz-main\tools\fragmenthelper.py", line 20, in shattermap_to_image
>     img = bpy.data.images.new(name, width, height)
> TypeError: BlendDataImages.new(): error with argument 2, "width" -  Function.width expected an int type, not float

**Comment by CFox04** [comment]
This is only an issue in Blender 3.2. It's now fixed in this commit e92ef55dcbd5830ef204681abe40db8421560224
