### ISSUE TITLE
A suggestion from EMBEDDED TEXTURES

### ISSUE THREAD

**Issue by dunham94** [Skylumz/Sollumz#302]
Good afternoon here in Brazil, 
One suggestion, could you put under SET ALL TEXTURES EMBEDDED, which is for SELECTED MATERIALS, a function that sets ALL TEXTURES of the object to EMBEDDED, without having to click ONE BY ONE ...

![image](https://user-images.githubusercontent.com/102479415/161435076-7f6570e9-44c4-428b-9161-7573e98ff1e9.png)

**Comment by Hancapo** [comment]
This is not a bad idea per se, but I do recommend most of the time to don't use embedded textures, and this change will encourage doing models without any texture dictionaries. Which can lead to bad practices.

**Comment by dunham94** [comment]
Yes, I know, but if the model is of small size, few quantities of vertices, few faces, we put embed to accelerate the work because in the end, the sum of weight, will be little! !!

Simillar Like this !!

![simillar](https://user-images.githubusercontent.com/102479415/161435499-38e0e85f-0b22-4ce6-afb5-07531d5b0d78.jpg)
!

**Comment by d1n3301** [comment]
If you say that the model is small, then there are 2-3 textures, and this is 2-3 clicks on the button to make the texture EMBEDDED

**Comment by Hancapo** [comment]
Just use a texture dictionary, there's no **real** reason to embed its textures.

**Comment by CFox04** [comment]
Sorry, I don't think this is necessary, but thanks for the suggestion.
