### ISSUE TITLE
Missing skel text in Target skeleton box

### ISSUE THREAD

**Issue by Kc2693** [Skylumz/Sollumz#306]
There is a very minor but annoying bug happening when trying to import a .ydr and .ycd pair where the 'target skeleton' for importing the .ycd is present, however there is no text, so it's not apparent that the target skeleton has been found. All is working functionally, you just can't see what you're selecting in the target skeleton box.

For this example I am using `v_res_tre_lightfan` and it's associated .ycd file `int_residential`

Here I have imported the .ydr:
![12121](https://user-images.githubusercontent.com/28677397/162594696-25663793-b8fb-44ea-b5fa-62e181f7d295.png)

then I go to import .ycd:
![2](https://user-images.githubusercontent.com/28677397/162594704-d33f185b-43a2-48fe-a01f-53eb8ab2d138.png)
target skeleton box _appears_ empty, but if I were to click on where the first selection is:

![3](https://user-images.githubusercontent.com/28677397/162594716-3a2a5366-8161-4766-8224-c8a73fe9ce0f.png)
it's there, the text is just empty for some reason?

![4](https://user-images.githubusercontent.com/28677397/162594734-518cd770-d39c-467a-9d27-dc314daba4c8.png)
with the invisible selection targeted, everything imports like normal & I see the anims/clips. So it's just a visual bug.

**Comment by CFox04** [comment]
Fixed in [db9a051](https://github.com/Skylumz/Sollumz/commit/db9a051d873931dfbcc9c70eb5634ab721b6caa2)
