### ISSUE TITLE
Readme section "Supported Formats (Import)" lacks entry for YFT

### ISSUE THREAD

**Issue by soryy708** [Skylumz/Sollumz#31]
Looks like there's a [yftimport.py](https://github.com/Skylumz/Sollumz/blob/main/yftimport.py) file which implies that this project is able to import `.yft` files, but it's not listed in the documentation in [README.md](https://github.com/Skylumz/Sollumz/blob/main/README.md). Why not?

**Comment by soryy708** [comment]
Looks like the [refactor branch](https://github.com/Skylumz/Sollumz/tree/refactor) doesn't have a `yftimport.py`. Is support being dropped? Or is it not implemented _yet_?

**Comment by Loyalists** [comment]
The repo is being refactored right now.
