### ISSUE TITLE
Issue when enabling addon

### ISSUE THREAD

**Issue by MarcusCute** [Skylumz/Sollumz#315]
![image](https://user-images.githubusercontent.com/85826899/164815735-f21b57f3-759b-4a43-a1b3-5920deb0b9fe.png)

Getting this issue when i try to enable the addon

**Comment by Hancapo** [comment]
Blender 2.93 is not compatible, use 3.1.2 instead

**Comment by ChakibChemso** [comment]
@MarcusCute consider closing this issue
