### ISSUE TITLE
root motion is playing in reverse

### ISSUE THREAD

**Issue by ChakibChemso** [Skylumz/Sollumz#319]
![image](https://user-images.githubusercontent.com/41765106/165191571-ae7d56b7-eab3-43ae-8ff8-7b52a5a2c914.png)
![image](https://user-images.githubusercontent.com/41765106/165191579-76c9426f-672f-465b-9349-43cf1b6bea88.png)

**Comment by ultrahacx** [comment]
Those 3 screenshots don't even mean anything. Please atleast provide a proper explanation and repro of the issue.

**Comment by Skylumz** [comment]
Im closing this until what ultra said is done feel free to reopen a more detailed issue
