### ISSUE TITLE
Having multiple textures in one drawable (YFT) imports invalid UV maps

### ISSUE THREAD

**Issue by zziger** [Skylumz/Sollumz#332]
In this situation multiple UV maps getting imported, one for each texture.
Example: airbus.yft

Boot drawable:
texcoord0 uv map active:
![image](https://user-images.githubusercontent.com/27638710/168448179-ce96ec91-fed5-4611-a339-81bd17a6c76f.png)
texcoord1 uv map active:
![image](https://user-images.githubusercontent.com/27638710/168448182-a90d5cfe-ada2-40d1-be59-cb4eedea84b5.png)

Bodyshell drawable:
texcoord0 uv map active:
![image](https://user-images.githubusercontent.com/27638710/168448204-938e638a-158f-49da-90ea-3b935214410c.png)
texcoord1 uv map active:
![image](https://user-images.githubusercontent.com/27638710/168448222-8618a5a5-fd0e-4593-9635-00dd8f1acf30.png)

**Comment by zziger** [comment]
It seems that the actual reason for the issue is the fact, that the texture in a shader has no assigned uv maps to it. Assigning it manually fixes the issue 
![image](https://user-images.githubusercontent.com/27638710/168469490-2f065eeb-278e-4c07-9042-e4641daca6ea.png)

**Comment by Dav-Renz** [comment]
Thanks for the fix
