### ISSUE TITLE
collision is showing perfect in codewalker, but not appear on GTA 5

### ISSUE THREAD

**Issue by PravYTplay** [Skylumz/Sollumz#339]
Hi, I have used Sollumz tool for making ydr file, I did all the process which is, i import xml in codewalker, collision is showing perfect in codewalker, but in game collision is not showing, also bound are not showing when i checked my ydr file in OIV., can anyone please suggest.

**Comment by Hancapo** [comment]
send your .ydr.xml file

**Comment by PravYTplay** [comment]
> send your .ydr.xml file

Hi please pick file from below google drive path:


https://drive.google.com/file/d/1i8wioLqf-48eEB4Npqg7R3JZ_4yELoE7/view?usp=sharing

**Comment by PravYTplay** [comment]
> send your .ydr.xml file

Hi, my problem is resolved, I was using that earlier older of codewalker, now I downloaded the latest version from discord and again imported the xml file in codewalker then the collision were visible, Thanks
