### ISSUE TITLE
I cannot export 3d models as YDR format

### ISSUE THREAD

**Issue by goldenyendo** [Skylumz/Sollumz#34]
Hi, I'm having a problem that doesn't allow me to export ANY model from blender as YDR.
When I try to export the model no selection window appears,(like shown in this image)
![image](https://user-images.githubusercontent.com/70267611/132649782-14ab8321-2e67-42d6-9269-2d80f0ab1a0a.png)
And so no object is selected, I've used blender 2.9,2.93 and I went back to try older versions like 2.8 but nothing, the bug is still there and when I try to export no selection windows appears and so it gives this error "No object in scene for Sollumz to export".
What would normally happen is this window popping up when exporting 
![image](https://user-images.githubusercontent.com/70267611/132650998-a92b0924-6721-44fb-8733-122579d3842b.png)

**Comment by Skylumz** [comment]
The first image is saying that you are importing? so thats prolly why you cant export. Also the current version has many bugs and we are working on a refactor right now you can check out the branch if you want
