### ISSUE TITLE
Lods editing 

### ISSUE THREAD

**Issue by Jibril13** [Skylumz/Sollumz#340]
When you import buildings LODS in blender it works but after exporting it with all textures in the rpf explorer , you can't  open it for some reason.

**Comment by ZiDeveloper** [comment]
Like your own or GTA buildings. Do you have some examples?

**Comment by Jibril13** [comment]
> Like your own or GTA buildings. Do you have some examples?

gta building, and most of them that I tried when I get home i will send you one of them
That I tried to edit like 10 times

**Comment by Jibril13** [comment]
sc1_13_build04_lod

**Comment by Jibril13** [comment]
> Like your own or GTA buildings. Do you have some examples?

sc1_13_build04_lod

**Comment by ZiDeveloper** [comment]
Found the issue. Its CodeWalker and not Sollumz.

Plainly exporting and importing the file without even touching it with Sollumz will break it. I don't know the reason behinde this but CodeWalker fails to export the names. I was able to get the right names from OpenIV
```
    sc1_13_build02a_lod -> sc1_13_build02a_lod
    1144192440          -> sc1_13_strip_lod
    1228852404          -> sc1_13_build04_lod
    3547816881          -> sc1_13_grd_lod
```
I've also found a way to fix this. You need to rename them in the xml or in Blender. Just make sure you rename the right one and it has to be all lower case.
```
<DrawableDictionary>
	<Item>
		<Name>sc1_13_build02a_lod</Name>
		[...]
	</Item>
	<Item>
		<Name>sc1_13_strip_lod</Name>
		[...]
	</Item>
	<Item>
		<Name>sc1_13_build04_lod</Name>
		[...]
	</Item>
	<Item>
		<Name>sc1_13_grd_lod</Name>
		[...]
	</Item>
</DrawableDictionary>
```
Then you should be able to edit this in Blender and import back to CodeWalker.

**Comment by Jibril13** [comment]
> Found the issue. Its CodeWalker and not Sollumz.
> 
> Plainly exporting and importing the file without even touching it with Sollumz will break it. I don't know the reason behinde this but CodeWalker fails to export the names. I was able to get the right names from OpenIV
> 
> ```
>     sc1_13_build02a_lod -> sc1_13_build02a_lod
>     1144192440          -> sc1_13_strip_lod
>     1228852404          -> sc1_13_build04_lod
>     3547816881          -> sc1_13_grd_lod
> ```
> 
> I've also found a way to fix this. You need to rename them in the xml or in Blender. Just make sure you rename the right one and it has to be all lower case.
> 
> ```
> <DrawableDictionary>
> 	<Item>
> 		<Name>sc1_13_build02a_lod</Name>
> 		[...]
> 	</Item>
> 	<Item>
> 		<Name>sc1_13_strip_lod</Name>
> 		[...]
> 	</Item>
> 	<Item>
> 		<Name>sc1_13_build04_lod</Name>
> 		[...]
> 	</Item>
> 	<Item>
> 		<Name>sc1_13_grd_lod</Name>
> 		[...]
> 	</Item>
> </DrawableDictionary>
> ```
> 
> Then you should be able to edit this in Blender and import back to CodeWalker.

**how can you change the name ? because i looked in the xml file use code studio  and i can't find the name that you told me ?**
    sc1_13_build02a_lod -> sc1_13_build02a_lod
    1144192440          -> sc1_13_strip_lod
    1228852404          -> sc1_13_build04_lod
    3547816881          -> sc1_13_grd_lod

**can you help me or if it's fast can you plase record when you do it that can be really helpful**

**Comment by ZiDeveloper** [comment]
I fixed the list and I'm making a video for you how to fix YDD's. I'll post it here

**Comment by ZiDeveloper** [comment]
Sorry for the audio. YouTube is still precessing, might need to wait for HD a little: https://www.youtube.com/watch?v=9pRQQTcqnOM

**Comment by Jibril13** [comment]
> Sorry for the audio. YouTube is still precessing, might need to wait for HD a little: https://www.youtube.com/watch?v=9pRQQTcqnOM

man thank you so much you don’t know how much I appreciate it I will try it as soon as I get home

**Comment by Jibril13** [comment]
thanks you so much❤️  it works for code walker 
**But now when i edit and import it back to code walker i have another error message** 

![image](https://user-images.githubusercontent.com/92039065/174186518-f58ad0e3-9a78-4011-a013-f725ce298291.png)

**Comment by ZiDeveloper** [comment]
[WIKI](https://github.com/Skylumz/Sollumz/wiki)

**Comment by Jibril13** [comment]
> WIKI

I will try but it for other ydd it works but not for lodd

**Comment by ZiDeveloper** [comment]
You need the name the textures folder the same as the YDD.

**Comment by Jibril13** [comment]
> You need the name the textures folder the same as the YDD.

Ohhh yea sorry am really dumb I thought that it was going to rename it automatically that am going to try when I get home

**Comment by Jibril13** [comment]
it works bro thanks for all your help
