### ISSUE TITLE
Click 'Auto-Create' And this message popped up

### ISSUE THREAD

**Issue by Teaa12t** [Skylumz/Sollumz#345]
![282440790_759777535458913_8719024539440739273_n](https://user-images.githubusercontent.com/107637307/174114326-d515fced-7cc8-44c1-89d2-36b24ec4ab24.png)
![284468998_423499362988981_2728754406978901993_n](https://user-images.githubusercontent.com/107637307/174114337-4bc80e20-1f81-4883-999b-e4a88fa54872.png)
![283862608_421484966513250_9012133825490074789_n](https://user-images.githubusercontent.com/107637307/174114341-2a84f80c-b5f3-4046-94bc-d46452509741.png)

I clicked 'Auto-Create' and this message popped up.
Could anyone tell me how to fix this? 

Thank you!

**Comment by ZiDeveloper** [comment]
Auto-Create can only add Sollumz objects to the YTYP. So lets say you create or import a YDR in Blender using Sollumz then you can use Auto-Create to add it to the YTYP.

It looks like your object is just a Blender Mesh.

You might want to take a look at the [Sollumz Wiki](https://github.com/Skylumz/Sollumz/wiki/Basic-Ydr-Creation-Tutorial)
and here a video I just found that might help you [Basic Emissive Logo with Blender/Sollumz](https://www.youtube.com/watch?v=5mkaCBTpxeg)

**Comment by Teaa12t** [comment]
> Auto-Create can only add Sollumz objects to the YTYP. So lets say you create or import a YDR in Blender using Sollumz then you can use Auto-Create to add it to the YTYP.
> 
> It looks like your object is just a Blender Mesh.
> 
> You might want to take a look at the [Sollumz Wiki](https://github.com/Skylumz/Sollumz/wiki/Basic-Ydr-Creation-Tutorial) and here a video I just found that might help you [Basic Emissive Logo with Blender/Sollumz](https://www.youtube.com/watch?v=5mkaCBTpxeg)

Thank you so much for your reply!  Already well solved! ♥

**Comment by siebe8000o** [comment]
I got the same issue
