### ISSUE TITLE
I've run into another problem in exporting ;w;

### ISSUE THREAD

**Issue by Teaa12t** [Skylumz/Sollumz#348]
![284471254_684699412628247_348909961143544347_n](https://user-images.githubusercontent.com/107637307/174488058-3aa33d3a-5cd0-48d4-bc93-10cc2b652738.png)

Sirs! I don't even know what I missed from the tutorial ;w;
Please help. Thanks a lot ♥

**Comment by Hancapo** [comment]
Please ask in Sollumz' help channel, that's what it's there for.
your mesh has no Sollumz materials, hence it was skipped.

**Comment by Teaa12t** [comment]
> Please ask in Sollumz' help channel, that's what it's there for. your mesh has no Sollumz materials, hence it was skipped.

Thank you so much for your kind advice. And so sorry if I put my question in the wrong place. So new here. Thanks!
