### ISSUE TITLE
Status of refactor?

### ISSUE THREAD

**Issue by soryy708** [Skylumz/Sollumz#35]
The [refactor branch](https://github.com/Skylumz/Sollumz/tree/refactor) is 9 commits ahead of `main` and the last commit was 11 days ago.
What's the refactor's status? I there an ETA for when it's done?
I'd like to contribute to this repository, but I'm blocked because the refactor is underway and there's no communication for what's the plan and expectations.
Specifically I'd like to contribute to YFT import and export, dealing with [#32](https://github.com/Skylumz/Sollumz/issues/32) and [#33](https://github.com/Skylumz/Sollumz/issues/33).

**Comment by Skylumz** [comment]
Hello if you want you can join the codewalker server to talk to me in more detail about this : https://discord.gg/BxfKHkk
