### ISSUE TITLE
Exporting spot lights angles and colors

### ISSUE THREAD

**Issue by DarkTide** [Skylumz/Sollumz#354]
The calculation used to determine inner and outer angles of the exported spot are completely wrong and have no meaning compared to what the user is setting up (blending in from full 180 deg instead of what the user is setting as the outter angle? why?)

Light colors again, they were fixed to be in the right range (0-255) but are exported in the wrong colorspace and that gives no real control to the user over the color of the lights, and i'm guessing the import doesn't translate them into linear color for blender to use the color properly (haven't tested though but i will)

**Comment by Hancapo** [comment]
You should use CW light editor for now.

**Comment by CFox04** [comment]
I'll look into this but yeah I would recommend using CW light editor. Lights in Sollumz are pretty bad right now
