### ISSUE TITLE
YBN issue on import / export

### ISSUE THREAD

**Issue by Rigonkmalk** [Skylumz/Sollumz#355]
Hi !

I used last version of sollumz (via git pull directly).
Blender version 3.2.1

After few check, I saw a mistake when I tried to import a vanilla YBN file.

File used : lr_sc1_rd_20.ybn

View from RPF Explorer :
![image](https://user-images.githubusercontent.com/12967235/179225905-eba28110-f298-4947-9767-adf2be793c89.png)

View from Blender :
![image](https://user-images.githubusercontent.com/12967235/179226186-4c332015-ba72-4bdf-bdec-fbfb105694c4.png)

Thank you for your work as well ! :)

I tried even with a vanilla YBN (v_stadium.ybn) MLO, same issue.

**Comment by Rigonkmalk** [comment]
Alright, I tried few older commits to make sure if the issue doesn't appear in older time :

Tried on [Merge pull request](https://github.com/Skylumz/Sollumz/commit/fbcb3406872f5b5e5bd319274fceec8b01cc73f6) https://github.com/Skylumz/Sollumz/pull/327 [from ultrahacx/pr-323-patch](https://github.com/Skylumz/Sollumz/commit/fbcb3406872f5b5e5bd319274fceec8b01cc73f6)
Import work fine.

Tried on [Merge pull request](https://github.com/Skylumz/Sollumz/commit/835b9aead9e02edb5c14eb31e7df7b28354519c0) https://github.com/Skylumz/Sollumz/pull/331 [from CFox04/refactor](https://github.com/Skylumz/Sollumz/commit/835b9aead9e02edb5c14eb31e7df7b28354519c0)
Import is broken now.

**Comment by CFox04** [comment]
Fixed in f3ef2cb
