### ISSUE TITLE
Blender error "No objects of type: drawable dictionary or bound composite or drawable to export."

### ISSUE THREAD

**Issue by raza178** [Skylumz/Sollumz#356]
Hi whenever I try to export xml files from Blender It gives this error. I am in great trouble. Kindly guide

**Comment by Rigonkmalk** [comment]
Can you give more informations about your issue ? 

Actually you didn't show anything, and we have no clue about your issue.

**Comment by CFox04** [comment]
Not enough info and sounds like a user error. If you have questions please ask on the discord.
