### ISSUE TITLE
Error during YTYP import (MLO)

### ISSUE THREAD

**Issue by Rigonkmalk** [Skylumz/Sollumz#358]
Version of sollumz used : Last version from GH
Version of Blender : 3.2.1

Description on the issue :

I tried to import v_int_4 from vanilla interior, and I received an error on ytyp operators.py

![image](https://user-images.githubusercontent.com/12967235/180642300-294af732-eda3-43d5-ad15-95db86d0d687.png)

This error involves an incident in the number of Rooms and Portals in the ytyp file.

v_int_4 from CW :

![image](https://user-images.githubusercontent.com/12967235/180642263-8dc6bb37-64a0-45e6-8f76-c8054d07d6b2.png)

v_int_4 from Sollumz :

![image](https://user-images.githubusercontent.com/12967235/180642286-ddc77a3d-0caf-4235-a5fb-a3553d81fd4f.png)

**Comment by CFox04** [comment]
Fixed in 6a3f828b3be11b912bf90d3fa59bc476da6210d0
