### ISSUE TITLE
Wrong rotations in MLO entities

### ISSUE THREAD

**Issue by Hancapo** [Skylumz/Sollumz#359]
Upon exporting a MLO with rotated entities, the rotations have shown to be wrong both in CW and in-game, the Z axis of the quaternion needs to be inverted.

Blender: 
![image](https://user-images.githubusercontent.com/20731612/180659909-6a873707-a8f7-4747-8bcc-00d2f4535df3.png)

CW: **Ignore the entities' position**
![image](https://user-images.githubusercontent.com/20731612/180660001-1f593c09-97e8-410a-8e9a-ae9dea655627.png)

**Comment by CFox04** [comment]
Fixed in b8f6b9158cfcca561a555387a25df7e3487da6ea
