### ISSUE TITLE
Sollumz Not Functional 

### ISSUE THREAD

**Issue by forbesee1** [Skylumz/Sollumz#36]
Do we have a update on the refractor? In its current state this sadly doesn't work - do we have a previous version that works with blender?

**Comment by soryy708** [comment]
Duplicate of https://github.com/Skylumz/Sollumz/issues/35 ?

**Comment by Skylumz** [comment]
"Doesn't work" does not help me I need useful information what doesn't work. You can join the codewalker server to stay updated! https://discord.gg/BxfKHkk
