### ISSUE TITLE
[YDR] Issue on export with TintColor in Color Attributes

### ISSUE THREAD

**Issue by Rigonkmalk** [Skylumz/Sollumz#360]
Version of sollumz used : Last version from GH
Version of Blender : 3.2.1

File used for testing purpose : hw1_12_ground.ydr

Description on the issue :

When you tried to export an ydr with

- Colour0
- TintColor
- Colour1

TintColor attributes take place of Colour1 in `VertexBuffer`.

## hw1_12_ground.ydr with TintColor :

![image](https://user-images.githubusercontent.com/12967235/180750521-ffde1b9f-229f-4e3c-b184-e84b5774b6f9.png)

CW view with Vertex Colour 2 selected :

![image](https://user-images.githubusercontent.com/12967235/180750616-9dd98b54-0af4-429f-a5b9-92037b7ada60.png)

## hw1_12_ground.ydr without TintColor :

![image](https://user-images.githubusercontent.com/12967235/180750748-38ebe084-1f9f-499a-8587-572404195107.png)

## Deep view from XML

![image](https://user-images.githubusercontent.com/12967235/180750351-5253b19e-88ed-4d73-97c1-ef1f6994bd19.png)

I think TintColor take place of Colour1 and delete Colour1 in the Color Attributes on export.

**Comment by Rigonkmalk** [comment]
After searching on ydrexport.py script :

```
    if vcs > 0:
        for vc in mesh.vertex_colors:
            if vc.name != "TintColor":
                sematic.append(ydrxml.VertexSemantic.color)
```

There's the only place you find TintColor attribute on export.

I don't, sadly, enough skill for helping you...

**Comment by LABNetwork1** [comment]
to solve this you need to delete TintColor I already tested it and it worked

**Comment by Rigonkmalk** [comment]
> to solve this you need to delete TintColor I already tested it and it worked

As you can see on my main description, I already tested without TintColor Attributes.

**Comment by Rigonkmalk** [comment]
Thanks to Vicho founding how to workaround the issue. Closing this one.

> disable Join Geometry upon importing
