### ISSUE TITLE
Pattern of fogcolor

### ISSUE THREAD

**Issue by SaifAlDilaimi** [Skylumz/Sollumz#364]
Hello, is there a reference what pattern the fog color property of the water_poolenv shader uses?
![3813D43B-75AA-4BE8-9739-840348C7F264](https://user-images.githubusercontent.com/3785570/182083381-fc02d300-1de0-4999-9a7a-5c103d80d446.png)
I have tried several combinations of X,Y,Z,W and I can't find a pattern that results in a specific color..

**Comment by Hancapo** [comment]
This is not an issue, do the respective questions on Sollumz server, thanks.

**Comment by SaifAlDilaimi** [comment]
@Hancapo I already did but to be honest no one could help me. Someone said that’s RGBA or ARGB but it didn’t worked.

**Comment by SaifAlDilaimi** [comment]
So after several test it seems that Y coresponds to green and Z to blue but X does not result in red. Is here someone that has the same issue?

**Comment by CFox04** [comment]
Please keep the issues specific to Sollumz; this isn't a place for general questions. If you couldn't get any help on the Sollumz discord then try another GTA modding-related discord.
