### ISSUE TITLE
Not exporting.

### ISSUE THREAD

**Issue by therealJiko** [Skylumz/Sollumz#367]
![WM-Screenshots-20220802223636](https://user-images.githubusercontent.com/104643122/182477803-bf522c13-aaa0-4f1b-89df-052aa31bff0b.png)
[Sollumz-main (1).zip](https://github.com/Skylumz/Sollumz/files/9245832/Sollumz-main.1.zip)

**Comment by Hancapo** [comment]
You can't export a drawable without materials, please use the Sollumz Discord server to get help.

**Comment by dotpeak** [comment]
Seriously? you some how went about screenshotting the error and putting it on GitHub as a bug instead of reading it and noticing what it says or even having a read at the Sollumz YDR creating wiki page..
