### ISSUE TITLE
Error when importing a YBN file

### ISSUE THREAD

**Issue by Walien-dev** [Skylumz/Sollumz#370]
Hello !
I have encountered this error while importing a ybn.xml file.

I want to know how to fix this error. I am exporting the xml from CodeWalker RPF explorer and I have the latest version of Sollumz.

I can import ydr.xml files but not ybn.

Error:
![error sollumz](https://user-images.githubusercontent.com/43910644/182911501-3df862fb-8ecb-4f92-846e-340be998e408.png)
:

I'm waiting for your answer,
thx,
Walien

**Comment by ooknumber13** [comment]
I just tried importing the same YBN file, worked fine for me, not sure why you are getting an error

**Comment by CFox04** [comment]
You definitely are not using the latest version. Make sure you download from this Github.
