### ISSUE TITLE
Error when import ycd 

### ISSUE THREAD

**Issue by jimz-dev** [Skylumz/Sollumz#372]
Some animation can't import 
example missarmenian2.ycd and missfinale_a_ig_2

![image](https://user-images.githubusercontent.com/56931445/183224680-eb5515cc-64e2-4f89-8bdb-d898d1ca148f.png)

**Comment by CFox04** [comment]
Can you try re-exporting the XML from Codewalker? Make sure you're using the latest version of Codewalker too.

**Comment by jimz-dev** [comment]
Yes using the latest version of Codewalker  (CodeWalker30_dev44)

**Comment by alexguirre** [comment]
This is a bug in CodeWalker's XML export.

Submitted a PR: https://github.com/dexyfex/CodeWalker/pull/216
