### ISSUE TITLE
Vertex Painter is not accurate

### ISSUE THREAD

**Issue by Kc2693** [Skylumz/Sollumz#374]
Vertex Painter does not actually paint the color that is input. 
![image](https://user-images.githubusercontent.com/28677397/183540137-5d4adf37-3d96-49cc-b7c5-d183441389b6.png)
this is #FF8000 (the orange everyone uses for clothing) with Sollumz Vertex Painter

![image](https://user-images.githubusercontent.com/28677397/183540210-c1fa3512-12cf-4bac-96bd-5d947986953a.png)
this is #FF8000 when using Blender Vertex Paint.

In RGB terms, it's painting (255, 55, 2) instead of (255,128, 0). If that helps. 

Also, the RGB selection in Vertex Painter is way off. It goes from -10000.000 to 10000.000 for RGBA when it should go from 0.000 to 1.000

**Comment by CFox04** [comment]
Fixed in 40c2483914ac11115bf24127b2111eb8dc07a6b8
