### ISSUE TITLE
Is there an active trojan when downloading the zip?

### ISSUE THREAD

**Issue by darektion** [Skylumz/Sollumz#377]
![image](https://user-images.githubusercontent.com/51394806/184483275-4c48ea97-18f3-4042-8f77-859647c962aa.png)
Tried to download the repo zip file twice, with the threat warning appearing in both occasions.

Seeking your kind clarification and verification on this matter.

**Comment by dotpeak** [comment]
Many users have had this pop up in Discord and some people had to update Windows Defender for it to not show up as a threat; If you can't update Windows Defender then disable it whilst you install Sollumz or add it to a bypass list on Windows Defender. Sollumz is completely safe and causes no harm to your system. 

Here is a [VirusTotal scan] (https://www.virustotal.com/gui/file/96b46707b3ba0e937d0ebc0f9392a07dbf51a63c17c931233baebd99cffc9357) nothing was flagged for any type of malware or harmful content.

**Comment by darektion** [comment]
Many thanks for your clarifications. I will go look up on how to add it into the bypass list on Windows Defender.

**Comment by krzysiula3000** [comment]
and install better antivirus than defender, it sucks ass bad, any antivirus out there would be 10 times better

**Comment by dotpeak** [comment]
> and install better antivirus than defender, it sucks ass bad, any antivirus out there would be 10 times better

or just don't download random shit that you don't trust; its simple. Only good anti virus is your brain
