### ISSUE TITLE
GTA V Files with Bones (YDR, YFT) Skeleton slower than Mesh

### ISSUE THREAD

**Issue by PeekerJ** [Skylumz/Sollumz#382]
When you import a **YDR, YFT** or any **GTA Rage file with Bones**, When you move the Mesh _(Object)_ in the Pose Mode the skeleton moves slower than the Mesh and breaks and makes animating very bad. Almost impossible.

**Comment by ultrahacx** [comment]
"Moves slower" thing hasen't happened to me ever. It looks like an issue with your Blender or your PC itself. Can you screenrecord this issue and post it?

**Comment by PeekerJ** [comment]
Yeah, sure. BTW I had 2 PCs and it did the same thing

**Comment by CFox04** [comment]
Closing this as it needs more info and has been inactive.
