### ISSUE TITLE
Sollumz not saving position changes of a ped model's mesh and skeleton 

### ISSUE THREAD

**Issue by MaddDoggArcheType** [Skylumz/Sollumz#386]
I'm trying to move a head model to correctly attach it to a different body, but Sollumz is not saving the position changes I make. The game kept showing the head still dealigned and upon re-importing the edited model in blender I noticed the changes were just not there anymore, head position's back in the vanilla position. Tried to do the whole process from scratch at least 10 times now, the problem persists and I fail to see what I'm doing wrong.

**Comment by CFox04** [comment]
Send your blend file
