### ISSUE TITLE
Center Composite not showing in sollumz collision tools

### ISSUE THREAD

**Issue by b1uedr4gon** [Skylumz/Sollumz#389]
As the title says after importing my model and collisions and then importing the ymap i go to collision tools and there is no option for "center composite", i only see "split collision" and "divide by 2"

![image](https://user-images.githubusercontent.com/17405870/185741955-e7552d72-30f2-4ae4-a382-2173a75b6133.png)

**Comment by dotpeak** [comment]
the button was removed, as far as I know you can skip this step. Ask in the [Discord](https://discord.gg/SmGNEFZR) if you need any more help.

**Comment by b1uedr4gon** [comment]
> the button was removed, as far as I know you can skip this step. Ask in the [Discord](https://discord.gg/SmGNEFZR) if you need any more help.

ahh ok , i ended up just setting all the location axis for it to 0,0,0 , figured that should work too

**Comment by CFox04** [comment]
Yeah, it's been removed. I just updated the tutorial.
