### ISSUE TITLE
Bug with material collision flags

### ISSUE THREAD

**Issue by d1n3301** [Skylumz/Sollumz#391]
**Issue**: After subsequent collision exports, the material flags in the file code are not removed, although in the blender the flags are unchecked.

**Software:**

- Blender 3.2.2
- Sollumz GitHub version Hancapo:convert-all-toselected
- CodeWalker v44

I check the boxes and export the model with collision material, everything is fine, but after I uncheck the boxes and export again, they remain in the code

![blender_uvUAq8zrqD](https://user-images.githubusercontent.com/94755823/185802943-d2d69bd6-ad26-4a6e-8e0b-a836f621bfe8.png)
![blender_yRoeWpmtIo](https://user-images.githubusercontent.com/94755823/185803170-a8e13900-4d69-4071-85a7-77fed3587de9.png)

**Comment by ooknumber13** [comment]
try downgrading to blender 3.2 or below

**Comment by d1n3301** [comment]
on 3.1.2 There is also this problem

**Comment by CFox04** [comment]
Fixed in 4c065636bb89d9400ccd8490874da823d28eb46b
