### ISSUE TITLE
MLO Update portal values they same way as the room boundaries feature

### ISSUE THREAD

**Issue by MrGTAmodsgerman** [Skylumz/Sollumz#393]
**Feature request:**
If i want to update a portal to a new position, the "Create Portal From Verts" button only creates a new Portal. So it doesn't update the existing one with all the naming and flags already set.

Room boundaries already can be updated by vertices selection trough one button. Why not the same for portals?

![675n](https://user-images.githubusercontent.com/19436774/185813487-1b7954a5-5a4d-4e9d-a261-3d1edd179a99.png)
Don't mind my ugly MS Paint work :laughing:

**Comment by Hancapo** [comment]
implemented in #405

**Comment by MrGTAmodsgerman** [comment]
> implemented in #405

Thanks a lot!
