### ISSUE TITLE
Powerlines / wiresets distorting on export

### ISSUE THREAD

**Issue by ooknumber13** [Skylumz/Sollumz#396]
all i did was import the model and export it without making changes, and the powerline becomes distorted
![after](https://user-images.githubusercontent.com/47336113/187052147-c77bd09f-4c35-404e-8e26-2b3f9be1f232.png)
![before](https://user-images.githubusercontent.com/47336113/187052148-4dd49a60-ac8f-4ff3-a273-b07dc20b4aba.png)

**Comment by krzysiula3000** [comment]
WTF LMAOOOOOOOO

**Comment by CFox04** [comment]
Fixed in #510
