### ISSUE TITLE
issue when importing: material shader incorrectly set as _tnt shaders

### ISSUE THREAD

**Issue by ooknumber13** [Skylumz/Sollumz#401]
ive noticed that sometimes when importing a model some of the materials are set to _tnt shaders. https://i.imgur.com/7fhsyZ8.png
i then have to manually set it to the non _tnt version. https://i.imgur.com/pvqMZdM.jpeg

**Comment by ooknumber13** [comment]
forgot to mention the model name; sc1_10_ground01

**Comment by Hancapo** [comment]
https://user-images.githubusercontent.com/20731612/188288079-80a714fc-3586-4cb6-95cb-46fb670a3b4a.mp4

There's nothing wrong with the shader set, that part of the drawable you mention corresponds to an actual `normal_spec_tnt` shader

**Comment by ooknumber13** [comment]
thats weird, why is it messed up in blender?

**Comment by Hancapo** [comment]
tint shaders has been messed up since a certain update
