### ISSUE TITLE
The pivot shifts when exporting with bones

### ISSUE THREAD

**Issue by d1n3301** [Skylumz/Sollumz#402]
**Issue - **For some reason the pivot point shifts when exporting

**
- Blender 3.1.2
- Sollumz GitHub version 04.09.22
- CodeWalker v44**

I needed to edit the door with the bones a bit, but when I export the pivot shifts at the door model
**Model name:** v_corp_hicksdoor
https://youtu.be/S6jkmC6iB0U
https://imgur.com/a/99jGwog
https://streamable.com/pi4g3d

**Comment by CFox04** [comment]
Fixed in 1f9f174f8808830ac404027a0b6b0fed831d20c8
