### ISSUE TITLE
Problem with the export and subsequent import in the rpf explorer

### ISSUE THREAD

**Issue by d1n3301** [Skylumz/Sollumz#403]
After exporting from blender and importing into CodeWalker RPF explorer, some of the objects are missing

- Blender 3.1.2
- Sollumz GitHub version 06.09.22
- CodeWalker v44

Model name: **sc1_11_slod1_children**
GTA standard file : https://i.imgur.com/S1oiq9m.png
After exporting and importing : https://imgur.com/a/Is6Qm0k

**Comment by d1n3301** [comment]
Not sure but it could be a CodeWalker problem

**Comment by Hancapo** [comment]
you need a nametable, is not related to Sollumz
