### ISSUE TITLE
Prevent export for YDD that has UNK bones

### ISSUE THREAD

**Issue by Kc2693** [Skylumz/Sollumz#408]
(feature request)
Hello it's your resident custom clothing assistant here. The number 1 problem I see when trying to help people is that they import clothing incorrectly & thus do not have proper vertex groups/bones and face a multitude of problems when they export.

![unknown](https://user-images.githubusercontent.com/28677397/188896538-c7c1a0d5-92ef-487c-8ea7-6c2fbe84caad.png)

The problem is, sometimes the issue sounds obscure and I (or anyone else trying to help) waste time asking other questions trying to figure out the problem when the entire time it's just bc they don't have proper vertex groups/weights. Of course helpers can start asking to see vertex groups first, but it would be even better if sollumz would give an error, or at least a warning, when people go to export with improper vertex groups so that the problem is more obvious to both the modder & people trying to help.

**Comment by Hancapo** [comment]
I will take a look

**Comment by Rigonkmalk** [comment]
As I tried in clothing,

When you import your clothes without importing bones (like mp_m_freemode_01.yft) you will find this kind of error and you can't export it afterward.

Following the wiki : 

[https://github.com/Skylumz/Sollumz/wiki/Basic-Clothes-Editing-Tutorial#3-importing-files](https://github.com/Skylumz/Sollumz/wiki/Basic-Clothes-Editing-Tutorial#3-importing-files)

![image](https://user-images.githubusercontent.com/12967235/199939427-ee1c5c83-0dbf-49ad-b06c-bd5b0ac13522.png)

**Comment by alexguirre** [comment]
#719
