### ISSUE TITLE
YCD facial animation import issue

### ISSUE THREAD

**Issue by Trucker7** [Skylumz/Sollumz#410]
Hello, I am a common user, I am presenting problems for the export of YCD facial animation. The other animations are exported to me fine, but these are actually exported:
![1](https://user-images.githubusercontent.com/112605260/189757195-f4bcd30a-9ec7-4a06-a994-4e667723840d.JPG)
![2](https://user-images.githubusercontent.com/112605260/189757247-4e97cb9e-77cf-41d2-9a0a-de83f6931767.JPG)

but when I go to animate the armor, there is no hint of facial animation.

![3](https://user-images.githubusercontent.com/112605260/189757294-2e25ffd3-56fc-451a-948d-bcacf05292eb.JPG)

All the names of the armor are fine, but I don't know if it's for compatibility, if there is a solution or if someone wants to contribute a bit of their knowledge to solve it, I, like all of us, will be grateful.

**Comment by CFox04** [comment]
Facial animations aren't supported at the moment
