### ISSUE TITLE
UV anim YCD setting anim constant is glitching out 

### ISSUE THREAD

**Issue by ScientiaeJuridicae** [Skylumz/Sollumz#412]
The original animation in game looks like this: https://imgur.com/l0aq5wm
I tried doing it again using Sollumz but it looks like this: https://imgur.com/b5otpO1
I tried doing everything and finding fixes, maybe checking where I went wrong but I am not sure, all out of options here. If this is an issue with Sollumz UV anim tool, I hope a fix can be found and implemented for it quickly. Thanks.

**Comment by alexguirre** [comment]
The action keyframes in Blender should be set every 30 frames if constant interpolation is needed.

If it is still an issue provide the model and ycd.
