### ISSUE TITLE
Not have Archetype Definition in Sollumz Tools Menu

### ISSUE THREAD

**Issue by LukNasc** [Skylumz/Sollumz#413]
![image](https://user-images.githubusercontent.com/26725196/192075356-993a1597-b52a-40f4-add0-b89ac866a6ce.png)
 Someone can help me?

**Comment by Hancapo** [comment]
Update Sollumz

**Comment by LukNasc** [comment]
> Update Sollumz

I'm downloading the latest version available on the site [5Mods](https://pt.gta5-mods.com/tools/sollumz-blender-plugin), but not work

**Comment by ooknumber13** [comment]
download from github, gta5mods version is VERY outdated

**Comment by LukNasc** [comment]
can you post the link here? i'm not finding

**Comment by LukNasc** [comment]
im so sorry, i understand now
thanks everybody
