### ISSUE TITLE
SET ALL TEXTURES TO EMBEDDED is slow and box marking bug

### ISSUE THREAD

**Issue by dunham94** [Skylumz/Sollumz#421]
Guys, I think the SET ALL TEXTURES TO EMBEDDED button has a problem, I click on the object first, then I click SET ALL TEXTURES TO EMBEDDED, when I go to check, the square is unmarked, at least when I pass the mouse over it, it marks ... I think I need to check the programming because it has some delay as far as I can tell

**Comment by ooknumber13** [comment]
i personally have not experienced what you are describing, also you need to select each material then click the button, it doesnt set all materials to embedded.

**Comment by CFox04** [comment]
This is because the UI doesn't update until you hover your mouse back over the panel. I don't believe there is a way to fix this atm.
