### ISSUE TITLE
Yft wheel Collisions & wheel meshes incorrectly placed

### ISSUE THREAD

**Issue by CFox04** [Skylumz/Sollumz#423]
from 13Stewartc:

![image](https://user-images.githubusercontent.com/46362482/195462619-43241f5e-7692-48ac-bf3c-6b1170e4439d.png)
I did some checking and it appears this is an issue with the way armature rotation is handled. I'll try my best to explain this, but it seems the wheels are being placed at the wrong "end" of the armature piece that represents the wheels my screenshots below will hopefully make the issue more obvious (explaining it is difficult).

![image](https://user-images.githubusercontent.com/46362482/195462684-0c098d51-a850-43e8-9b61-304f6e46ac20.png)
perspective view of the armature and the wheel (wheel moved on X axis so armature is visible)

![image](https://user-images.githubusercontent.com/46362482/195462707-2223dbb1-33ed-4bf4-8554-a6003f9669a7.png)
left view of wheel with armature highlighted.

![image](https://user-images.githubusercontent.com/46362482/195462725-d50c7de5-8bfe-460a-bda6-96f6b4a3d752.png)
left view of wheel with wheel mesh position manually set to the correct origin point. (armature highlighted)

**Comment by Hancapo** [comment]
I think there's a similar issue with weapons

**Comment by TheRaf3D1** [comment]
> I think there's a similar issue with weapons

yeah, i have this too
