### ISSUE TITLE
Light - Shadow Blur missing in Sollumz Light objects

### ISSUE THREAD

**Issue by Denis-3D** [Skylumz/Sollumz#428]
Light - Shadow Blur missing in Sollumz Light objects

![image](https://user-images.githubusercontent.com/7430830/197813312-2e594efc-8a65-44ab-be24-790735c1a6bd.png)
![image](https://user-images.githubusercontent.com/7430830/197813785-9b3bafc0-6935-49f8-bda6-4aebc7eae020.png)

**Comment by ooknumber13** [comment]
Should be implemented in my PR

**Comment by CFox04** [comment]
Implemented in f94dc97e51d15fa6cdc6bc2e35b7ffa2a3f416d4
