### ISSUE TITLE
yft.xml import ERROR

### ISSUE THREAD

**Issue by votavl** [Skylumz/Sollumz#431]
Everytime when i try to import yft.xml file I get this error.*

It create pack but nothingis inside
![image](https://user-images.githubusercontent.com/108093941/198588762-9dc04150-50c6-4f23-b695-5ba06ae6398a.png)

Thanks for helping me!

*:
````
Error importing: C:\Users\Vojta\Downloads\hzs_msk_scania_cas_20\firetruk.yft.xml 
 Traceback (most recent call last):
  File "C:\Users\Vojta\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Sollumz-main\sollumz_operators.py", line 71, in import_file
    import_yft(filepath, self.import_settings)
  File "C:\Users\Vojta\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Sollumz-main\yft\yftimport.py", line 274, in import_yft
    fragment_to_obj(yft_xml, filepath, import_settings)
  File "C:\Users\Vojta\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Sollumz-main\yft\yftimport.py", line 216, in fragment_to_obj
    materials = shadergroup_to_materials(
  File "C:\Users\Vojta\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Sollumz-main\ydr\ydrimport.py", line 21, in shadergroup_to_materials
    material = create_shader(shader.name, shader.filename)
  File "C:\Users\Vojta\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Sollumz-main\ydr\shader_materials.py", line 718, in create_shader
    raise AttributeError(f"Shader '{name}' does not exist!")
AttributeError: Shader 'hash_2A92AEE4' does not exist!

**Comment by ooknumber13** [comment]
You are most likely on an outdated version of sollumz, i can import firetruk.yft just fine

**Comment by votavl** [comment]
> You are most likely on an outdated version of sollumz, i can import firetruk.yft just fine

I installed new version of blender 3.3. And I installed sollumz from github so its newest version idk where is problem, weird.

**Comment by DonBondino** [comment]
Hi all! I had the same problem! I found a solution! The problem is in the XML file itself! I thought that only GTA5.exe would be enough for work, and in this state of affairs, it is wrong to get the xml model file! In order to eliminate this, I had to install GTA5 completely and only then pull out the xml model, and after that everything loads perfectly into the blender! If you have a similar problem then here is the solution! **_The problem is in the xml file itself!_**

**Comment by CFox04** [comment]
Yes, it is a problem with your file, I can import it just fine. The shader name shouldn't be a hash, not sure how that happened. Try re-exporting from Codewalker. If that doesn't work then maybe update Codewalker?

**Comment by votavl** [comment]
> Hi all! I had the same problem! I found a solution! The problem is in the XML file itself! I thought that only GTA5.exe would be enough for work, and in this state of affairs, it is wrong to get the xml model file! In order to eliminate this, I had to install GTA5 completely and only then pull out the xml model, and after that everything loads perfectly into the blender! If you have a similar problem then here is the solution! **_The problem is in the xml file itself!_**

Thanks you that works
