### ISSUE TITLE
Cant import object with "EMISSIVE" texture usage flag

### ISSUE THREAD

**Issue by martin951** [Skylumz/Sollumz#434]
Importing an .ydr object into blender, which has [Usage]EMISSIVE[/Usage] in its texture properties, will fail.

**Comment by cpmodding** [comment]
I'm sure you have a model which can crash the sollumz. Is it a vanilla or custom model?

**Comment by CFox04** [comment]
Can you please send the file, or a file reproducing the issue?

**Comment by martin951** [comment]
[model.zip](https://github.com/Skylumz/Sollumz/files/9937209/model.zip)

There you go

**Comment by CFox04** [comment]
Fixed in #517
