### ISSUE TITLE
Add a button for embedding all textures in ALL materials 

### ISSUE THREAD

**Issue by swapfr** [Skylumz/Sollumz#439]

**Comment by Hancapo** [comment]
Added in [SollumzX](https://github.com/Hancapo/SollumzX-Reloaded/commit/55e3c80ad4a051eaf79fbe2420852a191370da3b)

**Comment by swapfr** [comment]
> Added in [SollumzX](https://github.com/Hancapo/SollumzX-Reloaded/commit/55e3c80ad4a051eaf79fbe2420852a191370da3b)

would it be in the main sollumz?

**Comment by swapfr** [comment]
.
