### ISSUE TITLE
Wrong mesh export

### ISSUE THREAD

**Issue by swapfr** [Skylumz/Sollumz#443]
https://drive.google.com/file/d/1ZX6g2i02rGM--_Zls0ebzrAsWAC-iZSj/view?usp=sharing  <- blend file

![image](https://user-images.githubusercontent.com/97851724/200709923-3001283f-b431-456d-9300-050686f4e7da.png)
![image](https://user-images.githubusercontent.com/97851724/200710002-70670cc9-105f-43d7-a4af-fdf4490bd9a5.png)

**Comment by cpmodding** [comment]
Your mesh is too detailed, split it into smaller parts.

**Comment by swapfr** [comment]
other meshes it exported fine, 

![image](https://user-images.githubusercontent.com/97851724/200809843-b4de2d80-079b-424f-9889-3e407a52fd0f.png)

and it has more weight comparing with other ydrs with almost the same poly count

![image](https://user-images.githubusercontent.com/97851724/200810205-0e996152-f946-4749-b0c8-4d7d1b0d72a0.png)

**so it's definitely the sollumz bug**

`
also, when it is in xml it has much more weight then others `

![image](https://user-images.githubusercontent.com/97851724/200810932-f823653c-f4e1-4d92-be50-d3775b3e17e8.png)

**Comment by swapfr** [comment]
I separated the mesh in half, but it still exports incorrectly

![image](https://user-images.githubusercontent.com/97851724/200815154-ab06c352-ad8e-4ac3-94e8-0c91e2793347.png)

![image](https://user-images.githubusercontent.com/97851724/200815204-4e7bbe34-3445-4abe-a067-5171c5432e30.png)

**Comment by ooknumber13** [comment]
can you send me the xmls in discord just @ me

**Comment by CFox04** [comment]
This happens when the mesh is too high poly. Try splitting it up even more and if that doesn't work make an issue with the blend file attached.

**Comment by coltfox** [comment]
No longer an issue on yft branch (will be merged soon)
