### ISSUE TITLE
Implement entitySets

### ISSUE THREAD

**Issue by Rigonkmalk** [Skylumz/Sollumz#445]

**Comment by KilluaZoldyck0099** [comment]
it's really easy even doing it by hand but it's time-consuming. it's the same concept as the entities panel but for every object, you have to define in which room is the prop. Only 2 lines change and that's it
`<entitySets itemType="CMloEntitySet">
    <Item>
     <name>hash_503B3FA1</name> 
     <locations>2 2 0 1 2</locations> 
     <entities>
      <Item type="CEntityDef"> 
       <archetypeName>PROP NAME</archetypeName>
       <flags value="FLAG" />
       <guid value="0" />
       <position x="10.5356417" y="2.824246" z="-13.8411026" />
       <rotation x="-0.326505631" y="-0.3265056" z="-0.6272114" w="-0.6272114" />
       <scaleXY value="1" />
       <scaleZ value="1" />
       <parentIndex value="-1" />
       <lodDist value="200" />
       <childLodDist value="0" />
       <lodLevel>LODTYPES_DEPTH_ORPHANHD</lodLevel>
       <numChildren value="0" />
       <priorityLevel>PRI_REQUIRED</priorityLevel>
       <extensions />
       <ambientOcclusionMultiplier value="255" />
       <artificialAmbientOcclusion value="255" />
       <tintValue value="0" />
      </Item>
     </entitySets> `
     
     Hope it's added as soon as possible

**Comment by coltfox** [comment]
Implemented
