### ISSUE TITLE
add the .ynd.xml file support for the veh paths

### ISSUE THREAD

**Issue by swapfr** [Skylumz/Sollumz#455]

**Comment by ooknumber13** [comment]
issue with ynd files is they are very tricky to edit, and if you dont know exactly what you are doing, you WILL fuck stuff up. and ynds are really annoying to add / remove nodes as well.

**Comment by swapfr** [comment]
So there won't be any ynd support for sollumz?

**Comment by CFox04** [comment]
It is not planned at the moment.
