### ISSUE TITLE
Root motion rotation not exporting properly

### ISSUE THREAD

**Issue by cmg-divined** [Skylumz/Sollumz#456]
Did several experiments trying to export root rotation (track 6 for boneid 0, it includes only WXYZ rotation for the SKEL_ROOT bone) and it just won't export. Unsure what the issue is.. I tried several things, including leaving rotation in base, in root position etc and nothing worked. Root rotation refuses to export which is vital for moving animations.

**Comment by cmg-divined** [comment]
After talking with rans and Ultrahackx and trying a version with root rotation enabled, I'd say that for the most part it works. Only thing I noticed is that it slightly offsets Z up and to the left. Ranstar told me that it might have something to do with MRF and constraints, worth checking out.

**Comment by alexguirre** [comment]
This shouldn't be an issue anymore on the animation support rework branch (#709).
