### ISSUE TITLE
Auto-calculate room bounds based on attached entities

### ISSUE THREAD

**Issue by CFox04** [Skylumz/Sollumz#467]

**Comment by Hancapo** [comment]
Not a good idea, it can be dangerous for some cases.

**Comment by CFox04** [comment]
still looking into this. If this is not the right thing to do then I'm not sure how to solve the room bounds issue with imported ytyps

**Comment by dolutattoo** [comment]
Calculate room bounds from selection in edit mode is just the best thing for blender imo.
