### ISSUE TITLE
misplaced collision mesh on import

### ISSUE THREAD

**Issue by Adryamlo** [Skylumz/Sollumz#468]
When i import car model with yft.xml, the collision mesh are all placed in the center of the model. I don't know if i do something wrong.
![proof](https://user-images.githubusercontent.com/118862901/203447752-c7937948-bf44-4518-a5fb-5ae661795de6.PNG)

**Comment by ooknumber13** [comment]
What car model is this? is it vanilla?

**Comment by Adryamlo** [comment]
Yes it's vanilla model sheriff2, but it's the same for other model.

**Comment by Adryamlo** [comment]
The problem came from a too old version of CodeWalker.
