### ISSUE TITLE
Implement : Import ydr as asset in asset browser

### ISSUE THREAD

**Issue by Yam-Ka** [Skylumz/Sollumz#469]
Following Ook's tutorial (https://www.youtube.com/watch?v=htkzvdufXp4), it would be nice to have the possibility to import ydr directly as an asset in the asset browser. This could be something like that :
Select drawable.#dr > unparent > delete original hierarchy > remove .#dr extension in drawable.#dr > mark as asset 
Thank you.

**Comment by oythara** [comment]
I made a script that works for this purpose (thx chat GPT, i don't know a thing about scripting), still don't know how to mark all objects as assets, but if it can help.

import bpy

for obj in bpy.context.scene.objects:
     if obj.name.endswith(".#dr"):
      obj.parent = None

for obj in bpy.context.scene.objects:
   if not obj.name.endswith(".#dr"):
     bpy.data.objects.remove(obj)
        
for obj in bpy.context.scene.objects:
    if obj.name.endswith(".#dr"):
        obj.name = obj.name[:-4]

**Comment by Yam-Ka** [comment]
Nevermind, i made an addon for that ;)

https://github.com/Yam-Ka/Eazy_Azzets
