### ISSUE TITLE
Auto Embed Collision to Drawable

### ISSUE THREAD

**Issue by Molicheu** [Skylumz/Sollumz#470]
When there is a collision and a drawable that is named the same inside of the scene have the option to auto-embed the collision into the drawable with multiple file support

**Comment by Hancapo** [comment]
Could you elaborate further?

**Comment by dolutattoo** [comment]
@Molicheu Why would you want to do that? Separated composite are just static collisions.
Supporting this will just confuse beginners imo.
If you want to embed stuff, just put the bound in your model, thats a 3sec job...

**Comment by Molicheu** [comment]
> 

Because I have hundreds of static collisions that needs to be bound to hundreds of models

**Comment by coltfox** [comment]
^
