### ISSUE TITLE
Creating new tint shader doesnt create required Colour Attribute

### ISSUE THREAD

**Issue by ook3D** [Skylumz/Sollumz#471]
![image](https://user-images.githubusercontent.com/47336113/204150712-c57bf234-5de8-4279-b372-40f329806931.png)
here is when you create a new tint shader

![image](https://user-images.githubusercontent.com/47336113/204150753-6cd155a9-9867-414d-b7ab-873090e0d093.png)
here is a tint shader from a vanilla model when imported

**Comment by Hancapo** [comment]
it also doesn't create the needed geometry nodes for previewing it inside Blender

**Comment by coltfox** [comment]
Fixed on yft branch (will be merged soon)
