### ISSUE TITLE
Wrong vertex painted color

### ISSUE THREAD

**Issue by Minibull3** [Skylumz/Sollumz#475]
Hello,

There is an issue with the Sollumz vertex paint fonction.
When you try to use some darker colors the color with sollumz is not the good one.
If you use a full pink or a full green you don't have any issue.

Screenshot : 

![image](https://user-images.githubusercontent.com/119362041/204386892-933d7b23-366f-48d3-af9b-94e8930a703d.png)

Here a quick video : https://streamable.com/gpm7c3

if you need more details, feel free to pm me on discord.
Thanks for your help 👍

**Comment by CFox04** [comment]
Fixed in #477
