### ISSUE TITLE
add an option to edit one specific parameter in all materials with the same shader

### ISSUE THREAD

**Issue by swapfr** [Skylumz/Sollumz#487]
For example, this can be useful if some model has many default materials and you want to change the wetness multiplier in each of them

**Comment by Hancapo** [comment]
Is useful but at the same time way too specific, I can't think about a way to implement it and at the same time be a coherent option.

**Comment by swapfr** [comment]
> 

I hope you find a way to do this

**Comment by CFox04** [comment]
I agree it is too specific and I don't see it being used a lot. Maybe better of being a separate plugin or script.
