### ISSUE TITLE
Add defaults for yft properties

### ISSUE THREAD

**Issue by CFox04** [Skylumz/Sollumz#491]
some common properties (thanks ook!): 
Unknown_100h: 0
Unknown_108h: 0
Unknown_10h: 0
Unknown_128h: 0
Unknown_18h: 0
Unknown_50h: 0
Unknown_70h: 0
Unknown_78h: 0
Unknown_80h: 0
Unknown_88h: 0
Unknown_90h: 0
Unknown_98h: 0
Unknown_A0h: 0
Unknown_B0h: 0
Unknown_B4h: 0
Unknown_B8h: 0
Unknown_BCh: 0
Unknown_C0h: 65280
Unknown_C4h: 1
Unknown_C8h: -1
Unknown_CCh: 0
Unknown_D8h: 0
Unknown_DAh: 0
Unknown_DCh: 0
Unknown_E8h: 0

PLG1_DampingAngularC: X:0.02 Y:0.02 Z:0.02
PLG1_DampingAngularV: X:0.02 Y:0.02 Z:0.02
PLG1_DampingLinearC: X:0.02 Y:0.02 Z:0.02
PLG1_DampingLinearV: X:0.02 Y:0.02 Z:0.02
PLG1_DampingLinearV2: X:0.01 Y:0.01 Z:0.01
PLG2_DampingAngularC: X:0.02 Y:0.02 Z:0.02
PLG2_DampingAngularV: X:0.02 Y:0.02 Z:0.02
PLG2_DampingLinearC: X:0.02 Y:0.02 Z:0.02
PLG2_DampingLinearV: X:0.02 Y:0.02 Z:0.02
PLG2_DampingLinearV2: X:0.01 Y:0.01 Z:0.01
PLG3_DampingAngularC: X:0.02 Y:0.02 Z:0.02
PLG3_DampingAngularV: X:0.02 Y:0.02 Z:0.02
PLG3_DampingLinearC: X:0.02 Y:0.02 Z:0.02
PLG3_DampingLinearV: X:0.02 Y:0.02 Z:0.02
PLG3_DampingLinearV2: X:0.01 Y:0.01 Z:0.01

**Comment by ooknumber13** [comment]
Fragment

UnknownB0 = 0
UnknownB8 = 0
UnknownBC = 0
UnknownC0 = 65280
UnknownC4 = 1
UnknownCC = 0
Gravity Factor = 1
buoyancy factor = 1


Fragment LOD

Type = 1

Damping = 0.02


Unknown1C = 1 / 0 / -1
Unknown48 = 1
Unknown4c = 150
Unknown50 = 6.28
Unknown54 = 1

Fragment Group

min soft angle 1 = -1
max soft angle 1 = 1
max soft angle 2 = 1
max soft angle 3 = 1

UnkFloat5C = 0
UnkFloat60 = 0 / 1
UnkFloat64 = 0 / 1
UnkFloat68 = 0 / 1
UnkFloat6C = 0 / 1
UnkFloat70 = 0 / 1
UnkFloat74 = 0 / 1
UnkFloat78 = 0 / 1
UnkFloatA8 = 0 / 1

**Comment by CFox04** [comment]
set lod type default to 1

**Comment by CFox04** [comment]
Added in 753912ad4c29717b702ec337ecefdc7017c8ed4a
