### ISSUE TITLE
Sollumz pretends that the armature has materials, doesn't let me export

### ISSUE THREAD

**Issue by MaddDoggArcheType** [Skylumz/Sollumz#494]
Trying to port a model from GTA 4 to GTA 5, Sollumz pretends that the armature has materials and doesn't let me export the model. I've tried everything that could possibly come to mind to fix it and nothing did. Tried to redo everything from the beginning with a different model, same outcome. What am I meant to do lol [https://imgur.com/a/Irz2gJo](url)

**Comment by Hancapo** [comment]
attach a blend file, no one can help you with no examples.
