### ISSUE TITLE
BVH automatic setup

### ISSUE THREAD

**Issue by Gusepe** [Skylumz/Sollumz#497]
When creating a BoundGeometryBVH, it would be interesting to have it automatically configured with the basic flags.
In this way, it is not necessary to configure these BVHs, unless the flags need to be configured manually for specific cases.
It would also be interesting if the shape margin was also set as default (0.005 if I'm not mistaken)
![sollumz_bvh_setup](https://user-images.githubusercontent.com/120711057/208055382-ff1926bb-341c-4683-9647-114607d16ce8.png)

**Comment by ooknumber13** [comment]
its a bad idea to automatically set the flag preset because not everything uses the default flags.

**Comment by gn-studio-mods** [comment]
> its a bad idea to automatically set the flag preset because not everything uses the default flags.

Yes but actually if you don't use the default Flags what do you do ? Do you select your BVH and apply specific Flags to it?
Well, that won't change for this kind of situation.
But in case you need to set your default Flags, you won't have to do anything. It's just a time saving in the Classic cases, and a non modification of your workflow in a specific case

**Comment by Gusepe** [comment]
> its a bad idea to automatically set the flag preset because not everything uses the default flags.

Yes but actually if you don't use the default Flags what do you do ? Do you select your BVH and apply specific Flags to it? I think I'm saying right?
Well, that won't change for this kind of situation.
But in case you need to set your default Flags, you won't have to do anything. It's just a time saving in the Classic cases, and a non modification of your workflow in a specific case

**Comment by CFox04** [comment]
An option was added for this in pr #499
