### ISSUE TITLE
Ytyp Tools - Flags & Set to all selected

### ISSUE THREAD

**Issue by Gusepe** [Skylumz/Sollumz#498]
It would be very interesting to add a **"Flags - Set All Flags"** section in the **Ytyp tools**.
What would be even more advanced for a better configuration of its Ytyp, would be to be able to **set to all selected** in order to be able to manage several type of asset in the same ytyp.

Example:

- my_asset_01.ydr / my_asset_02.ydr / my_asset_03.ydr / my_asset_04.ydr / my_asset_05.ydr / my_asset_06.ydr / my_asset_07.ydr
 -> Texture Dictionnary = asset_txd.ytd
 -> Flags = 32
- my_asset_decals_01.ydr / my_asset_decals_02.ydr / my_asset_decals_03.ydr / my_asset_decals_04.ydr / my_asset_decals_05.ydr / my_asset_06.ydr / my_asset_decals_07.ydr
 -> Texture Dictionnary = asset_decals_txd.ytd
 -> Flags = 8192

**Comment by CFox04** [comment]
Implemented in #500
