### ISSUE TITLE
Greatly degraded performance after importing #bn's

### ISSUE THREAD

**Issue by Lucas7yoshi** [Skylumz/Sollumz#502]
I have a file that has 4 assets
hei_hw1_07_0.ybn
hi@hei_hw1_07_0.ybn
hw1_07_vw_muzak_001.ydr
hw1_07_props_combo02_dslod_children.ydd
hei_hw1_07_strm_0.ymap

after having all this stuff imported, my exports take over 2 minutes. This seems to be largely related to collisions.

Every sollumz related action seems slow. Even just creating a new drawable from a plane takes over 30 seconds, and that's with the collision hidden in the hierarchy

https://user-images.githubusercontent.com/28872095/208831085-be82f65c-c283-4005-baed-60d8bd40e20a.mp4

**Comment by Lucas7yoshi** [comment]
Further evidence, disabling the collision collection entirely makes the create drawable action much quicker

https://user-images.githubusercontent.com/28872095/208831406-ff39cfb4-2431-4929-8b14-0b7d62dcd6ec.mp4

**Comment by alexguirre** [comment]
Doesn't seem to be an issue anymore.
