### ISSUE TITLE
Vertex Painter does not paint active color layer

### ISSUE THREAD

**Issue by Kc2693** [Skylumz/Sollumz#503]
All GTA clothing requires 2 Color Attributes (what blender calls vertex colors since 3.3). If you add two color attributes to a mesh & have the second attribute selected, it will still only paint the first color attribute, no matter whether you're in object mode or vertex paint mode.

**Comment by CuppaT-student** [comment]
fixed in latest PR https://i.imgur.com/mVm7qf9.gif

**Comment by coltfox** [comment]
Fixed in 39cbadd84c8ad4dff72b85863ee23e2e2c374351
