### ISSUE TITLE
portal are not properly exported in the ytyp

### ISSUE THREAD

**Issue by Minibull3** [Skylumz/Sollumz#505]
Hello,

There is an issues about the ytyp export & portal.
if you don't select the MLO archetype **before** clic on 'export ytyp.xml' all the portal will be set from 0 to 0 and make the game crash.

![image](https://user-images.githubusercontent.com/119362041/209105426-963e6c89-5e15-4d14-add5-02ee65c8625a.png)

if you select the mlo archetype like in the screenshot, everything will be ok.

Thanks for your help !

**Comment by Minibull3** [comment]
Hi CFox04 !
Yep exactly.

example here : 
i select the shell archetype instead of mlo archetype : 
![image](https://user-images.githubusercontent.com/119362041/209367778-d8e56046-4ac2-448f-833e-6b48be3fd8f2.png)

then export, all the portal are set from 0 to 0 even if they are properly defined in sollumz : 

![image](https://user-images.githubusercontent.com/119362041/209367828-7596499d-a5c7-4e74-9cd9-e1a43f9275fd.png)

there is many people on sollumz discord asking for help because game crash after they added there mlo in game.
99% of the time it's ytyp issue caused by portal room from/to seted to 0 even if they are correct in sollumz.

**Comment by CFox04** [comment]
Ok, I see. This will be fixed soon, thanks for reporting.

**Comment by CFox04** [comment]
Fixed in #555
