### ISSUE TITLE
Change YTYP panel layout

### ISSUE THREAD

**Issue by ooknumber13** [Skylumz/Sollumz#513]

**Comment by ooknumber13** [comment]
![image](https://user-images.githubusercontent.com/47336113/210189677-a3003073-c4f6-49fe-a40c-bdfbe5da0542.png)

**Comment by ooknumber13** [comment]
Remove the YTYP list in favour for a more compact format, maybe a drop down menu to switch between active YTYPs?

**Comment by CFox04** [comment]
I was thinking maybe a tabbed system would work nice. Where you could toggle between active tabs instead of having to open a ton of dropdowns and endlessly scroll.

**Comment by coltfox** [comment]
Implemented in 280a9e9c5a0da876876ce56a2da2e5509578b5ac
