### ISSUE TITLE
Automatically split geometries on export when vertex limit is reached

### ISSUE THREAD

**Issue by swapfr** [Skylumz/Sollumz#515]
Gims can freely export really heavy meshes, while solumz starts to distort them
mesh splitting doesn't always help

![image](https://user-images.githubusercontent.com/97851724/210153270-b8923b5d-48f7-4624-9163-edf2fe65a58c.png)

**Comment by swapfr** [comment]
Don't tell me that there is a limit for polys in gta, it's just for collisions, there is no such limitation for ydrs
There are also pretty heavy models in the game exist

**Comment by coltfox** [comment]
Implemented in yft branch
