### ISSUE TITLE
Handle more errors

### ISSUE THREAD

**Issue by coltfox** [Skylumz/Sollumz#524]
Sollumz does not account for a lot of edge cases and user errors can easily cause exceptions to be thrown. Post all unhandled errors you encounter here so we can handle them. You can either take a screenshot or copy and paste it from the info window into a code block.

**EDIT:**
Deleted errors not present in yft branch

**Comment by ultrahacx** [comment]
- Sollumz uses hardcoded node names instead of nodes type which causes error when user has different set Blender language anything other than English
![image](https://user-images.githubusercontent.com/43913907/210851535-3ff0310d-c214-4c51-b18e-1217966b6c53.png)

- Drawable having random vertex group/s without having a skeleton/bone causes the following error
![image](https://user-images.githubusercontent.com/43913907/210851854-135a200e-6dd7-458e-8484-6d43c6a94aa9.png)

**Comment by CFox04** [comment]
![image](https://user-images.githubusercontent.com/46362482/211214551-f0667281-fc30-441e-9731-a560eaa51b9d.png)
this shouldn't raise an error, also the convert functions and operators are an unholy spawn from hell and need to be refactored.

**Comment by CFox04** [comment]
![image](https://user-images.githubusercontent.com/46362482/211214632-0a63eaf0-fe4f-4437-88f7-4b9707c7ecee.png)
Check for none

**Comment by CFox04** [comment]
![image](https://user-images.githubusercontent.com/46362482/211214670-746f0fa5-fc86-43e3-ae6b-9522bd61ad8e.png)

Need a better way to get shader nodes instead of using names like this. It's very hacky and prone to error.

**Comment by CFox04** [comment]
![image](https://user-images.githubusercontent.com/46362482/211214688-492cc932-247c-4bd0-9393-20cf60daf1ab.png)
Make sure ``map`` isn't empty.

**Comment by CFox04** [comment]
![image](https://user-images.githubusercontent.com/46362482/211214748-1d41080d-6c41-4d2f-8cad-7ceda5177e8f.png)
This needs to be a warning.

**Comment by CFox04** [comment]
![image](https://user-images.githubusercontent.com/46362482/211214796-1a9fe125-bbdd-4e9d-a24d-2773e09e8fbc.png)

**Comment by CFox04** [comment]
![image](https://user-images.githubusercontent.com/46362482/211214806-404fef66-d07e-4f6a-a570-7f609dab29f9.png)
Another issue due to indexing shader node by English name.

**Comment by CFox04** [comment]
![image](https://user-images.githubusercontent.com/46362482/211214866-a53f5c69-f741-4ebb-916b-d9ee7c2019c4.png)
This should be a warning and actually skip the object like it says instead of cancelling everything.

**Comment by CFox04** [comment]
![image](https://user-images.githubusercontent.com/46362482/212477689-a58f2113-48b2-47bb-b676-d18f5b98adfd.png)
From issue: https://github.com/Skylumz/Sollumz/issues/527

**Comment by CFox04** [comment]
![image](https://user-images.githubusercontent.com/46362482/212477812-91296367-917b-4282-8733-cd3737e57a1d.png)
Display better error when modules fail to import

**Comment by Teddygirl1987** [comment]
![image](https://user-images.githubusercontent.com/95267186/212534257-27926e3c-8c06-4463-a03d-511167446426.png)

**Comment by Teddygirl1987** [comment]
its not letting me export files to make the a ydd file this is frustrating.

**Comment by CFox04** [comment]
@Teddygirl1987 You're using a very outdated version of Sollumz

**Comment by plesalex100** [comment]
![image](https://user-images.githubusercontent.com/34649178/217676190-3aad7ad0-1fe2-4901-982e-6ca1ab3615bc.png)
