### ISSUE TITLE
add something for saving presets of material parameters

### ISSUE THREAD

**Issue by swapfr** [Skylumz/Sollumz#525]
it should  save the shader settings of the selected material somewhere in some file by pressing a button, and by pressing another button it should apply those settings to another material
for example it's useful when you make a lot of textures in substance painter or designer and you've spent a lot of time looking for the perfect settings for your beautiful textures to make them look the most similar to what we see in substance and in order to avoid spending a lot of time for setting the same values for each materal, you should make it possible to save these settings and apply them 

i hope it's enough information about what I'm asking for

**Comment by levdevlev** [comment]
Copy & paste button for shader params would be nice to have too.

**Comment by coltfox** [comment]
You can already do this in Blender with the asset browser.
