### ISSUE TITLE
Suggestion to change, some functions in the creation of YTYP MLO

### ISSUE THREAD

**Issue by d1n3301** [Skylumz/Sollumz#526]
1:Change the current attachment , rooms to portals, at the moment it is not convenient, because you need to select a room then go to another tab and already assigned. Instead, I propose to change this way to a drop-down list with rooms.
![blender_p5SuF7rdl1](https://user-images.githubusercontent.com/94755823/211034774-2bbc1fe0-52ff-49a8-a38c-dd9702eedd9a.png)

2:I also propose to change the attachment of props to rooms and portals, on the same drop-down list.
![image](https://user-images.githubusercontent.com/94755823/211035082-b07b3cde-ac0a-450b-8322-4d69818725bc.png)

**Comment by CFox04** [comment]
Using a dropdown menu seems like the obvious choice, but if I remember correctly there was a limitation with the Blender API that made that not possible. I will look into it again when I get the chance as I agree, that's not a good user experience.

**Comment by coltfox** [comment]
Implemented in 2188094a025e7c4b8e3292e9a8e8466c07a85180
