### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by NteamFare** [Skylumz/Sollumz#531]
I have problem when try to import or export something inside blender project
For example i try to add teture on house project and they send my Traceback error
https://ibb.co/g6Vk8c3
How can I fix this problem

**Comment by CFox04** [comment]
This happens when a module fails to import another module. It causes a domino effect and a ton of blender properties fail to register. Try deleting Sollumz and re-installing it, and make sure you are using the latest Blender version.

**Comment by NteamFare** [comment]
I am try to reiinstall but that not help me.Not i have this problem


https://ibb.co/T4trkx1

**Comment by CFox04** [comment]
This does not appear to be a Sollumz issue. This error that node wrangler is throwing might be what causes Sollumz to fail to register for some reason. Try uninstalling node wrangler and see if Sollumz still fails to register. If you still have issues and you are sure it is related to Sollumz then feel free to repost, but I am going to close this for now.
