### ISSUE TITLE
Create Pool for fivem GTA 5

### ISSUE THREAD

**Issue by jonilson-bkb** [Skylumz/Sollumz#533]
Hello.
actually this is not even a problem but a question. I would like to know how to create a pool in Sollumz

If you can help me, I really appreciate it.

**Comment by Molicheu** [comment]
Why not ask in the discord where there is a support section instead of making an issue post that's not even an issue? Plus there is literally a tutorial on how to create a pool in the sollumz discord...in the tutorials section

**Comment by CFox04** [comment]
^ . This is a place for issues or feature request not a help forum.

**Comment by jonilson-bkb** [comment]
Thank you anyway gentlemen
I'm aware now.
