### ISSUE TITLE
Importando y exportando yft

### ISSUE THREAD

**Issue by Joanbap** [Skylumz/Sollumz#534]
Hola y enhorabuena por el plugin de blender para importar y exportar archivos.
Tengo un problema.
Importo y exporto un archivo yft.xml de un vehículo sin editarlo pero después, cuando lo pruebo, el vehículo no se mantiene en el suelo sino que lo atraviesa como si hubiera perdido la capacidad de colisionar contra el propio suelo u otros objetos.
Gracias y un saludo

**Comment by Rigonkmalk** [comment]
Hola, debes saber que por el momento, los yft no están completamente implementados y puedes encontrarte con errores de este tipo.

No obstante, si tiene sugerencias para mejorar el código, le invito a proponer soluciones 😉

**Comment by Joanbap** [comment]
Gracias por tu respuesta.
Un saludo.
