### ISSUE TITLE
Texture embed wrong

### ISSUE THREAD

**Issue by tracer8** [Skylumz/Sollumz#544]
Hi
i try to export from CodeWalker then import to blender but seem texture is wrong. 
Export model not same color as CodeWalker model viewer
Even mesh net is not the same.
Did i do something wrong?

Prop name: **stt_prop_stunt_tube_crn_5d**

![Screenshot 2023-01-21 17 25 37](https://user-images.githubusercontent.com/15725821/213863102-89e0ceaa-5585-4f62-a760-f58e94b89e8c.png)
![Screenshot 2023-01-21 17 25 28](https://user-images.githubusercontent.com/15725821/213863104-5cd552b6-daa3-473b-9618-c4d587bce42c.png)

**Comment by Rigonkmalk** [comment]
As you can see on the shaders, seems to be a tint value ( wrong one, but it is 👍 )

![image](https://user-images.githubusercontent.com/12967235/213879703-145a3f7c-93c8-4b65-92e7-5d6e0ae7f7fa.png)

**Comment by n3tc0d3x** [comment]
File > External Data > Find Missing Files > Select the textures folder from the object

**Comment by tracer8** [comment]
> As you can see on the shaders, seems to be a tint value ( wrong one, but it is 👍 )
> 
> ![image](https://user-images.githubusercontent.com/12967235/213879703-145a3f7c-93c8-4b65-92e7-5d6e0ae7f7fa.png)

Thank you may be it use tint, but i fogot to Find Missing Textures too.



> File > External Data > Find Missing Files > Select the textures folder from the object

Work like a charm, thank you!
