### ISSUE TITLE
Traceback error - importing codewalker xml file - 

### ISSUE THREAD

**Issue by afcb78** [Skylumz/Sollumz#546]
https://i.imgur.com/dBn5RuS.png

have reinstalled both application and add-ons twice with no resolution.  Anyone help or guide me as to what I can do next please?

**Comment by GreekRa** [comment]
I'm not sure cuz I dont have much knowledge about this, but make sure you are do all steps about codewalker xml export etc. Open codewalker rpf in edit mode find your ydr file, export ydr xml and export the textures of this ydr etc. Let me know if works

**Comment by CFox04** [comment]
This is a CodeWalker-related issue. For some reason the shader names are exporting as hashes, so Sollumz does not recognize them. Try asking in the CodeWalker discord.
