### ISSUE TITLE
Sorting entity by room and improvement of the add entity to room button

### ISSUE THREAD

**Issue by Gusepe** [Skylumz/Sollumz#553]
In the "entities" section of the MLO. It would be interesting to be able to easily find an entity we are looking for, or just to be able to check the objects attached to our room.
Here is my proposal, 
Add a box above the list of entities listed with the selection of the room you want, when a room is selected only the entities of the room are displayed, when no room is selected all entities are displayed.
This way we can even improve the ease of the 'Add selected object as entity to selected room' button, as you will no longer need to unfold the 'Rooms' category to select the room you want.

![sollumz_room_selection](https://user-images.githubusercontent.com/120711057/215434498-ba032a77-b234-4c6a-944d-1ca87316f6ed.png)

**Comment by SaifAlDilaimi** [comment]
definitely +1

**Comment by coltfox** [comment]
Implemented in e1e2b95c8694ef075d061913d72c1e6126c53653
