### ISSUE TITLE
Error exporting z_z_fred.yft.xml

### ISSUE THREAD

**Issue by AcezOT** [Skylumz/Sollumz#557]
I've been stuck on this error for hours, I had someone else try it for me and it let them export it successfully(not sure how),
Please anything that will help 🙏

This is the error code: 
![image](https://user-images.githubusercontent.com/124843712/217676540-cdf4f82e-fffe-45c9-aa7f-0ccc8f9b2843.png)

**Comment by AcezOT** [comment]
This error I was having was different than what you're saying.
Thanks for trying though???????

**Comment by coltfox** [comment]
@Kc2693 Bug reports for yfts are fine, in fact, encouraged. This bug report is actually helpful, I did not know about this issue

**Comment by coltfox** [comment]
@AcezOT I'll make sure to fix this for the release.

**Comment by coltfox** [comment]
Ped YFTs are unsupported https://sollumz.gitbook.io/sollumz-wiki/features#fragment-.yft
