### ISSUE TITLE
When importing, part of the name is lost

### ISSUE THREAD

**Issue by d1n3301** [Skylumz/Sollumz#560]
**After importing props, some lack the prefix "ch_" from the name, I do not know perhaps there are other examples, but so far saw only with these props** 

**The names of the props I import:**

- ch_prop_casino_diamonds_01a
- ch_prop_casino_diamonds_01b
- ch_prop_casino_diamonds_02a
- ch_prop_casino_diamonds_03a
- ch_prop_casino_till_01a
- ch_prop_ch_vase_01a
- ch_prop_ch_vase_01a
- ch_prop_champagne_01a
- ch_prop_fingerprint_scanner_01a
- ch_prop_table_casino_tall_01a

After importing we get this:
![blender_bUSNSF7hMh](https://user-images.githubusercontent.com/94755823/218328240-6c64513e-b9d8-418f-9210-8f632549b50a.png)

- Blender 3.4.1
- Sollumz GitHub version 07.02.23
- CodeWalker v44**

**Comment by ooknumber13** [comment]
https://i.imgur.com/XJVabh4.png Sollumz is using the name in the XML not the actual YDR name, so it seems like they renamed the YDRs or some shit

**Comment by coltfox** [comment]
^
