### ISSUE TITLE
Importing xml in Blender does fail

### ISSUE THREAD

**Issue by DaNeubi** [Skylumz/Sollumz#568]
If i try to import a xml file from the latest codewalker with the latest sollumz plugin version.
This is the error, I get in Blender. Couldn't find anything about it.

A friend of mine tried importing the file the same way and it worked for him.

![grafik](https://user-images.githubusercontent.com/6529346/219516685-af913f39-917e-4843-923e-3139431fb91f.png)

**Comment by CuppaT-student** [comment]
change your blender language to english and try again

**Comment by DaNeubi** [comment]
thanks a lot! this helped!
