### ISSUE TITLE
Difficulty importing a ydd

### ISSUE THREAD

**Issue by Fatichti** [Skylumz/Sollumz#571]
Hello everyone 👋 ,

I would like to import Rockford Plaza to edit the building like removing the escalators.
The template is: **bt1_04_slod1**
![image](https://user-images.githubusercontent.com/74354655/219824772-75bd9e16-9188-4061-a789-966ea4a27dce.png)

With RPF search on codeWalker, it gives: **bt1_04_slod1_children.ydd**

I did the extraction to XML as well as the file ss1_lod_bt04_children.ytd

I put the textures (18 in all) in the bt1_04_slod1_children folder
![image](https://user-images.githubusercontent.com/74354655/219824798-033c3dce-05b9-4cde-a6e0-ee4a7e5fd34b.png)

**Comment by Hancapo** [comment]
You need a name table to resolve the hashed names from the .#DD (You can find more info about this in #resources channel in CodeWalker's Discord Server, the search function is your friend), also you need to set your Blender's language to English.

**Comment by Fatichti** [comment]
WOW thanks so much, i just set language to English and it's better ! (sorry i am french XD)
you know how i can separate the YDD on multiple YDR to work separatly ?

**Comment by coltfox** [comment]
A ydd is just a collection of ydrs, so you can just unparent the ydrs from the ydd and export each ydr separately. If you need further help please ask on the discord, as this is not a bug.

**Comment by Fatichti** [comment]
Ok thx <3
I will follow the conversation on discord (because now, there are no textures XD)
