### ISSUE TITLE
Cloth models not importing

### ISSUE THREAD

**Issue by levdevlev** [Skylumz/Sollumz#572]
Cloth objects are not imported, could be an issue since they're YFT's but still...

![image](https://user-images.githubusercontent.com/110393325/219881432-c46c4ee8-730f-4c44-b64f-01e765fe6d8d.png)

**Comment by CuppaT-student** [comment]
https://i.imgur.com/ngUi0VP.gif & https://imgur.com/a/rQAiZul

**Comment by coltfox** [comment]
Cloth yfts are not supported atm and they won't be supported at the initial yft release.
