### ISSUE TITLE
To many colors layers on mesh

### ISSUE THREAD

**Issue by alireza-da** [Skylumz/Sollumz#574]
greetings
![image](https://user-images.githubusercontent.com/47556466/220090797-e6035d7d-bc8a-4fa3-a11a-ebc5b76aa85d.png)
hirarchy
![image](https://user-images.githubusercontent.com/47556466/220090888-8e7edfee-a6aa-483d-9517-97f5ad3a7560.png)

**Comment by coltfox** [comment]
You're using an outdated version of Sollumz. Make sure to download from GitHub https://github.com/Skylumz/Sollumz/wiki#installation . If you still have a problem on the latest version feel free to make another issue.
