### ISSUE TITLE
[Light] Does not export the Shadow Blur setting

### ISSUE THREAD

**Issue by Gusepe** [Skylumz/Sollumz#578]
![image](https://user-images.githubusercontent.com/120711057/220381608-67917174-356b-4da2-aee1-95c4e8834907.png)
Tried with an old and new version of sollumz, with and without the "scale light intensity" option

**Comment by Gusepe** [comment]
edit: after research the xml file contains the value set with sollumz, but this value is not taken into account during the import in lr rpf explorer

**Comment by ultrahacx** [comment]
Update CW to latest version

**Comment by Gusepe** [comment]
My Codewalker is up to date (CodeWalker30_dev44)
The problem will apparently come from the Rpf Explorer, you can try to export v_55_tor_mesh_worklight.ydr yourself, which has several lights with the shadowblur. 
The xml file should have a line like this <ShadowBlur value="80" />, but it doesn't include

**Comment by Gusepe** [comment]
I don't know if this helps but here is a ydr.xml with the shadow blur parameter
[gn_sheriff_corridor_b_proxy.zip](https://github.com/Skylumz/Sollumz/files/10795076/gn_sheriff_corridor_b_proxy.zip)

**Comment by Gusepe** [comment]
oh ok i saw this was patched but it must not have been built on a release
