### ISSUE TITLE
clothing ydd exported file issue

### ISSUE THREAD

**Issue by 34Destiny** [Skylumz/Sollumz#583]
File exported from gta or from 3ds max not contain skeleton category inside file, but exported with sollumz contain it. It causes problems when you want to open your model in openiv and also file weight more.
![exported_with_3dsmax](https://user-images.githubusercontent.com/126720595/222259188-589b8208-e372-4315-add1-acf959c6000f.png)
![exported_with_blender](https://user-images.githubusercontent.com/126720595/222259191-41345630-0bbe-4f74-addd-e3b1183581d4.png)

**Comment by Loyalists** [comment]
Which file is it? The exported file should not contain the Skeleton block if the skeleton is absent.

**Comment by 34Destiny** [comment]
This is clothing ydd file made from scratch. But everytime you import this type of file to blender and export it, it contains skeleton. This is also reason why we cant import file edited in blender to zmodeler3.

**Comment by 34Destiny** [comment]
sorry i accidentally closed it
