### ISSUE TITLE
Wrong placement of Room Gizmo

### ISSUE THREAD

**Issue by Rigonkmalk** [Skylumz/Sollumz#587]
Version of Sollumz used : Last version from GH
Version of Blender : 3.4.1

Description :

When I import v_int_4.ytyp file for editing purpose, room Gizmo is centered through origin and not correctly placed.

How to Reproduce : 

- export v_int_4.ytyp
- import it
- profit

Blender view :

![image](https://user-images.githubusercontent.com/12967235/222693934-ea1c7900-5e18-4ade-abb3-c31d3014136b.png)

CW view ( not the exported one ) :

![image](https://user-images.githubusercontent.com/12967235/222694033-7887f6ab-1fcd-43bc-9423-d5bed8eeba58.png)

No issue on CW after exporting the file without editing something.

CW view ( after export the file ) :

![image](https://user-images.githubusercontent.com/12967235/222695040-d6388f6b-eb35-4deb-a94b-00df7df6bf17.png)

**Comment by ooknumber13** [comment]
could you try exporting the ytyp XML to make sure its just the gizmo and not the import / export code?

**Comment by coltfox** [comment]
This issue has already been reported here https://github.com/Skylumz/Sollumz/issues/466
