### ISSUE TITLE
ADD timeflags in archetype property

### ISSUE THREAD

**Issue by Gusepe** [Skylumz/Sollumz#588]
![image](https://user-images.githubusercontent.com/120711057/222894740-9e4364de-653d-40a2-a445-d06bb006a846.png)

**Comment by ooknumber13** [comment]
![image](https://user-images.githubusercontent.com/47336113/222967482-033a9478-2414-4473-9862-209375335a77.png)

it already exists.

**Comment by coltfox** [comment]
It has to be a time archetype. Select the dropdown where it says "Base" and change it to "Time".
