### ISSUE TITLE
Incorrect embedded texture folder naming on export

### ISSUE THREAD

**Issue by ultrahacx** [Skylumz/Sollumz#590]
Currently Sollumz creates embedded texture folder name based on the name of the drawable model whereas the folder name should be of the highest available parent of sollumz_type.

As an example, upon export of a YDD, multiple folders are created by drawables names instead of a single folder with the name of YDD:
![image](https://user-images.githubusercontent.com/43913907/222968407-9793da1b-0c8e-4a61-abac-1e643d8fb521.png)

There's a current [bypass](https://github.com/Skylumz/Sollumz/blob/458171750eadeb731a344ad3e4f91e4320145c1a/ydr/ydrexport.py#L781) for fragments but it should be dealt at fundamental level instead of passing parameters like `is_frag` in functions. Continuing the approach of passing `is_*` as a parameter can severly convolute the function parameters in future.

**Comment by coltfox** [comment]
Fixed in b1122ea4401d3e4b328f5622cdfb5c4ba7e437f2
