### ISSUE TITLE
Exporting problem with hierarchy!

### ISSUE THREAD

**Issue by BalasIgor1998** [Skylumz/Sollumz#591]
Hello, my problem happens when i try to export model after editing. I used example of original  hierarchy from tailgater, but when exporting I receiving message "No objects of type: drawable dictionary or drawable or bound composite to export." Double checked if everyithing is right but still can't find issue, where can I find proper example of hierarchy

**Comment by coltfox** [comment]
GitHub issues is for bug reports and feature requests only. If you need help please ask in our [discord](https://discord.gg/UZ2rb2qxAy).

> where can I find proper example of hierarchy

Here: https://github.com/Skylumz/Sollumz/wiki/Importing-and-Exporting#drawable-ydrxml
