### ISSUE TITLE
The door stopped sliding when import to blender and export again

### ISSUE THREAD

**Issue by dunham94** [Skylumz/Sollumz#595]
I discovered a bug guys with the plugin, I imported a Van in blender. with format " yft " ... ok , but this Van , it has a DOOR THAT SLIDES OPEN INSTEAD OF OPENING, ok ... I edited it... after that, I exported it back to any folder ... and then converted it to the game ... Result, THE DOOR THAT SLIDES, STOPS SLIDING.... it started to open NORMAL FORM instead of SLIDING

**Comment by MidgetHD** [comment]
Yeah, YFT isn't currently supported

**Comment by coltfox** [comment]
^
