### ISSUE TITLE
Drawable Shader Groups and Collision Shader Groups

### ISSUE THREAD

**Issue by Kozzren** [Skylumz/Sollumz#597]
Is it possible to make these two have groups/tabs like 3ds had it. For instance Hard Terrain is one group Vegetation is another one etc. Also for when the ymap gets the same ui as ytyp would it be possible to have a button that auto generates LOD distanceses based on drawable bounds?

**Comment by coltfox** [comment]
I don't plan on grouping the materials, as I think it is unnecessary. You can search the lists by clicking the dropdown which should be all you need. As for your second suggestion, that could possibly be done. Just make a new issue specific to your second suggestion and be more clear on how exactly the LOD distances would be generated from the drawable bounds.

**Comment by Kozzren** [comment]
Ah fair point I only suggested it for ease of use specially for new people who dont know all the shaders, then again there is the auto convert button, But ill make that new post with that next suggestion and again thank you for your amazing work i love sollumz!

**Comment by coltfox** [comment]
Of course! Thanks for the feedback!
