### ISSUE TITLE
Occlusion Box Export

### ISSUE THREAD

**Issue by Gusepe** [Skylumz/Sollumz#601]
tried to create occlusion boxes, it seems that sollumz exports the scale instead of the object dimensions. This is annoying because when we create a box whether it is a collision or occlusion, its scale is 1.
Here is an example of the same box in blender and in codewalker.
I
![F0E68846-1F65-4553-9C6C-0532C4B0123F](https://user-images.githubusercontent.com/120711057/227792604-b657decd-4ba4-40dc-9736-e1b4a0864a49.png)
![D4B458C5-1649-4EF2-8ADD-8FA5BF91915F](https://user-images.githubusercontent.com/120711057/227792607-70faf345-2a7a-48e2-a4f4-a0407bb0cc81.png)

**Comment by coltfox** [comment]
Fixed in https://github.com/Skylumz/Sollumz/commit/90dfc6ce152e424a2911595611287763a6d88d5d
