### ISSUE TITLE
Error Exporting YDD Files

### ISSUE THREAD

**Issue by iceagexx** [Skylumz/Sollumz#602]
I was export my ydd files and this error is show up
What is this error code means and how can i fix it ?
![Capture](https://user-images.githubusercontent.com/129215824/228331121-f0f6c3e2-d279-4cb6-bc25-addff0befabc.PNG)

**Comment by coltfox** [comment]
Hm, not sure how that error is related to exporting ydds. Can you attach a blend file reproducing the issue?

**Comment by iceagexx** [comment]
> Hm, not sure how that error is related to exporting ydds. Can you attach a blend file reproducing the issue?

[clothes.zip](https://github.com/Skylumz/Sollumz/files/11182965/clothes.zip)

here you are, i have tried to make custom clothes by tranfer weights with in game clothes. but i got some error export again.
![dd](https://user-images.githubusercontent.com/129215824/230715839-eed1af46-a18f-4e24-934c-24a215ef9fdb.PNG)

**Comment by coltfox** [comment]
The original error is unrelated. This error occurs because you don't have any materials on the object, it's not a bug. Check the tutorials at #tutorials on the discord and if you're still confused ask for help in the help channels.
