### ISSUE TITLE
create shader doesnt work

### ISSUE THREAD

**Issue by Nova89TV** [Skylumz/Sollumz#605]
hello, I'm trying to create a sign for fivem but when I try to create a shader I get this error and I don't know how to fix it. I use blender in version 3.4
![Cattura](https://user-images.githubusercontent.com/129515257/229118128-608f6540-21f6-4da9-8940-dc7954440a45.PNG)

**Comment by coltfox** [comment]
This is a known bug. To fix this, you have to change your Blender language to English for now, sorry.

**Comment by Nova89TV** [comment]
> This is a known bug. To fix this, you have to change your Blender language to English for now, sorry.

Really? just change the language and it works?

**Comment by coltfox** [comment]
Yes. The error occurs because the code expects there to be a node called "PrincipledBSDF", but if the language isn't English, it's called something else.

If for some reason switching the language doesn't fix your issue let me know and I will reopen the issue.
