### ISSUE TITLE
Selected Objects export parameter - Activate by defaut

### ISSUE THREAD

**Issue by Gusepe** [Skylumz/Sollumz#607]
I think that most of the time everyone just exports their selection.
If this is the case, it should be enabled by default.
(Yes, this can avoid a mistake of exporting the whole project if you forget to activate the option)

**Comment by d1n3301** [comment]
I did such a PR, I was told that it would be added to the settings later, so that people could choose for themselves

**Comment by coltfox** [comment]
> I did such a PR, I was told that it would be added to the settings later, so that people could choose for themselves

Yes, this is going to happen eventually. I've just been busy with yfts lately. I am probably going to add it to the yft branch and just merge it along with yft.

I'll post in #feedback to see what people think about making this option default to True.

**Comment by coltfox** [comment]
Implemented in 5192226da422e8fbba510f3ce6554d80ae3739a5
