### ISSUE TITLE
Michael's head bone placements are very weird

### ISSUE THREAD

**Issue by GordonFreakman** [Skylumz/Sollumz#608]
When importing player_zero/head_000_r.ydd.xml, this happens. Michael's head bone placement seems to be rotated 90 degrees on everything except the facial bones.
![uh](https://user-images.githubusercontent.com/75632358/230596246-6c843436-62d7-482f-b88f-eeccc6698614.png)

**Comment by BrynnaDaRosa** [comment]
Protag heads skeletons always import like this. What you want to do now is import the yft skeleton if you really need it to pose Michael's face for whatever you're planning.
