### ISSUE TITLE
In new scene sollumz list of shaders to create is empty.

### ISSUE THREAD

**Issue by e-49** [Skylumz/Sollumz#609]
If you create new scene, list of shaders will be empty.
Default scene:
![2222222222](https://user-images.githubusercontent.com/88804666/230855909-b7bd4afc-2c77-4c0f-92cd-9a664677ec74.JPG)
New scene:
![333333333](https://user-images.githubusercontent.com/88804666/230855924-627e96fa-a225-4f45-b706-5b21053c0e59.JPG)
P.S collision materials and flag presets is also will be empty
![444444444](https://user-images.githubusercontent.com/88804666/230856181-f88c832a-112c-4c93-8a9b-ffad156a5999.JPG)

**Comment by ooknumber13** [comment]
you need to restart blender.

**Comment by coltfox** [comment]
Restarting blender with the new scene active should fix it, but you shouldn't have to do this, so I'll mark this as a bug.
