### ISSUE TITLE
Can't import xml to codewalker

### ISSUE THREAD

**Issue by SlightlyPeckish** [Skylumz/Sollumz#611]
Forgive me if I'm missing something obvious but I followed all the steps in [this tutorial](https://github.com/Skylumz/Sollumz/wiki/Basic-YDR-Creation-Tutorial) got the model exported as an ydr.xml and I can't figure out how on earth I import it into codewalker

**Comment by ooknumber13** [comment]
this isnt an issue with Sollumz, in the future please dont make bug reports for issues not related to Sollumz

**Comment by SlightlyPeckish** [comment]
Sorry about that do you know how I can do it at least? or maybe how to convert the xml into a usable ydr?
