### ISSUE TITLE
export xml error 

### ISSUE THREAD

**Issue by LievreAI** [Skylumz/Sollumz#616]
![Screenshot 2023-04-18 182508](https://user-images.githubusercontent.com/84988313/232825964-b6306f7b-0358-4608-8ce8-d5f395106ac0.png)

i using the latest version of the plugin but cant export it , please help me i cant realize what the problem

**Comment by ook3D** [comment]
do you have empty vertex groups on the object?

**Comment by enot444** [comment]
Same problem

**Comment by coltfox** [comment]
This looks like a user error. Try asking for help on the discord first.
