### ISSUE TITLE
portals get moved to the next one if you delete a portal

### ISSUE THREAD

**Issue by SaifAlDilaimi** [Skylumz/Sollumz#632]
If you remove a portal that is somewhere between the first and last portal, all portals loose their association and the from/to selection list will be incorrect. You have to set all portals from/to again.

**Comment by coltfox** [comment]
https://gyazo.com/3621315aeca74bafec2eca9eaa28fcd1.mp4

Doesn't happen for me. Am I understanding the issue correctly?

Make sure you're on the latest version of Sollumz.
