### ISSUE TITLE
Error on XML inport

### ISSUE THREAD

**Issue by GamingMakingDave** [Skylumz/Sollumz#635]
Hey have this error. when import a codewalker ydr.xml

![image](https://user-images.githubusercontent.com/87772503/236076942-8777ac4e-5f85-411e-a26a-d9d0d8887b40.png)

![image](https://user-images.githubusercontent.com/87772503/236077008-0c87d72e-56fe-4e2d-80c1-250cc63d7a60.png)

**Comment by ook3D** [comment]
change language to english

**Comment by MurilloGavron** [comment]
my blender is in english and same errors

**Comment by gutzzina** [comment]
I have the same error, could someone solve it?

**Comment by GamingMakingDave** [comment]
my blender is eng. ^^

**Comment by GamingMakingDave** [comment]
i have newest blender and latest version from here isnt work

**Comment by EvokeAU** [comment]
I'm having this same issue, using blender 3.4 and 3.5 spits these errors on import of ydd.xml. The YFT is there, tried re-installing latest version of sollumz and ran in to the same issue, also get similar error messages when installing the addon

**Comment by coltfox** [comment]
I am about 99% sure this error is caused by not having Blender set to English. Try this:
1. Uninstall Sollumz
2. Set Blender language to English
3. Restart Blender
4. Reinstall Sollumz

**Comment by Chiller2019** [comment]
Why the hell I must change the language to work?
Can I change the language back after the import?

**Comment by alexguirre** [comment]
@Chiller2019 A bug (#708), it has been fixed for next release, 2.1. Not released yet, but you can download and install the ZIP of the repo in the meantime.
