### ISSUE TITLE
yft Collision export issue

### ISSUE THREAD

**Issue by cheesykyle** [Skylumz/Sollumz#636]
Exporting a yft with child LOD collisions renders an incorrect collision.

As an example, importing prop_beach_ring_01 and exporting without changes results in the in-game collision being a very small area at the front of the prop, despite Codewalker showing seemingly correct collisions.

Unable to determine if it's an issue on import or export.

**Comment by coltfox** [comment]
Yft is unsupported for Sollumz. There is a new version currently in closed early access for Patreons that uses a new, simpler hierarchy.
