### ISSUE TITLE
cant add more than one entity to mlo

### ISSUE THREAD

**Issue by brofx1** [Skylumz/Sollumz#637]
Hi,
on newest version of sollumnz you cant add more than one entity to mlo, after "adding" second entity it will show error message

![image](https://github.com/Skylumz/Sollumz/assets/95037479/aa402a9a-60d8-44f3-a967-0554ca386290)

https://streamable.com/f5gc57

👍

**Comment by Rigonkmalk** [comment]
Same issue here

**Comment by coltfox** [comment]
Fixed in 924aa0032ad37077de414bbc322a1f28f4851a87
