### ISSUE TITLE
newest version breaks my MLO

### ISSUE THREAD

**Issue by SaifAlDilaimi** [Skylumz/Sollumz#638]
So I had the version of this commit 4d4bd8d and everything was working fine (except animation but thats another topic). However, today I updated to the current version and suddenly my MLO broke. All entities started flickering, some didnt even showed up. Reverting back to 4d4bd8d solved the issue. I'm not sure why and what you guys need to replicate it. If you guys need anything tell me..

**Comment by coltfox** [comment]
Can you send some videos of your issue and attach blend files to reproduce the issue? Also, try the latest version, I just pushed an update.

**Comment by coltfox** [comment]
Closing this for now. If you have this issue feel free to repost, just make sure to attach a blend file that reproduces the issue.
