### ISSUE TITLE
ytyp error entity

### ISSUE THREAD

**Issue by 4lby00** [Skylumz/Sollumz#639]
hi , so i'm having problems with the ytyp file of my mlo when i try to attach an entity to the room on blender everything goes fine but when i export the added entities they move to none so they are not attached to any room

https://github.com/Skylumz/Sollumz/assets/133820552/fd4bb3fa-7c0a-459e-8c29-1b9553a1c700

**Comment by coltfox** [comment]
Fixed in ec54e40430fad0ecb894a99b6b3fdc672a622cd7
