### ISSUE TITLE
Emissive bug

### ISSUE THREAD

**Issue by lucaspdp** [Skylumz/Sollumz#641]
I have a Emissive model in Sollumnz and when I test it, it wasnt emissive.
I put it in Gims Evo(3ds Max) and I export it again, and it makes emissive... This is the project (from blender and odr from gims), they are exported in:

[gims_logo.zip](https://github.com/Skylumz/Sollumz/files/11504205/gims_logo.zip)
[solumnz_logo.zip](https://github.com/Skylumz/Sollumz/files/11504210/solumnz_logo.zip)

**Comment by coltfox** [comment]
I will close this for now as it needs more information, and this sounds more like a user error than a bug. Please first ask for help on the ([discord](https://discord.gg/UZ2rb2qxAy)), and make sure you explain EVERYTHING you did so people can help you. If you still can't solve your problem after getting help from people, feel free to make another issue, just provide more information next time.
