### ISSUE TITLE
Exporting xml file

### ISSUE THREAD

**Issue by LillyPaige** [Skylumz/Sollumz#642]
very new to this so not sure if it's something I am doing wrong if I could be pointed in the right direction ill really appreciate it thank you.

![Screenshot 2023-05-22 093602](https://github.com/Skylumz/Sollumz/assets/83020705/08a6fb38-1298-4dec-a600-69261e1adca1)

**Comment by MurilloGavron** [comment]
see last line, you model have more 65k vertices
