### ISSUE TITLE
There is a problem with the material used to create Sollumz.

### ISSUE THREAD

**Issue by bonjour111** [Skylumz/Sollumz#645]
Yo, I have a 3.4.1 version of Blender with Sollumz plug-in, but I seem to have a problem. Blender cannot create Sollumz's material by clicking Default. The following photos. After clicking Create Shader Material, it will not be created.
![11](https://github.com/Skylumz/Sollumz/assets/75312360/440196c6-046a-4f25-9da5-0f336dca4ee6)
![22](https://github.com/Skylumz/Sollumz/assets/75312360/90a857be-c852-45d4-a2fa-b1ce810dbd0b)

**Comment by DyroS3** [comment]
可以加个联系方式进行交流吗？

**Comment by bonjour111** [comment]
> 可以加个联系方式进行交流吗？

当然 你的是多少

**Comment by Rigonkmalk** [comment]
你是否在使用Github上的最新版本的Sollumz？

**Comment by bonjour111** [comment]
> 你是否在使用Github上的最新版本的Sollumz？

当然

**Comment by Rigonkmalk** [comment]
![blender_ESk7kB5I3F](https://github.com/Skylumz/Sollumz/assets/12967235/1c0b87c6-f31e-465c-84ca-a4ce84e82fca)

Did you have the same shader tools ?

**Comment by bonjour111** [comment]
This is a video. Watch it for yourself.  https://streamable.com/b1jbwd

**Comment by Rigonkmalk** [comment]
Yes right, the language is useful on Sollumz 😊

**Comment by coltfox** [comment]
> > ![blender_ESk7kB5I3F](https://user-images.githubusercontent.com/12967235/240661759-1c0b87c6-f31e-465c-84ca-a4ce84e82fca.gif)
> >       
> >         [
> >           
> >         
> >             ![blender_ESk7kB5I3F](https://user-images.githubusercontent.com/12967235/240661759-1c0b87c6-f31e-465c-84ca-a4ce84e82fca.gif)
> >           ](https://user-images.githubusercontent.com/12967235/240661759-1c0b87c6-f31e-465c-84ca-a4ce84e82fca.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/12967235/240661759-1c0b87c6-f31e-465c-84ca-a4ce84e82fca.gif)
> >         
> >       
> > 你有相同的着色器工具吗？
> 
> Ohh, this is a big problem with a plug-in. If I change Chinese into English, it will work, but Chinese will not.😑 This is a video. Watch it for yourself. https://streamable.com/b1jbwd It's been bothering me all day and it's just a stupid question of changing the language.🤣😐

Yep, and iirc there are other issues caused by this too For now, it's recommended to use English.
