### ISSUE TITLE
yft export shader problems

### ISSUE THREAD

**Issue by 0xA0426** [Skylumz/Sollumz#648]
![image](https://github.com/Skylumz/Sollumz/assets/107247709/11098c0d-6466-49cf-96e0-f2cc40dd4bc8)

When exporting a model, some elements are not exported where there is a designated shader as vehicle_cloth

**Comment by ook3D** [comment]
Vehicles are not expected to work correctly on the main branch.

**Comment by coltfox** [comment]
^. Yft support is currently in early-access for patrons only. Yfts are not supported on the main branch.
