### ISSUE TITLE
Incorrect CExtensionDefAudioEmitter export for YTYP

### ISSUE THREAD

**Issue by danix9303** [Skylumz/Sollumz#659]
When exporting a YTYP with objects with audio emitter extension, CExtensionDefAudioEmitter should be:

       <Item type="CExtensionDefAudioEmitter">
          <name>YOURPROPNAME</name>
          <offsetPosition x="0.00000000" y="0.00000000" z="0.00000000"/>
          <offsetRotation x="0.00000000" y="0.00000000" z="0.00000000" w="1.00000000"/>
          <effectHash value="EFFECTHASH"/>
        </Item>

But instead, this is what Sollumz exports:

        <Item type="CExtensionDefAudioEmitter">
          <name>PROPNAME</name>
          <offsetPosition x="0.0" y="0.0" z="0.0" />
          <offsetRotation x="0.0" y="0.0" z="0.0" w="1.0" />
          <effectHash>EFFECTHASH</effectHash>
        </Item>

This prevents the YTYP from being imported into CW RPF Explorer.
Thank you for your attention!

**Comment by Hancapo** [comment]
Fixed in #663
