### ISSUE TITLE
Drawable vertex duplication bug

### ISSUE THREAD

**Issue by Kc2693** [Skylumz/Sollumz#666]
Hey
There's some sort of bug going on with Sollumz where drawables can export with many more vertices than they should have. Originally brought to attention by TinyBigJacko in discord (https://discord.com/channels/899043946142003240/905963185381716050/1119677391518834698). Exporting one of the heist3 YDDs. 
 
Per Jacko's experiment:
In CW RPF before import this shirt reports as having 2595 verts
![CodeWalker_RPF_Explorer_4nn8wWpCVS](https://github.com/Skylumz/Sollumz/assets/28677397/28fe48a9-a015-41f7-9f7a-fd912040b736)

After sollumz export:
![CodeWalker_RPF_Explorer_hC3L5QAO1u](https://github.com/Skylumz/Sollumz/assets/28677397/525417fd-dc61-4ccd-9c3a-3349bb14a922)

I tried this myself. Here is the statistics in blender:
![3](https://github.com/Skylumz/Sollumz/assets/28677397/d26ae8ac-348f-46de-8187-517705b6fad2)

Thinking it was just an issue with merged vertices, I merged vertices, then exported:
![1](https://github.com/Skylumz/Sollumz/assets/28677397/128c6949-157a-4246-857d-267a49f501f7)

The same thing is being reported in OIV:
![image](https://github.com/Skylumz/Sollumz/assets/28677397/d6297288-c67c-4c2f-9570-e7dd46155afc)

As an experiment I think took the geometry out of the YDD, deleted vertex groups, and exported as YDR but still has the same issue:
![2](https://github.com/Skylumz/Sollumz/assets/28677397/56e8a543-3df7-40b1-a3fd-4f595e271e22)

**Comment by coltfox** [comment]
No longer an issue on yft branch
