### ISSUE TITLE
Blender lagging after updating

### ISSUE THREAD

**Issue by SaifAlDilaimi** [Skylumz/Sollumz#667]
Hello guys, 

I have a project that has a very big ytyp and I have updated to the current version of sollumz. As soon as I open the entities the whole UI lags and I cant click on any button. In the console see only this warning:

![image](https://github.com/Skylumz/Sollumz/assets/3785570/335ff925-0a9e-4a88-a9b3-3f56685b6872)

**Comment by coltfox** [comment]
Please update to the latest version of Sollumz and make a new post with the blend file attached.
