### ISSUE TITLE
I get this error while exporting " PBBNCCTT layout is not found in the shader 'ped' "

### ISSUE THREAD

**Issue by Ayccoe** [Skylumz/Sollumz#673]
I'm kind of new to this and trying to figure things out, but I get this with everything i wanna export, don't know if i'm missing something.
anyone can help me?
![Screenshot 2023-07-03 003042](https://github.com/Skylumz/Sollumz/assets/138401132/aaedc1a8-b29d-4586-a4b7-43cf7605ec28)

**Comment by ook3D** [comment]
dont edit the shader nodes

**Comment by Ayccoe** [comment]
> dont edit the shader nodes

I don't change the nodes and this still happens with "ped" shaders. and now when i try to use the original shader from the original file, the necklace shows invisible in game.
