### ISSUE TITLE
No objects of type: drawable or fragment or clip dictionary or drawable dictionary or bound composite or ymap to export.

### ISSUE THREAD

**Issue by VladMarkov1** [Skylumz/Sollumz#674]
I have this problem since i have the new pc, everything ok with the import, but when I export shows me this problem.
The thing is that even if I import and export the same model, without changing anything, keeps showing me this error,
Any solution? Its quite urgent,

**Comment by ook3D** [comment]
literally just select the object

**Comment by VladMarkov1** [comment]
![image](https://github.com/Skylumz/Sollumz/assets/138591473/c67ed8cb-4939-4a7d-a4bc-1e7f9009cab7)
That doesnt work if i select and export doesnt show me anything, this is a quite new problem for me

**Comment by Rigonkmalk** [comment]
Please follow instructions :

What's the issue ? As I see, export issue where your ped doesn't appear.
Can you please give your .blend file for understanding your issues.

You can also open a thread on the Sollumz's discord if you need

**Comment by VladMarkov1** [comment]
Good new guys it was a name part problem, just change the name to FiveM peds type names and it worked, thank u all for the help
