### ISSUE TITLE
cablemesh broken again

### ISSUE THREAD

**Issue by FilipeCuco** [Skylumz/Sollumz#683]
after editing and exporting it looks like this
![image](https://github.com/Skylumz/Sollumz/assets/116587926/8db196c5-c102-4966-a4e2-204920ebe891)

this is the default without any editing
![image](https://github.com/Skylumz/Sollumz/assets/116587926/f1048670-9878-4f59-b6a8-0b5f3baaab2c)

**Comment by ook3D** [comment]
this isnt an issue with sollumz, codewalker breaks it regardless.

**Comment by FilipeCuco** [comment]
> this isnt an issue with sollumz, codewalker breaks it regardless.

how can it be from CodeWalker if I just exported and imported the same file without modifications and it is normal?

**Comment by ook3D** [comment]
> > this isnt an issue with sollumz, codewalker breaks it regardless.
> 
> how can it be from CodeWalker if I just exported and imported the same file without modifications and it is normal?

change the in game tessalation setting to high and you will see
