### ISSUE TITLE
occlusion bug

### ISSUE THREAD

**Issue by FilipeCuco** [Skylumz/Sollumz#686]
when I edit and export the occlusions this happens
the blue boxes get bug

Edited:
![image](https://github.com/Skylumz/Sollumz/assets/116587926/c7944f93-c55a-4be8-a15a-d5d68abcf913)

Default:
![image](https://github.com/Skylumz/Sollumz/assets/116587926/4b7a7b8a-8557-46c6-a433-04512c01b504)

**Comment by coltfox** [comment]
Fixed on yft branch
