### ISSUE TITLE
YTYP bug

### ISSUE THREAD

**Issue by nikit0** [Skylumz/Sollumz#687]
Blender v: 3.6.1
Sollumz v: latest

Some days I'm testing, and this bug is happening...

I'm using a Ytyp Vanilla: v_int_24, when you export from CW to Blender and then from Blender Pro CW, it looks like this.

![image](https://github.com/Skylumz/Sollumz/assets/45583155/0940b15d-9d2e-4e4e-85c3-1f0943d988b2)
![image](https://github.com/Skylumz/Sollumz/assets/45583155/34576f68-b3a8-46e1-a03a-9abb3ab0d3ba)

All Objects lose their default location and rotation

**Comment by coltfox** [comment]
Fixed on yft branch (will be merged soon)
