### ISSUE TITLE
"emissive_clip" material has not BSDF socket connect to material output

### ISSUE THREAD

**Issue by MoravianLion** [Skylumz/Sollumz#688]
emissive_clip material has not BSDF socket connect to material output, resulting in non transparent places of the texture, visible as black.

![image](https://github.com/Skylumz/Sollumz/assets/38085706/d387e646-e24e-4379-84d7-a3e9951ff65f)

**Comment by ook3D** [comment]
seems to be for all emissive shaders, looking into a fix.
