### ISSUE TITLE
I cant get my ydd file

### ISSUE THREAD

**Issue by Grindhardsnap787** [Skylumz/Sollumz#692]
I been practicing for months i can make a chain easy now but i cant seem to figure out how to get the ydd can somebody help its giving me a error about polycount then even after I lowered that i only get ydr

**Comment by P-lauski** [comment]
Not a sollumz issue, post in the Sollumz discord for help.

> I been practicing for months i can make a chain easy now but i cant seem to figure out how to get the ydd can somebody help its giving me a error about polycount then even after I lowered that i only get ydr
