### ISSUE TITLE
Key error 22

### ISSUE THREAD

**Issue by planetpatrick** [Skylumz/Sollumz#693]
![image](https://github.com/Skylumz/Sollumz/assets/17790754/d5aa38c5-84ef-41c9-90df-765186b1a1a4)
how do i fix?

**Comment by P-lauski** [comment]
@planetpatrick So this isnt an issue with Sollumz itself so post issues like this in the discord in future, as it is a problem with the vest model you are trying to import, you would need to check your .xml of the model as it looks like one of your texture "<format>" is listed as '22' and not as a dxt.

**Comment by P-lauski** [comment]
Same as #689 where you could have also got your solution
