### ISSUE TITLE
Export Issue for YDR/YBN

### ISSUE THREAD

**Issue by Z3USmodding** [Skylumz/Sollumz#699]
Hi, 

Firstly I know how to make a YDR following this tutorial so that's not the issue 
https://www.youtube.com/watch?v=YPuKM8vHg-4&t=250s&ab_channel=Quixotic

I had a problem so I reinstalled Blender and Sollumz (using the version from here).

My YDR is make like in the video:

Name
   Bound Composite
       Bound Geometry VBH
            Bound Poly Mesh
   Drawable Model
       Name model
       
Now when I want to import my YDR (a simple cube to make it simple), instead of having one YDR I got 3 files:
- the YDR
-Bound poly mesh.ybn
-Bound geometry VBH.ybn

When I want to export a YBN same problem, but instead of 1 file YBN I got 2

Pls help me because I can't work on my project haha

Thanks

**Comment by P-lauski** [comment]
@Z3USmodding For future, try posting in sollumz discord first for help and alos checking other open issues as same thing here applies on export like issue #684 , sowhen you export dont 'select hierarchy', just need to left click the parent and then export. Its a work around I found in more recent versions on sollumz which is newer than what is used in tutorial videos. and you wont get the extra files upon exporting.

**Comment by Z3USmodding** [comment]
Ok thanks for answer, and I asked on Discord first and ppl told me to go there tha'ts why

**Comment by Beast-art-des** [comment]
@Z3USmodding hey brother have found any fix bcz I'm also having the same problem, and I also found that the problem is with the latest version of sollumz plugins

**Comment by Z3USmodding** [comment]
@Beast-art-des Hey as P-lauski said to me you just have to click on your object and then export, no need to select the whole hierarchy while it was the case with an other sollumz update

**Comment by Beast-art-des** [comment]
@Z3USmodding I did what he said but still it is not exporting ydr, did you export the ydr??if yes, then which version of blender are you using??

**Comment by Z3USmodding** [comment]
Well for me that's ok, I'am using the version you can download here so the last one

**Comment by Beast-art-des** [comment]
@Z3USmodding no I'm not talking about sollumz plugins I'm talking about blender version. Is it 2.8 or 3.5 or 6

**Comment by Z3USmodding** [comment]
Oh the latest one too I downloaded it today
