### ISSUE TITLE
non-calculated mipmap levels after exporting #dr, #dd, #ft

### ISSUE THREAD

**Issue by cpmodding** [Skylumz/Sollumz#703]
for each exported drawable, drawable dicitonary or fragment, where user chose to embed textures to the file, mipmap levels are defautled to 0
https://i.imgur.com/1701Nao.png

**Comment by alexguirre** [comment]
CW overwrites the MipLevels, Width, Height and Format values with values found in the DDS file, so their values in the XML is not too important.

And the Blender API doesn't expose mipmaps information from images which I guess is why MipLevels was hardcoded to 0.

https://github.com/dexyfex/CodeWalker/blob/9d76f2c6c42b580e67aabf293e3c57be5edbb190/CodeWalker.Core/GameFiles/Resources/Texture.cs#L561-L586

**Comment by alexguirre** [comment]
For example, here MipLevels is 0 and the Format is wrong in the XML but when imported the values correct (Levels=9, Format=DXT5)

![image](https://github.com/Skylumz/Sollumz/assets/12873137/006b2605-da73-47fe-ad41-8950106ef9ef)
![image](https://github.com/Skylumz/Sollumz/assets/12873137/52fa91ed-4be0-4b89-a22e-024da30adbb9)

**Comment by gg781** [comment]
> For example, here MipLevels is 0 and the Format is wrong in the XML but when imported the values correct (Levels=9, Format=DXT5)
> 
> ![image](https://user-images.githubusercontent.com/12873137/260694259-006b2605-da73-47fe-ad41-8950106ef9ef.png) ![image](https://user-images.githubusercontent.com/12873137/260694273-52fa91ed-4be0-4b89-a22e-024da30adbb9.png)

Although it's incorrect that a 256*128 image has 9 levels of mipmaps. Should be 6 at most.

**Comment by alexguirre** [comment]
> Although it's incorrect that a 256*128 image has 9 levels of mipmaps. Should be 6 at most.

That's what ImageMagick generated with default options ¯\\\_(ツ)\_/¯
```
magick convert .\test_spritesheet.png .\test_spritesheet.dds
```

**Comment by cpmodding** [comment]
Oh, great. I was thinking the MipLevels from exported sollumz file is taken into consideration while importing .xml in CW. I'm closing this issue.
