### ISSUE TITLE
Errors when Blender language is anything other than English

### ISSUE THREAD

**Issue by alexguirre** [Skylumz/Sollumz#708]
Sollumz uses hardcoded node names instead of nodes type which causes error when user has different set Blender language anything other than English
![image](https://user-images.githubusercontent.com/43913907/210851535-3ff0310d-c214-4c51-b18e-1217966b6c53.png)

_Originally posted by @ultrahacx in https://github.com/Skylumz/Sollumz/issues/524#issuecomment-1372571567_

**Comment by ook3D** [comment]
![image](https://github.com/Skylumz/Sollumz/assets/47336113/d9c48906-d2a2-47ec-8afc-cc68798e6e0d)
ensure to update the readme after implementing this
