### ISSUE TITLE
Cable creation tools

### ISSUE THREAD

**Issue by alexguirre** [Skylumz/Sollumz#713]
Cable shader requires some setup that is difficult to do manually and needs some scripting, which should be included in Sollumz.

More info:
https://cable.lokos.fun/
https://gist.github.com/ranstar74/01044b834986391276bb416bfcf8771e

**Comment by miraf202** [comment]
Made a simple UI to this script.
https://gist.github.com/miraf202/8f1cfbe0d4dbc222a55a14feac6f2e7e

**Comment by alexguirre** [comment]
Done in 3c627dc1bf1ab7929ce0ae555c0d416bd7f5cdd4.
