### ISSUE TITLE
When I place my Blender model into GTA V, it clips through the mesh

### ISSUE THREAD

**Issue by wcsanshu** [Skylumz/Sollumz#715]
Blender version 3.5.1

demonstration:

https://drive.google.com/file/d/1Mq-uTORwYih8YV0Ljd6DKiDSjpg1cPdf/view?usp=drive_link

https://drive.google.com/file/d/1PlY9W7df2uGV1QH8j7iuKK1mJj3nuv0T/view?usp=drive_link

**Comment by gg781** [comment]
What am I looking at?

Your custom model seems to large for the gtav world scale.

This is **not-very-likely** a sollumz bug but a user issue, ask in our discord for general helps if possible.

**Comment by alexguirre** [comment]
Go to our discord for help.
