### ISSUE TITLE
YFT : kt1_04_cloth_0X no bone detected

### ISSUE THREAD

**Issue by Rigonkmalk** [Skylumz/Sollumz#734]
Blender version : 3.6.2
Sollumz version : last git version ( git pull on main branch )

Description :

When you try to import 
- kt1_04_cloth_01
- kt1_04_cloth_02

You will have an error like this down below

![image](https://github.com/Skylumz/Sollumz/assets/12967235/ddad3084-8840-453d-8668-d25d0734cb94)

Blender collection :

![image](https://github.com/Skylumz/Sollumz/assets/12967235/b2184210-9f54-4473-b92f-fdc612e4b92f)

**Comment by alexguirre** [comment]
Cloth meshes are currently unsupported.
