### ISSUE TITLE
Vehicle Never Imports

### ISSUE THREAD

**Issue by sbdonslaught** [Skylumz/Sollumz#737]
This model just never imports into Blender, I get the spinning blue circle and nothing else. I've kept it open for 10 minutes to see if it ever does something, but no luck.

Spawns perfectly fine in the game and zMod does import it fine.

[NeverImports.zip](https://github.com/Skylumz/Sollumz/files/12455640/NeverImports.zip)

**Comment by alexguirre** [comment]
Minimal repro ([repro.zip](https://github.com/Skylumz/Sollumz/files/12471324/repro.zip)). Seems to be caused by a degenerate triangle in the boot mesh.

**Comment by alexguirre** [comment]
Corrupted mesh on the _hi xml. Removing the degenerate triangles `1678 1678 2099` and `1246 1246 1248` allows Blender to import it.

Blender is expected to crash on corrupted meshes, so nothing to report either.

Fixed xml: [488gtb_hi.yft.xml.zip](https://github.com/Skylumz/Sollumz/files/12477993/488gtb_hi.yft.xml.zip)
