### ISSUE TITLE
Car Collisions issue after export

### ISSUE THREAD

**Issue by sbdonslaught** [Skylumz/Sollumz#738]
I've attached a video as I'm not entirely sure how to explain this one.. but basically, the collision either shifts downwards or gets bigger when you export the car model. 

I've had this issue with more than the vehicle provided, so it's not just tied to this model. - I'm assuming people/I didn't notice it on other vehicles that are higher off the ground.

https://onslaught.ca/s/jpvqyAjm.mp4

I didn't provide the XML's in this one as it was apparently too big to upload.
[CarColIssue.zip](https://github.com/Skylumz/Sollumz/files/12456038/CarColIssue.zip)

**Comment by sbdonslaught** [comment]
Euh, I personally didn't download it but it does look like the same model! 

I was also testing on 2.0 + Blender 3.6.2
Similar to my other issue(#737 ), some people got it and some people didn't, not too sure why. I'm hoping Alex gets the issue and can investigate. But I'll assume for the time being that collisions aren't being calculated properly on export. I could be way off tho.

**Comment by sbdonslaught** [comment]
The new version of Codewalker seems to have resolved this issue. CW Dev45

**Comment by ook3D** [comment]
Skill issue
