### ISSUE TITLE
Shading error

### ISSUE THREAD

**Issue by CxzImMaxYT** [Skylumz/Sollumz#741]
Hey I updated Blender and Sollumz to have everything up to date, but now I can't put any shaders on my props or mlos anymore because the following errors occur:
![Screenshot 2023-08-31 202040](https://github.com/Skylumz/Sollumz/assets/143746845/daa6ab8a-ccf9-4f02-af81-00b6f3873ce9)
![Screenshot 2023-08-31 202055](https://github.com/Skylumz/Sollumz/assets/143746845/9390f003-0f49-4229-8b3d-6222a2bb36e4)

In the second picture you can see that the connections no longer exist and are not assigned at all

**Comment by ook3D** [comment]
try setting your blender language to english

**Comment by CxzImMaxYT** [comment]
Thanks
