### ISSUE TITLE
yft: UV animation on engineblock

### ISSUE THREAD

**Issue by Rigonkmalk** [Skylumz/Sollumz#743]
Blender version : 3.6.1
Sollumz Version : last pull on main branch

Description :

I try to copy paste engineblock from dominator3 to another dominator3 ( named sasp1 FYI ) 

and I see a weird loop on timing belt

https://github.com/Skylumz/Sollumz/assets/12967235/9b65568a-e259-45ad-957e-e62b1e509dd1

**Comment by alexguirre** [comment]
Seems like import-export of dominator3 doesn't break the belt animation. Maybe some topology difference when copying to the new model? Not really sure how those animations work.

If you send the .blend with the broken animation, I could take a look.

**Comment by Rigonkmalk** [comment]
[sasp1.zip](https://github.com/Skylumz/Sollumz/files/12565783/sasp1.zip)

**Comment by cpmodding** [comment]
Game presumably has a whiltelist of vehicle models to enable belt animations when the bone is at the center of vehicle. There are a workarounds working in Zmodeler but, at this time, no one recreated that by Sollumz.

**Comment by alexguirre** [comment]
Closing as the game has different ways to calculate the UV anim parameter for track shaders and just decides via hardcoded vehicle model checks. Seems like the default fallback just animates one side, while for dominator3 (and other models) it animates both sides.
