### ISSUE TITLE
sail missing on yft

### ISSUE THREAD

**Issue by Minorex1** [Skylumz/Sollumz#752]
when you import a yft with sail the sail missing.
![Screenshot 2023-09-10 173732](https://github.com/Skylumz/Sollumz/assets/113803287/95c4d897-33e0-4de3-8ca1-8fd3fa9e93e5)
![Screenshot 2023-09-10 173757](https://github.com/Skylumz/Sollumz/assets/113803287/eeb23d21-ce7d-4e1e-8982-1f14c0e7685a)

**Comment by ultrahacx** [comment]
It's because YFT's are not 100% supported. That part uses cloth physics which is not supported
