### ISSUE TITLE
Latest Sollumz version doesn't seem to import all YCD anims, unlike an older version.

### ISSUE THREAD

**Issue by MoravianLion** [Skylumz/Sollumz#760]
I downloaded the latest Sollumz today, it is marked as 2.0.0, but when trying to import animation from a file I worked before, the animation after the import wasn't present inside Blender.

After some experimenting, I figured why not to try out older Sollumz I used originally. On 1.3.0 the animation import worked again.

Here's an example ycd file and animation that was missing upon latest import with newer Sollumz version. 

arm_1_mcs_2_concat-0.ycd

player_one_dual-0_base

No error inside Blender while importing. I never worked with animation before, so it is also possible I overlooked something basic. But older Sollumz let me to import animation with skeleton selected, the newest Sollumz doesn't seem to even have that option with import. So, I consider this a bug, but feel free to correct me, if I'm wrong.

**Comment by alexguirre** [comment]
This is part of the changes to the animation support for version 2.1. It appends `_action` now, so the action for that animation is called `player_one_dual-0_action` now.

> let me to import animation with skeleton selected

Same, part of the changes for 2.1. Now you can set a target per animation, which is useful when the same clip dictionary has animations for different armatures or other targets (e.g. cameras).

![image](https://github.com/Skylumz/Sollumz/assets/12873137/68f7f744-54c6-4e75-a048-8fd9fa543ce9)

You can also use this tool to set the same target to all animations in a clip dictionary, equivalent to selecting an skeleton on import on previous versions.

![image](https://github.com/Skylumz/Sollumz/assets/12873137/68a865cf-6018-4657-9193-5da51d0eb423)

**Comment by alexguirre** [comment]
Btw, if you use the Download ZIP option from the repo, you will get the latest development version, and will report the old version until there is a new release. If you want exactly 2.0.0, get it from the releases page: https://github.com/Skylumz/Sollumz/releases/tag/v2.0.0

**Comment by MoravianLion** [comment]
Thank you for explaining! I managed to get it work. However, I can't figure out face cap. I might be simply missing something, as I've never work with animations before, but I've tried all related animation to the main actors and nothing fits. Is possible "a bridge" to make it work is missing?

**Comment by alexguirre** [comment]
If you are talking about the animations in `x64c.rpf\anim\ingame\clip_facials@.rpf` (e.g. `facials@p_m_zero@base.ycd`), those use animation tracks specific to facial animations (track IDs 24, 25 and 26) which aren't really supported yet.

These tracks animate values which are later processed by YEDs files (e.g. `p_m_zero.yed`, kinda like small scripts applied to animations), which is what actually sets the final facial bone position/rotation. This is the missing "bridge", yeah.

I want to support YEDs in Sollumz, but it will take a while, until then it won't really be possible to work on facial animations.

**Comment by MoravianLion** [comment]
> I want to support YEDs in Sollumz, but it will take a while, until then it won't really be possible to work on facial animations.

I just wanted to know, if there's something I overlooked or it's not implemented yet. 

Thanks for the clarification!
