### ISSUE TITLE
Implement automatically adding of bone tags  & bone ID in ydr props.

### ISSUE THREAD

**Issue by farazkhann95** [Skylumz/Sollumz#769]
While i create ydr prop animations,  i have to add bone tags ( RotX,RotY, RotZ, TransX, TransY & TransZ) and also the Bone ID 1 2 3 and soo oon. The problem is  when i work with prop with a large number of bones such as 78 or 90 ,  i have to manually add all the tags and ids to bones and its very time consuming...please try to implement something like bone presets..where these all tags and ids applied automatically.

**Comment by alexguirre** [comment]
In 2.1, Bone IDs are already auto-calculated based on the bone name and the "Apply Bone Flags" buttons in the sidebar panel apply them to all selected bones in pose mode, so you just need to switch to pose mode, select all bones and click on "Rotation" and "Translation" buttons.
![image](https://github.com/Skylumz/Sollumz/assets/12873137/428ca05d-dea8-4bd5-878c-6942e88fee4b)
