### ISSUE TITLE
Blender crashes when importing models as assets

### ISSUE THREAD

**Issue by mnsb223** [Skylumz/Sollumz#771]
Blender crashes randomly whenever you import any YDR/YFT as an asset.

**Comment by alexguirre** [comment]
Do you have any more information to reproduce the crash? It is not crashing for me.

**Comment by mnsb223** [comment]
Genuinely I don't. It hard crashes, no error messages, nothing.

**Comment by alexguirre** [comment]
Which version of Sollumz are you using?

**Comment by mnsb223** [comment]
Version 2.1

**Comment by alexguirre** [comment]
Cannot reproduce these crashes, closing for now.
