### ISSUE TITLE
Add Objects To Room (Pie Menu) misleading

### ISSUE THREAD

**Issue by ook3D** [Skylumz/Sollumz#773]
![image](https://github.com/Skylumz/Sollumz/assets/47336113/3e3c2101-c832-4a10-9ad4-75823293582b)
its labelled add to Room but it now with the new YTYP system only adds it as an entity, but not to any room, either rename the button or update it to properly add it to the selected room

**Comment by gamma781** [comment]
make this a thing where you can add selected props to selected room
