### ISSUE TITLE
Question to your Blender_Plugin

### ISSUE THREAD

**Issue by Animator617** [Skylumz/Sollumz#785]
Hey i just wanted to ask you do that plugin s aviable over the python api of blender so i can automat imports and if not do you work on somehing lke that

Hope you can answer me these quetions

and if it is aviable from blender api i would like to ask if you can provide some documentation about how or tell me where to find it

**Comment by Hancapo** [comment]
Is not.

**Comment by Animator617** [comment]
damit but thanks for answer :-)

**Comment by Hancapo** [comment]
If you wanted to do custom add-ons that uses Sollumz you need it to be installed. now, talking about something like fake bpy module, we don't have such a thing.

**Comment by alexguirre** [comment]
Blender does allow you to import installed add-ons, so you can do something like this in a script:
```py
import Sollumz

Sollumz.ydr.ydrimport.import_ydr("D:\\gta5\\props\\sm_22_rcoaster1f.ydr.xml")
Sollumz.yft.yftimport.import_yft("D:\\gta5\\props\\prop_busstop_02.yft.xml")
```

Of course, this isn't the intended use-case so there isn't much documentation other than reading the source code.

**Comment by Animator617** [comment]
Oh thats helps me a lot thank you
