### ISSUE TITLE
automatic hash generation for light projections

### ISSUE THREAD

**Issue by ook3D** [Skylumz/Sollumz#790]
![image](https://github.com/Skylumz/Sollumz/assets/47336113/2b3b8037-84d8-4969-97d9-42ec9f0ae08c)

![image](https://github.com/Skylumz/Sollumz/assets/47336113/3f83ca43-72e6-4206-8e0c-79f16a2876a6)

similar to the YCD animation hash generation, it should allow you select a texture and it will generate a hash based off of the texture name.

**Comment by ook3D** [comment]
or even instead of setting the texture hash, just have an option to open an image texture, or set the path similar to the Texture parameters UI.

**Comment by alexguirre** [comment]
You can just write the texture name
