### ISSUE TITLE
Vehicles: Issue on Tulip after export

### ISSUE THREAD

**Issue by Rigonkmalk** [Skylumz/Sollumz#810]
Blender Version : 3.6.5
Sollumz : 2.2.0 Last pull

Problem:
On the GTA Tulip vehicle, it has been observed that, without any apparent modifications, the vehicle loses specific properties when exported via Sollumz. This issue was not present before the export, and there is no obvious cause on the original vehicle's side.

Steps to Reproduce the Issue:

- Load the GTA Tulip vehicle in the game.
- Perform an export via Sollumz.
- Observe the vehicle's properties after the export.

Configuration

![image](https://github.com/Skylumz/Sollumz/assets/12967235/4a5d2606-31c4-4bed-b5dd-822cbb682629)

Video before export

https://github.com/Skylumz/Sollumz/assets/12967235/941f461e-93e3-4385-bc84-d59a7d14fb4d

Video after export

[https://youtu.be/e1X_HuZqWd0](https://youtu.be/e1X_HuZqWd0)

**Comment by alexguirre** [comment]
Cannot reproduce on the latest commit, may have already been fixed?

**Comment by Rigonkmalk** [comment]
> Cannot reproduce on the latest commit, may have already been fixed?

Need to pull new update on my blender, I will keep you updated

**Comment by Rigonkmalk** [comment]
@alexguirre - I confirm the issue is fixed
