### ISSUE TITLE
support for z3d importing

### ISSUE THREAD

**Issue by tacticalcatboy** [Skylumz/Sollumz#816]
adding support for z3d importing would be really helpful and cause less headaches.
already wasting time, because i have to export it as dae or obj and i lose my textures in the meantime.

**Comment by Sqrl34** [comment]
💀

**Comment by ultrahacx** [comment]
nuh uh

**Comment by ook3D** [comment]
how tf you expect us to do that lmao

**Comment by Sqrl34** [comment]
> how tf you expect us to do that lmao

Get in contact with oleg stat!
