### ISSUE TITLE
Import/export glass shatter maps

### ISSUE THREAD

**Issue by CFox04** [Skylumz/Sollumz#82]

**Comment by soryy708** [comment]
Prior art: https://github.com/soryy708/Shatter-Map-Utility-Tool
This is a JavaScript utility which converts back and forth between CodeWalker's shatter map and BMP images.
[encoding](https://github.com/soryy708/Shatter-Map-Utility-Tool/blob/master/encode.js)
[decoding](https://github.com/soryy708/Shatter-Map-Utility-Tool/blob/master/decode.js)

**Comment by CFox04** [comment]
Awesome, we will definitely use this! We're just gonna have to convert to Python and we will need to figure out how to import the image data to Blender. Blender doesn't allow the use of any external Python libraries which is a challenge.

I would consider compiling an exe without the UI that takes in command line arguments to run the exe through Python, but then there will be issues with the exe not being incompatible with some machines.
