### ISSUE TITLE
Issue with AUTO-CONVERT-TEXTURE

### ISSUE THREAD

**Issue by dunham94** [Skylumz/Sollumz#822]
I consider it a BUG: Issue with AUTO-CONVERT-TEXTURE.

Example:
When you create a new material, it comes with a 'PRINCIPLED BSDF and MATERIAL OUTPUT'... after creating an image texture, linking it to the 'Base Color', then creating a new 'image Texture' and linking it to the 'Normal Bump', then creating a new 'image Texture' and linking it to the 'Specular map', when you click on 'Auto Convert Texture', it doesn't convert the normal or the specular, it keeps ALL DEFAULT and disregards the BUMP and the Specular.

https://ibb.co/kSztVq4
https://ibb.co/g4fnR4f

I noticed that one of the problems could be the Nodes that have changed. The Normal map, when we use the node wrangler, has now become a 'bump' and not a 'normal map' as before, causing a conflict.

**Comment by alexguirre** [comment]
The auto-convert tool is very limited and only has some very basic checks. For normals, it does need the Principled BSDF's Normal socket connected to a Normal Map node, and this one connected to an image.
It isn't planned to extend the functionality of this tool.
