### ISSUE TITLE
implement keymapping for setting LODs

### ISSUE THREAD

**Issue by tacticalcatboy** [Skylumz/Sollumz#826]
![image](https://github.com/Skylumz/Sollumz/assets/10102451/bba25a43-1325-4ce0-beb3-88d3443753cc)
i want to be able to set a shortcut to select LODs for meshes

**Comment by alexguirre** [comment]
There is the object visibility pie menu, which you can open with Shift+V, then press one of the number keys or use your mouse to select the option.
![Object Visibility Pie Menu](https://github.com/Skylumz/Sollumz/assets/12873137/151225cc-748d-40c7-a9ae-a4f98b5b3767)

Note, that Blender also allows you to create your own keybindings for pretty much any button in the UI, in Preferences > Keymap:
![Custom keybinding](https://github.com/Skylumz/Sollumz/assets/12873137/9618bb4e-bb43-4982-8ad7-4827e5234a81)
