### ISSUE TITLE
Xml import,export support.

### ISSUE THREAD

**Issue by sEmreCaNw** [Skylumz/Sollumz#827]
Please add ydd,yft,ydr support for Red Dead 2.

**Comment by ook3D** [comment]
its as simple as that.

**Comment by sEmreCaNw** [comment]
First of all, this is a request. I understand that implementing such a feature may not be an easy thing. I also don't know if it's planned or not, that's why I asked.

**Comment by alexguirre** [comment]
Closing for now. Will create more fine-grained issues when we start working on it.
