### ISSUE TITLE
Latest push broke material parameters

### ISSUE THREAD

**Issue by Splavacado100** [Skylumz/Sollumz#834]
I updated to the newest push because I wanted to try out the new flags, but when trying to export a prop that used the normal_cutout shaders, when I loaded it into CW the mesh that used that material was transparent. I could see the shadow, but not the actual mesh. After comfirming that the issue was fixed when using the release version instead of latest, I found the difference between the two files as shown below. The left is the working ydr.xml, and the right is the one that doesn't work, as shown by the lack of parameters. Upon looking at the blend file, no parameters even show up for options in the side panel.
![Screenshot 2023-12-03 221104](https://github.com/Skylumz/Sollumz/assets/22159119/b526994d-488b-4fe4-9895-4c592ff41c25)

**Comment by ook3D** [comment]
Yes this is a breaking change, you cannot use existing projects

**Comment by ook3D** [comment]
> But how do I edit the parameters then? They don't show up in blender anymore, are they elsewhere?

You can re make the shader click convert  and it will show again
