### ISSUE TITLE
Object Location & Rotation Tools > Paste Rotation. Pastes rotation of Quaternion needs to be in reversed on the XYZ.

### ISSUE THREAD

**Issue by ShiftyGaming** [Skylumz/Sollumz#843]
**Blender Version**: 4.0.2
**Sollumz Version**: 2.3.1

**Information:** 
When pasting the quaternion rotation from Codewalker into Blender with the "Object Location & Rotation Tools" of Sollumz, the object flipped the wrong way in Blender, To fix this we need to reverse the results in Blender.

**Reproduction Steps:**
1. Locate any prop in Codewalker (Export it to XML and import in to Blender)
![image](https://github.com/Skylumz/Sollumz/assets/73522294/b1f1d387-b256-4124-b34c-069e90ec7732)

2. Copy the quaternion from Codewalker
![image](https://github.com/Skylumz/Sollumz/assets/73522294/d0461776-fb2e-4609-aa18-4d178197ee4f)

3. Use the button "Paste Quaternion" button in Sollumz "Object Location & Rotation Tools"
![image](https://github.com/Skylumz/Sollumz/assets/73522294/f17df42f-0d2a-4fc6-b711-32aa107f1e14)

4. Observe that the prop is flipped in Blender 
![image](https://github.com/Skylumz/Sollumz/assets/73522294/617d35da-43c0-4e4e-8f3f-f4475f12e4ee)

To fix this I currently flip all the + to - and all the - to + on the xyz of the quaternion. It would be nice if there is automation for this flipping.
![image](https://github.com/Skylumz/Sollumz/assets/73522294/6b7afe0a-7beb-44ed-a948-4cec941ac59a)

**Comment by ook3D** [comment]
fixed here https://github.com/Skylumz/Sollumz/commit/3952895b2b9ae826c6011e019a8a9f62333d6df0

**Comment by alexguirre** [comment]
> fixed here [3952895](https://github.com/Skylumz/Sollumz/commit/3952895b2b9ae826c6011e019a8a9f62333d6df0)

Not really, now it is broken when pasting from the copy button or anything else that outputs a quaternion.

I think when @ook3D first added this feature, we discussed that it shouldn't invert the quaternion. IMO, it is CW that should display a correct quaternion in the UI to the user, even if that's not what is saved in the file.
