### ISSUE TITLE
YFT Physic broken after export (vanilla props) [Incorrect Transforms in physics LOD1]

### ISSUE THREAD

**Issue by MiniBulle3D** [Skylumz/Sollumz#844]
Hello !

**Blender version** : 4.0
**Sollumz version** : 2.3.1

I noticed something about yft concerning my issue here ⁠[YFT Punch bag Physics] :(https://discord.com/channels/899043946142003240/1188083773150089338)
i used **prop_garden_chimes_01** vanilla props as reference and there is something weird : if you export this props from CW, import it in blender, you change nothing, you export it, put it in game, it's broken and it have the same "behavior" than my props (the physics seems broken, like in the video i shared on my post).

Here the 2 xml : the original one (just exported from CW) and the same props after sollumz export
[prop_garden_chimes_01.yft.zip](https://github.com/Skylumz/Sollumz/files/13766978/prop_garden_chimes_01.yft.zip)

May someone can take a look if you are able to see what is broken during the export ?
if yes let me know (here or feel free to ping me on discord)

Thank a lot for your help !

**Comment by Splavacado100** [comment]
Is the "original one" meant to be truncated? Other than that the only thing I see difference is the omission of the <Matrix> section right in the skel declaration.

**Comment by alexguirre** [comment]
> i noticed that the RestoringStrength value is seted to 0 when you import/export it in sollumz instead of 500 for example. I'm not really comfortable with this kind of troubleshooting so i might be wrong. For info even if i set it back to 500 the issue is still here so i guess there is something else

Looking at your first video, it does seem related to restoring strength. Sollumz incorrectly imported/exported rotation and restoring strengths, but this should have been fixed since 2.3.1: f01e89895003514521f5ceecf2a6f40f4307b40d. Can you try import/export on latest Sollumz?

**Comment by alexguirre** [comment]
I mean latest commit, Download ZIP option in the main repo page. Both will show 2.3.1 in the version field.
![image](https://github.com/Skylumz/Sollumz/assets/12873137/a2b9d88b-0231-4f92-9b74-a6063cf402a9)

**Comment by alexguirre** [comment]
Confirmed that the issue are only the Transforms in the physics LOD1. Sollumz is calculating them incorrectly.

**Comment by IRAKUNITA95** [comment]
i had the same problem but with cars, when i export the values change xml and the car move on wrong positions
