### ISSUE TITLE
trees_lod2.sps doesn't import/export properly

### ISSUE THREAD

**Issue by arifsezeraktas** [Skylumz/Sollumz#846]
Blender 4.0.2/Sollumz 2.3.1
In this example I tried to import cs2_lod_02_slod3_children.ydd and models(or sprites) with trees_lod2 shader are just dots in Blender. With no modification on file, they're not visible when export from Blender.

![image](https://github.com/Skylumz/Sollumz/assets/55943009/63225f32-044f-4091-8774-618b89232940)
![image](https://github.com/Skylumz/Sollumz/assets/55943009/3b870711-8df5-472e-b304-9006f2a0a693)
![image](https://github.com/Skylumz/Sollumz/assets/55943009/653e4b22-1fd7-4999-8b20-4bcf7bba67a5)

**Comment by ultrahacx** [comment]
IDK how CW/Game Shaders are handeling it but sollumz imports it correctly. This is the view of ydd in OpenIV just to make sure its not CW fault
![image](https://github.com/Skylumz/Sollumz/assets/43913907/b2992c61-46b3-4be1-9b82-61fe722442ee)

**Comment by ultrahacx** [comment]
It is imported. trees_lod2 mesh is just vertices, so if you go into edit mode you'll see floating vertices
