### ISSUE TITLE
No import YMAP button?

### ISSUE THREAD

**Issue by Pyth3rEx** [Skylumz/Sollumz#847]
So I'm guessing there have been a few updates since. But I'm trying to follow the documentation to create an MLO.
The doc askes to import a YMAP and the gif shows a button "import ymap". This said I can't seem to find that button anywhere and importing the ymap through the import menu does not link the entities to their collisions (still have the model at 0,0,0 and the collisions at the opposite side of the galaxy.

Is this known? thanks
![image](https://github.com/Skylumz/Sollumz/assets/26427764/6543f929-1b75-4e9c-bad8-9d1f29a31c67)

**Comment by Pyth3rEx** [comment]
I'll also mention I saw #522 but doing as he said dosn't seem to have the expected results:
![image](https://github.com/Skylumz/Sollumz/assets/26427764/32a9c388-892e-474b-8976-a198d7b5ed52)

**Comment by Rigonkmalk** [comment]
@Pyth3rEx 

https://streamable.com/7vnj97

Work as well.
