### ISSUE TITLE
Export ydr file just get a small file

### ISSUE THREAD

**Issue by yaofanggh** [Skylumz/Sollumz#848]
Hi! When I export ydr, I get a ydr file of approximately 2kb size, which is obviously incorrect. Is this an issue with Sollumz or my operation? Thank you!
<img width="400" alt="a" src="https://github.com/Skylumz/Sollumz/assets/103634844/a42e3334-a945-4384-bf25-bf1fe7b5816a">
<img width="655" alt="b" src="https://github.com/Skylumz/Sollumz/assets/103634844/b4a62e25-2fc2-474b-9437-c13113723cf5">

**Comment by ook3D** [comment]
Your hierarchy is completely messed up

**Comment by yaofangwx123** [comment]
> Your hierarchy is completely messed up

Okay,  I am not very familiar with this and followed the instructions on YouTube, but due to the Blender version, there are some different steps. Thank you very much!

**Comment by yaofangwx123** [comment]
**My MLO model cannot be displayed in CodeWalker. When I input Entity as "xpmode_shell", it is displayed, but when I input "xpmode_mlo", it cannot be displayed. Does anyone know why?**

**bob.ytyp**

`<?xml version='1.0' encoding='UTF-8'?>
<CMapTypes>
  <archetypes>
    <Item type="CBaseArchetypeDef">
      <lodDist value="60" />
      <flags value="0" />
      <specialAttribute value="0" />
      <bbMin x="-5.2665443" y="-7.8452754" z="-1.0" />
      <bbMax x="5.917515" y="2.4679973" z="2.4827769" />
      <bsCentre x="0.32548523" y="-2.6886392" z="0.74138844" />
      <bsRadius value="7.8034687" />
      <hdTextureDist value="40" />
      <name>xpmode_shell</name>
      <textureDictionary>xp_box_shell</textureDictionary>
      <assetType>ASSET_TYPE_DRAWABLE</assetType>
      <assetName>xpmode_shell</assetName>
    </Item>
    <Item type="CMloArchetypeDef">
      <lodDist value="60" />
      <flags value="0" />
      <specialAttribute value="0" />
      <bbMin x="0.0" y="0.0" z="0.0" />
      <bbMax x="0.0" y="0.0" z="0.0" />
      <bsCentre x="0.0" y="0.0" z="0.0" />
      <bsRadius value="0" />
      <hdTextureDist value="40" />
      <name>xpmode_mlo</name>
      <physicsDictionary>xpmode_mlo</physicsDictionary>
      <assetType>ASSET_TYPE_ASSETLESS</assetType>
      <assetName>xpmode_mlo</assetName>
      <mloFlags value="0" />
      <entities>
        <Item type="CEntityDef">
          <archetypeName>xpmode_shell</archetypeName>
          <flags value="0" />
          <guid value="0" />
          <position x="-17.299253" y="6301.4346" z="31.307724" />
          <rotation x="-0.0" y="-0.0" z="-0.0" w="1.0" />
          <scaleXY value="1" />
          <scaleZ value="1" />
          <parentIndex value="-1" />
          <lodDist value="200" />
          <childLodDist value="0" />
          <lodLevel>LODTYPES_DEPTH_ORPHANHD</lodLevel>
          <numChildren value="0" />
          <priorityLevel>PRI_REQUIRED</priorityLevel>
          <ambientOcclusionMultiplier value="255" />
          <artificialAmbientOcclusion value="255" />
          <tintValue value="0" />
        </Item>
      </entities>
      <rooms itemType="CMloRoomDef">
        <Item>
          <name>limbo</name>
          <bbMin x="-22.565798" y="6293.5894" z="30.307724" />
          <bbMax x="-11.381739" y="6303.9023" z="33.7905" />
          <blend value="1" />
          <timecycleName>int_gasstation</timecycleName>
          <flags value="0" />
          <portalCount value="1" />
          <floorId value="0" />
          <exteriorVisibiltyDepth value="-1" />
          <attachedObjects />
        </Item>
        <Item>
          <name>main</name>
          <bbMin x="-22.565798" y="6293.5894" z="30.307724" />
          <bbMax x="-11.381739" y="6303.9023" z="33.7905" />
          <blend value="1" />
          <timecycleName>int_gasstation</timecycleName>
          <flags value="0" />
          <portalCount value="1" />
          <floorId value="1" />
          <exteriorVisibiltyDepth value="-1" />
          <attachedObjects>0</attachedObjects>
        </Item>
      </rooms>
      <portals itemType="CMloPortalDef">
        <Item>
          <roomFrom value="1" />
          <roomTo value="0" />
          <flags value="0" />
          <mirrorPriority value="0" />
          <opacity value="0" />
          <audioOcclusion value="0" />
          <corners>
            <Item>-22.565798,6298.91,30.307724</Item>
            <Item>-22.565798,6298.91,33.7905</Item>
            <Item>-14.804251,6303.9023,33.7905</Item>
            <Item>-14.804251,6303.9023,30.307724</Item>
          </corners>
          <attachedObjects />
        </Item>
      </portals>
    </Item>
  </archetypes>
  <name>bob</name>
</CMapTypes>
`

**xpmode_shell.ydr**

`<?xml version='1.0' encoding='UTF-8'?>
<Drawable>
  <Name>xpmode_shell</Name>
  <BoundingSphereCenter x="0.32548523" y="-2.6886392" z="0.74138844" />
  <BoundingSphereRadius value="7.8034687" />
  <BoundingBoxMin x="-5.2665443" y="-7.8452754" z="-1.0" />
  <BoundingBoxMax x="5.917515" y="2.4679973" z="2.4827769" />
  <LodDistHigh value="9998" />
  <LodDistMed value="9998" />
  <LodDistLow value="9998" />
  <LodDistVlow value="9998" />
  <FlagsHigh value="1" />
  <FlagsMed value="0" />
  <FlagsLow value="0" />
  <FlagsVlow value="0" />
  <Unknown9A value="9998" />
  <ShaderGroup>
    <Unknown30 value="0" />
    <Shaders>
      <Item>
        <Name>default</Name>
        <FileName>default.sps</FileName>
        <RenderBucket value="0" />
        <Parameters>
          <Item name="DiffuseSampler" type="Texture">
            <Name>wall_boss</Name>
          </Item>
          <Item name="matMaterialColorScale" type="Vector" x="1.0" y="0.0" z="0.0" w="1.0" />
          <Item name="HardAlphaBlend" type="Vector" x="1.0" y="0.0" z="0.0" w="0.0" />
          <Item name="useTessellation" type="Vector" x="0.0" y="0.0" z="0.0" w="0.0" />
          <Item name="wetnessMultiplier" type="Vector" x="1.0" y="0.0" z="0.0" w="0.0" />
          <Item name="globalAnimUV1" type="Vector" x="0.0" y="1.0" z="0.0" w="0.0" />
          <Item name="globalAnimUV0" type="Vector" x="1.0" y="0.0" z="0.0" w="0.0" />
        </Parameters>
      </Item>
    </Shaders>
  </ShaderGroup>
  <DrawableModelsHigh>
    <Item>
      <RenderMask value="255" />
      <Flags value="0" />
      <HasSkin value="0" />
      <BoneIndex value="0" />
      <Unknown1 value="0" />
      <Geometries>
        <Item>
          <ShaderIndex value="0" />
          <BoundingBoxMin x="-5.2665443" y="-7.8452754" z="-1.0" />
          <BoundingBoxMax x="5.917515" y="2.4679973" z="2.4827769" />
          <BoneIDs />
          <VertexBuffer>
            <Flags value="0" />
            <Layout type="GTAV1">
              <Position />
              <Normal />
              <Colour0 />
              <TexCoord0 />
            </Layout>
            <Data>
              -5.2665443 -2.524588 -1.0   0.84102964 0.54098904 0.0   255 255 255 255   0.91131127 0.68869424   
              -1.8440332 -7.8452754 2.4827769   0.84102964 0.54098904 0.0   255 255 255 255   0.2257925 0.31130576   
              -1.8440332 -7.8452754 -1.0   0.84102964 0.54098904 0.0   255 255 255 255   0.2257925 0.68869424   
              5.917515 -2.85269 -1.0   -0.84102964 -0.54098904 0.0   255 255 255 255   0.2257925 0.68869424   
              2.4950032 2.4679973 2.4827769   -0.84102964 -0.54098904 0.0   255 255 255 255   0.91131127 0.31130576   
              2.4950032 2.4679973 -1.0   -0.84102964 -0.54098904 0.0   255 255 255 255   0.91131127 0.68869424   
              -1.8440332 -7.8452754 -1.0   -0.54098904 0.84102964 0.0   255 255 255 255   0.0 0.68869424   
              5.917515 -2.85269 2.4827769   -0.54098904 0.84102964 0.0   255 255 255 255   1.0 0.31130576   
              5.917515 -2.85269 -1.0   -0.54098904 0.84102964 0.0   255 255 255 255   1.0 0.68869424   
              -1.8440332 -7.8452754 -1.0   0.0 0.0 1.0   255 255 255 255   0.0 0.7742075   
              2.4950032 2.4679973 -1.0   0.0 0.0 1.0   255 255 255 255   1.0 0.08868873   
              -5.2665443 -2.524588 -1.0   0.0 0.0 1.0   255 255 255 255   0.0 0.08868873   
              5.917515 -2.85269 2.4827769   0.0 0.0 -1.0   255 255 255 255   1.0 0.7742075   
              -5.2665443 -2.524588 2.4827769   0.0 0.0 -1.0   255 255 255 255   0.0 0.08868873   
              2.4950032 2.4679973 2.4827769   0.0 0.0 -1.0   255 255 255 255   1.0 0.08868873   
              -5.2665443 -2.524588 2.4827769   0.84102964 0.54098904 0.0   255 255 255 255   0.91131127 0.31130576   
              5.917515 -2.85269 2.4827769   -0.84102964 -0.54098904 0.0   255 255 255 255   0.2257925 0.31130576   
              -1.8440332 -7.8452754 2.4827769   -0.54098904 0.84102964 0.0   255 255 255 255   0.0 0.31130576   
              5.917515 -2.85269 -1.0   0.0 0.0 1.0   255 255 255 255   1.0 0.7742075   
              -1.8440332 -7.8452754 2.4827769   0.0 0.0 -1.0   255 255 255 255   0.0 0.7742075
            </Data>
          </VertexBuffer>
          <IndexBuffer>
            <Data>
              0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 0 15 1 3 16 4 6 17 7 
              9 18 10 12 19 13
            </Data>
          </IndexBuffer>
        </Item>
      </Geometries>
    </Item>
  </DrawableModelsHigh>
</Drawable>
`

**xpmode_mlo.ybn**

`<?xml version='1.0' encoding='UTF-8'?>
<BoundsFile>
  <Bounds type="Composite">
    <BoxMin x="-22.565798" y="6293.5894" z="30.307724" />
    <BoxMax x="-11.381739" y="6303.9023" z="33.7905" />
    <BoxCenter x="-16.973768" y="6298.746" z="32.04911" />
    <SphereCenter x="-16.973768" y="6298.746" z="32.04911" />
    <SphereRadius value="7.803214" />
    <Margin value="0" />
    <Volume value="0" />
    <Inertia x="0.0" y="0.0" z="0.0" />
    <MaterialIndex value="0" />
    <MaterialColourIndex value="0" />
    <ProceduralID value="0" />
    <RoomID value="0" />
    <PedDensity value="0" />
    <UnkFlags value="0" />
    <PolyFlags value="0" />
    <UnkType value="1" />
    <Children>
      <Item type="GeometryBVH">
        <BoxMin x="-22.565798" y="6293.5894" z="30.307724" />
        <BoxMax x="-11.381739" y="6303.9023" z="33.7905" />
        <BoxCenter x="-16.973768" y="6298.746" z="32.04911" />
        <SphereCenter x="-16.973768" y="6298.746" z="32.04911" />
        <SphereRadius value="7.803214" />
        <Margin value="0.005" />
        <Volume value="0" />
        <Inertia x="0.0" y="0.0" z="0.0" />
        <MaterialIndex value="0" />
        <MaterialColourIndex value="0" />
        <ProceduralID value="0" />
        <RoomID value="0" />
        <PedDensity value="0" />
        <UnkFlags value="0" />
        <PolyFlags value="0" />
        <UnkType value="1" />
        <CompositeTransform>
          1.0 0.0 0.0 0.0
          0.0 1.0 0.0 0.0
          0.0 0.0 1.0 0.0
          0.0 0.0 0.0 1.0
        </CompositeTransform>
        <CompositeFlags1>MAP_ANIMAL, MAP_COVER, MAP_DYNAMIC, MAP_VEHICLE, MAP_WEAPON</CompositeFlags1>
        <CompositeFlags2>ANIMAL, ANIMAL_RAGDOLL, EXPLOSION, FORKLIFT_FORKS, GLASS, OBJECT, PED, PLANT, PROJECTILE, RAGDOLL, TEST_AI, TEST_CAMERA, TEST_SCRIPT, TEST_VEHICLE_WHEEL, TEST_WEAPON, VEHICLE_BVH, VEHICLE_NOT_BVH</CompositeFlags2>
        <GeometryCenter x="-16.973768" y="6298.746" z="32.04911" />
        <Materials>
          <Item>
            <Type value="0" />
            <ProceduralID value="0" />
            <RoomID value="0" />
            <PedDensity value="0" />
            <MaterialColourIndex value="0" />
            <Unk value="0" />
          </Item>
        </Materials>
        <Vertices>
          -2.169517993927002, -5.156798362731934, -1.7413864135742188
          -2.169517993927002, -5.156798362731934, 1.7413904666900635
          -5.592029571533203, 0.16388839483261108, 1.7413904666900635
          -5.592029571533203, 0.16388839483261108, -1.7413864135742188
          2.1695175170898438, 5.1564741134643555, -1.7413864135742188
          2.1695175170898438, 5.1564741134643555, 1.7413904666900635
          5.592029571533203, -0.16421246528625488, 1.7413904666900635
          5.592029571533203, -0.16421246528625488, -1.7413864135742188
        </Vertices>
        <VertexColours>
          255, 255, 255, 255
          255, 255, 255, 255
          255, 255, 255, 255
          255, 255, 255, 255
          255, 255, 255, 255
          255, 255, 255, 255
          255, 255, 255, 255
          255, 255, 255, 255
          255, 255, 255, 255
          255, 255, 255, 255
          255, 255, 255, 255
          255, 255, 255, 255
          255, 255, 255, 255
          255, 255, 255, 255
          255, 255, 255, 255
          255, 255, 255, 255
          255, 255, 255, 255
          255, 255, 255, 255
          255, 255, 255, 255
          255, 255, 255, 255
        </VertexColours>
        <Polygons>
          <Triangle m="0" v1="0" v2="1" v3="2" f1="0" f2="0" f3="0" />
          <Triangle m="0" v1="0" v2="2" v3="3" f1="0" f2="0" f3="0" />
          <Triangle m="0" v1="4" v2="5" v3="6" f1="0" f2="0" f3="0" />
          <Triangle m="0" v1="4" v2="6" v3="7" f1="0" f2="0" f3="0" />
          <Triangle m="0" v1="7" v2="6" v3="1" f1="0" f2="0" f3="0" />
          <Triangle m="0" v1="7" v2="1" v3="0" f1="0" f2="0" f3="0" />
          <Triangle m="0" v1="3" v2="4" v3="7" f1="0" f2="0" f3="0" />
          <Triangle m="0" v1="3" v2="7" v3="0" f1="0" f2="0" f3="0" />
          <Triangle m="0" v1="5" v2="2" v3="1" f1="0" f2="0" f3="0" />
          <Triangle m="0" v1="5" v2="1" v3="6" f1="0" f2="0" f3="0" />
        </Polygons>
      </Item>
    </Children>
  </Bounds>
</BoundsFile>
`

**Comment by yaofangwx123** [comment]
@ook3D  Hello, if you have time, could you help me see what's going on? I have been studying this issue for several nights, even reducing the versions of Blender and Sollumz to refer to the video tutorial, and it has been like this all along. Thank you.
