### ISSUE TITLE
No option of root motion location and rotation and animation got messed up while exporting. 

### ISSUE THREAD

**Issue by farazkhann95** [Skylumz/Sollumz#851]
Hi, previously sollumz version 1.3 have root motion location and root motion rotation option,  which cannot be found in sollumz's newer version. Possible to bring them back? Also while editing in game animations  , for example if i edit a clip of move@m@generic and export it, all other animations got messed up ( they all got either wrong rotation or wrong location ). Even if i simply export gta 5 vanilla animations into sollumz legacy or newer sollumz and export it, whole animations of that clip got messed up. Please fix animations if possible, im trying to replace in game generic animations such as walk, run, spring, melee, etc.

Thank you

**Comment by alexguirre** [comment]
The root motion since 2.1 uses the object's delta location and rotation, but it has some issues. I opened another issue with the plan I have to improve it, #852. Broken animation already tracked in #839 and #840.
