### ISSUE TITLE
YFT hinges physics on certain props broken

### ISSUE THREAD

**Issue by ook3D** [Skylumz/Sollumz#855]
seems to mainly be with yft props that have hinges or that sway / swing

an example would be the recycling bins

**Comment by alexguirre** [comment]
`prop_bin_08a.yft`

Doesn't seem to be the same issue reported in #844. Copying the Transforms block from the original seemed to help a bit with its physics in general, but the lid still kept swinging. So something else is broken.

Context: https://discord.com/channels/899043946142003240/1195304544549212230/1195304544549212230

**Comment by alexguirre** [comment]
In the end, seems it was the same issue as #844. After the fix for that issue the swinging on the bin lid stopped.
