### ISSUE TITLE
Ped shader `ped_wrinkle_enveff` not exporting properly

### ISSUE THREAD

**Issue by Stickerzz** [Skylumz/Sollumz#861]
1st is exported from CW
2nd is after exported from Sollumz

https://stickerz.is-serious.business/2znjm1d.mp4

[pedshaderstuff.zip](https://github.com/Skylumz/Sollumz/files/14194116/pedshaderstuff.zip)

**Comment by alexguirre** [comment]
The whole embedded texture dictionary is missing, so you probably didn't have the textures exported from CW.

**Comment by Stickerzz** [comment]
> Hey, can you show your Sollumz texture panel of the imported xml in Blender please.

https://stickerz.is-serious.business/566Y9Sq.png

**Comment by ultrahacx** [comment]
Well, as alex said your embedded texture dictionary seems to be missing. You can reexport the xml and or assign the textures manually in those fields
