### ISSUE TITLE
New animation possibilities

### ISSUE THREAD

**Issue by BIGBOYSLATT** [Skylumz/Sollumz#863]
What's in the future of Update 2.5? What kind of animation work is being done? Yes, we can add and change animations, but it's still limited.

I've seen the work of one of the developers, is it still in development? Is it expected to be released in the upcoming updates? 

https://www.youtube.com/watch?v=-1-KmIMkfDY

**Comment by alexguirre** [comment]
Not much at the moment, other than bug fixes. Anything planned, and its status is public here in the issue tracker and milestones.

That video was something I was working on before becoming the current Sollumz maintainer, when Colton was still working on Sollumz. Since I'm the only active developer currently, I have other priorities for Sollumz, mostly bug fixing given my time constraints.

I would like to support MRFs eventually, just don't have time to spend on such a niche feature.

**Comment by BIGBOYSLATT** [comment]
> Not much at the moment, other than bug fixes. Anything planned, and its status is public here in the issue tracker and milestones.
> 
> That video was something I was working on before becoming the current Sollumz maintainer, when Colton was still working on Sollumz. Since I'm the only active developer currently, I have other priorities for Sollumz, mostly bug fixing given my time constraints.
> 
> I would like to support MRFs eventually, just don't have time to spend on such a niche feature.

And why don't you take someone on the team? Or is it necessary to pay money?

**Comment by alexguirre** [comment]
Anyone is free to contribute through pull requests. If they are active and trustworthy enough, they could become official maintainers if they want to. But there isn't a lot of those, people skilled enough to work on this either are busy with other stuff or not interested.

**Comment by BIGBOYSLATT** [comment]
> Anyone is free to contribute through pull requests. If they are active and trustworthy enough, they could become official maintainers if they want to. But there isn't a lot of those, people skilled enough to work on this either are busy with other stuff or not interested.

And if you were to call on ko-fi, a good amount of money with the addition of some feature, would you do it? Or would you increase the team?

**Comment by BIGBOYSLATT** [comment]
> Anyone is free to contribute through pull requests. If they are active and trustworthy enough, they could become official maintainers if they want to. But there isn't a lot of those, people skilled enough to work on this either are busy with other stuff or not interested.

I'm not saying that you have to do something for a voluntary donation, I just wonder if you received a larger amount of money, would you do it, or would you find a better addition to the team.

**Comment by alexguirre** [comment]
Honestly, looking for something more stable than ko-fi donations from a single person. If more people were donating, maybe I could dedicate more time. And I cannot just go find someone, hiring people is just not a possibility. If there was someone in the community interested, they would be contributing already, as some have already done although none that would like to be a Sollumz maintainer afaik.

**Comment by BIGBOYSLATT** [comment]
> Honestly, looking for something more stable than ko-fi donations from a single person. If more people were donating, maybe I could dedicate more time. And I cannot just go find someone, hiring people is just not a possibility. If there was someone in the community interested, they would be contributing already, as some have already done although none that would like to be a Sollumz maintainer afaik.

Something like patreon?


And yes, As far as I understand, we shouldn't expect something like the State machine this year?

And by the way, I've heard from someone that you're planning to support sollumz, for the new installment, is that true?

**Comment by BIGBOYSLATT** [comment]
> Honestly, looking for something more stable than ko-fi donations from a single person. If more people were donating, maybe I could dedicate more time. And I cannot just go find someone, hiring people is just not a possibility. If there was someone in the community interested, they would be contributing already, as some have already done although none that would like to be a Sollumz maintainer afaik.

While you may have answered these questions, I just recently found out about sollumz

**Comment by Disquse** [comment]
Oh no, the legendary "MRF state machine" guy!

**Comment by alexguirre** [comment]
> And yes, As far as I understand, we shouldn't expect something like the State machine this year?

 Yeah, most likely not something I'll be working on.

> And by the way, I've heard from someone that you're planning to support sollumz, for the new installment, is that true?

GTA 6 is not even confirmed to be coming to PC. Don't get ahead of ourselves. We'll see when the time comes.
