### ISSUE TITLE
Create static collision and create geometry ops create empties instead of mesh objects

### ISSUE THREAD

**Issue by CFox04** [Skylumz/Sollumz#87]
- Create static collision and create geometry ops create empties for some reason now.
- ~~Created objects do not get parented~~.
- ~~Maybe make a "create" operator that all of these ops inherit from?~~

**Comment by Skylumz** [comment]
objects not being parented is on purpose... I say only parent them if an object is active and of the specific sollum_type it should be parented to. i thought about making a base create op... seems useless

**Comment by CFox04** [comment]
Oh gotcha

**Comment by Skylumz** [comment]
Create static collision and create geometry ops create empties for some reason now. 

as far as this i have no clue what you mean what else are they supposed to be?

**Comment by CFox04** [comment]
> Create static collision and create geometry ops create empties for some reason now. 
> 
> 
> 
> as far as this i have no clue what you mean what else are they supposed to be?
> 
> 

Create box for instance should create a box. Right now everything just creates an empty. I fixed it though on my fork and am about to make a pr after I pull
