### ISSUE TITLE
Props renamed during import

### ISSUE THREAD

**Issue by MiniBulle3D** [Skylumz/Sollumz#874]
Sollumz 2.4.0
Blender 4.0

Hello,

I don't know if someone already reported that : I noticed that some props are renamed during blender import with sollumz. 
I have only 1 example right now :  m23_prop_m32_weaponcrate_01a.yft
if you import it, it will be rename like this : prop_m32_weaponcrate_01a
![image](https://github.com/Skylumz/Sollumz/assets/119362041/32dafd03-899d-41f7-ac50-de1b26f00734)

The issue with this is that if you add this props as entity of your mlo it will not appear, until you notice that the name is not the good one :)

Thanks a lot for your help !

**Comment by ook3D** [comment]
this is an issue with the asset itself, its common with DLC assets from Rockstar updates, the drawable name is prop_32_weaponcrate_01a but the file name is m32_prop_32_weaponcrate_01a
