### ISSUE TITLE
BLENDER YDR IMPORT PROBLEM

### ISSUE THREAD

**Issue by LMNStudio** [Skylumz/Sollumz#877]
Helooo, I have a problem when I try to import a YDR file into blender.
It worked an hour ago and now it won't :). It says that it is imported, but it doesn't read it in the list or show it on the desktop.
I am also sending you pictures for you to see
As you can see on photos it write Import but not loading :)

https://imgur.com/a/Pj3CmfB
Are some of my settings loaded incorrectly or what ?

**Comment by ultrahacx** [comment]
![image](https://github.com/Skylumz/Sollumz/assets/43913907/b5e20161-be98-437c-b737-ddd77eaae86d)
Disable `Import as asset` on import window

**Comment by LMNStudio** [comment]
I'm f blind :) :) . Thanks for your help and sorry for the stupid disturbance
