### ISSUE TITLE
Export bugs when moving material list

### ISSUE THREAD

**Issue by nikit0** [Skylumz/Sollumz#881]
Sollumz: 2.4.1
Blender: 4.1.0

I'm creating animated textures for my model, and when moving the list of materials to organize the order better, when exporting the 3d model, the list of materials stays in the order they were created even after organizing them!

Before export:
![image](https://github.com/Skylumz/Sollumz/assets/45583155/238d52ae-8aa6-4518-9841-a9fa35820044)

After re-import:
![image](https://github.com/Skylumz/Sollumz/assets/45583155/7a8b9b9f-5dee-438d-a3cb-c03007713122)

As shown in the images, the list of materials is disorganized, which makes it difficult to create animated textures according to the ids.

**Comment by ook3D** [comment]
the order of materials isnt saved or set when importing or exporting

**Comment by alexguirre** [comment]
If you need a specific order, there is the Order Shaders button in the drawable properties.
![image](https://github.com/Skylumz/Sollumz/assets/12873137/feb28ecc-466f-4c22-b193-4f881f40a0e4)

**Comment by nikit0** [comment]
@ook3D @alexguirre Thank you! I didn't know about that option.
