### ISSUE TITLE
Blender crashes when "copy to selected" LOD Level

### ISSUE THREAD

**Issue by VolpeDelDeserto** [Skylumz/Sollumz#884]
No matter what but when trying to "copy to selected" the LOD level value my blender closes.

Steps to reproduce:
1- Select the drawables
2- Go to  Object properties -> Entity Definiton 
3- Switch LOD Level
4- Copy to selected

Do "Copy to Selected" for other parameters as "Lod Distance" still works as before.
It seems to be an issue since 2.4.1 as before it never happened.

https://gyazo.com/810f8a7540607ab3c6683b7e828a5cec

**Comment by alexguirre** [comment]
Looks like a bug in Blender 4.1. It was reported here: https://projects.blender.org/blender/blender/issues/119999
