### ISSUE TITLE
Some unsupported f-curve data paths are not ignored and throw errors

### ISSUE THREAD

**Issue by Trippieee420** [Skylumz/Sollumz#887]
![image](https://github.com/Skylumz/Sollumz/assets/166540762/bda08a0a-b8d3-4f89-8298-13b06cfbe49b)
this is what is says

**Comment by Pigeonhunt3r** [comment]
find any fix im having same problem

**Comment by Rigonkmalk** [comment]
Can you please told me :

- Blender version
- Sollumz Version
- If possible : Blender project (if not possible, PM me on Discord [Rigonkmalk])
