### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by lawfulbrick09** [Skylumz/Sollumz#888]
Hi i recently came across some strange behavior when embedded a texture. Sometimes it will mess up the model and cause it to not be able to spawn shown here in this screenshot
https://cdn.discordapp.com/attachments/1227462955310780506/1227462955701108830/Screenshot_2024-04209_223828.png?ex=66287ef5&is=661609f5&hm=04abe5de0885e65810cd9528fed8523c197d962f07f117178fd71a8f8561ca7f&
this only happens when embedding a texture not when using a ytd.

**Comment by ook3D** [comment]
gonna need some additional info, can you attach the blend file, and or the ydr?

**Comment by lawfulbrick09** [comment]
here attached is the xml file and the blend file and the texutres
https://drive.google.com/drive/folders/1aK1xZZklHZfIkUSJlTZS5P-jND9E-Iut?usp=drive_link

**Comment by ook3D** [comment]
> here attached is the xml file and the blend file and the texutres https://drive.google.com/drive/folders/1aK1xZZklHZfIkUSJlTZS5P-jND9E-Iut?usp=drive_link

sorry for late reply, its set to restricted
![image](https://github.com/Skylumz/Sollumz/assets/47336113/5b69b74a-cd31-4e5e-b708-ae42f90d3f41)

**Comment by lawfulbrick09** [comment]
My bad here i gave you access

**Comment by ook3D** [comment]
> My bad here i gave you access
the issue seems to be caused by the texture, try removing the alpha channel of the texture(s)
![image](https://github.com/Skylumz/Sollumz/assets/47336113/8069361d-0808-473f-bb21-4cce8b7b5a3e)

**Comment by lawfulbrick09** [comment]
ok thanks
