### ISSUE TITLE
Broken YDD while exporting any type of head_r

### ISSUE THREAD

**Issue by Denyss600** [Skylumz/Sollumz#890]
I want to create a new custom mp_freemode head, and i followed up how rockstar does their head models for mp_freemode, but it seems to be broken while exporting. At first i thought i did a mistake or i forgot to do something. What i did next was to import a head model from vanilla gta (my example: "head_021_r.ydd" and also tryed other ones, still the same) into blender and without touching it, export and test in game. 
Vanilla head just imported and exported with Sollumz and this is the result: 
![image](https://github.com/Skylumz/Sollumz/assets/137230286/f333180e-357e-4d9c-8ab7-2629fb98c0d1)

Tools used:
Blender version: 4.1
Sollumz 2.4.1
CodeWalker30_dev46

[ I also tryed on older version of sollumz and blender and codewalker too and its the same result ]

**Comment by ook3D** [comment]
https://github.com/Skylumz/Sollumz/issues/646 already a known issue 😸
