### ISSUE TITLE
Textures not rendering correctly

### ISSUE THREAD

**Issue by Ninovui** [Skylumz/Sollumz#892]
I'm struggling to get a UV map to be correctly displayed on a prop, but can't figure out why it's not working.

So in blender, I've made this :

https://imgur.com/a/KV5WGel

Then, I followed all instructions ("Set all Materials Embedded") and it came out like this :

https://imgur.com/a/X3XqgdJ

Can someone explain to my why this isn't working properly ? Thank you

**Comment by ook3D** [comment]
this isnt an issue with sollumz, please if you need help with the plugin use the proper channels

**Comment by Ninovui** [comment]
Sorry but what are you talking about, it is, why aren't the textures working while exported ?

**Comment by alexguirre** [comment]
Use the Discord help channels.
