### ISSUE TITLE
wheels not visible after export

### ISSUE THREAD

**Issue by meliholmak** [Skylumz/Sollumz#899]
![12341](https://github.com/Skylumz/Sollumz/assets/104675873/efe0703c-762c-493a-8080-bf29aee2c955)
![1452512](https://github.com/Skylumz/Sollumz/assets/104675873/7900302e-8174-4a0b-94e0-84e92b57b676)

I deleted the logo of the vehicle, I activated collision again and exported it to the xml file in this form. But the wheel does not appear. In the same way in the game, the car stays in the air and looks broken.

**Comment by ook3D** [comment]
can you send the blend file or the original yft files?

**Comment by meliholmak** [comment]
[volvoxc90.zip](https://github.com/Skylumz/Sollumz/files/15282293/volvoxc90.zip)

I also use blender 4.0 and sollumz 2.4.2, but when exported, it does not transfer the xml file to the folder, I could not solve it, I encountered a different problem in each version.

**Comment by Rigonkmalk** [comment]
Did you check IG ?
CW is not really accurate for visualization.

**Comment by alexguirre** [comment]
To edit vehicles you should have both non-hi and hi .yft.xmls in the same folder, and import the non-hi one. Don't import _hi.yft.xml directly.
