### ISSUE TITLE
Problem importing a .YDR.XML file into blender

### ISSUE THREAD

**Issue by anteyria** [Skylumz/Sollumz#901]
Hello,

I have a problem which is importing the first file of a gta mapping into blender. When I import it with sollumz it gives me a big message with lots of errors.
the message is as follows:

![image](https://github.com/Skylumz/Sollumz/assets/133444155/3e732bc0-c666-461e-9fba-670914ea4259)

please help me.

thanks

**Comment by ook3D** [comment]
this is not a bug. please only report things you are 110% certain are issues with sollumz itself.

you need to update blender, read the requirements
