### ISSUE TITLE
Error when trying to install addon Sollums 

### ISSUE THREAD

**Issue by Extricationer9** [Skylumz/Sollumz#904]
When trying to install the Sollums add-on into Blender I keep getting an error message.  I took a screen shot of the error and hoping someone else had this issue and knows how to fix it.
![blender_leU7LTTTU6](https://github.com/Skylumz/Sollumz/assets/63804249/4da3a650-b6c0-423f-8e9c-1f23774781f5)

**Comment by ook3D** [comment]
Download the proper file from the latest release, 'Sollumz.zip', also remove any current installation of sollumz in blender first.

**Comment by Extricationer9** [comment]
I did download the latest version of both blender and sollums
