### ISSUE TITLE
Error while installing add-on

### ISSUE THREAD

**Issue by Extricationer9** [Skylumz/Sollumz#908]
I have the latest versions of both Blender and Sollums and when I go to install the add-on I get this error message box pop up.

![rZSwAd5bRI](https://github.com/Skylumz/Sollumz/assets/63804249/39c24737-5e97-4b28-94cb-ad2454544fd0)

**Comment by ook3D** [comment]
Remove any current install of blender and install the correct Sollumz.zip from the releases tab

**Comment by ook3D** [comment]
also, do not open duplicate issues, your previous one was closed because this is NOT a bug with sollumz.

**Comment by Extricationer9** [comment]
I understand that but when I hit report big this is where it sent me so I
will post here to see if someone can help me because I have the latest
version for blender and Dollie’s and it is not working
