### ISSUE TITLE
Adding new texture leads to error with UV Map

### ISSUE THREAD

**Issue by itIsMaku** [Skylumz/Sollumz#909]
When adding a new texture after creating a shader material and uploading an texture image, the texture does not load and is not properly visible on the model. 
You have to go to the Vector UV Map 0 settings for the texture and uncheck the red error, then the texture appears correctly.

![image](https://github.com/Skylumz/Sollumz/assets/68100107/6b5e3ca6-fcb8-4f5c-a9ad-817752b4ba73)

Tested on Blender 4.0 & Blender 4.1, both Solumnz version 2.4.2

**Comment by alexguirre** [comment]
You should rename the UV map under Mesh data > UV Maps instead. This is expected as for proper rendering we need to choose UV maps by name in the shader nodes, specially when a shader uses multiple UV maps.

Specific UV map and color attribute names will also be required for export eventually per #800.
