### ISSUE TITLE
Exporting Textures

### ISSUE THREAD

**Issue by Skruluc** [Skylumz/Sollumz#916]
So when i want to exporrt my model, everything is exported except the materials folder.

![Screenshot_1](https://github.com/Skylumz/Sollumz/assets/92750442/065c6265-20dd-466f-b1cb-da643176c839)
![image](https://github.com/Skylumz/Sollumz/assets/92750442/87cb45d2-7641-4be1-ac4d-475e22e50464)

**Comment by ook3D** [comment]
this isnt a sollumz issue, your hierarchy is incorrect, or the sollumz type is wrong
