### ISSUE TITLE
ATTN can not import create prameter how can I fix this

### ISSUE THREAD

**Issue by gigiiontwitch** [Skylumz/Sollumz#920]
![image](https://github.com/Skylumz/Sollumz/assets/161231873/031dbe5d-a31b-44e2-bc63-0cf68bc4123b)

**Comment by alexguirre** [comment]
You probably had another Sollumz version previously installed, make sure to uninstall any versions you have and install the newest one. Afterward, restart blender just in case.

If you still have issues, ask in the [Discord server](https://discord.gg/bZuWBWaQBg). The issue tracker is for actual bug reports.
