### ISSUE TITLE
YDR/YFT file size increase after import-export

### ISSUE THREAD

**Issue by fhsjxk** [Skylumz/Sollumz#921]
Vanilla drawable geometries only use 2 bytes of float's 4 bytes for normals, sollumz exported geometries use full 4 bytes, so packed and deflated file size increased, maybe can processing normals when exporting to avoid it, this CW fork solve this problem [https://github.com/fhsjxk/CodeWalker/tree/float16-normal](https://github.com/fhsjxk/CodeWalker/tree/float16-normal)

**Comment by alexguirre** [comment]
> Vanilla drawable geometries only use 2 bytes of float's 4 bytes for normals

No, they don't. Check the vertex data of any model. Some rare ones use Dec3N (packed in 32-bits, 10 bits per X,Y,Z component), but the majority simply uses 32-bit floats, 4 bytes each component.
![normals](https://github.com/Skylumz/Sollumz/assets/12873137/7a5263ee-6472-446a-adb2-5bd2ed5015b4)

You cannot just add new entries to `VertexComponentType` and expect it to work, this enum comes from the game engine, the engine just won't know about any new entries.
https://github.com/fhsjxk/CodeWalker/blob/bc2c7ed762ee39ed51fc2dba942282684c142892/CodeWalker.Core/GameFiles/Resources/VertexType.cs#L26-L30

Similarly, you cannot just add a special case in `GetComponentType` and expect the game to know about it. The game uses that `Types` field to know the type of each component. The game will still expect 32-bit floats.
https://github.com/fhsjxk/CodeWalker/blob/bc2c7ed762ee39ed51fc2dba942282684c142892/CodeWalker.Core/GameFiles/Resources/Drawable.cs#L4290-L4299

And that's just not how you get a half value from a float value, you don't just copy 2 bytes of the float.
https://github.com/fhsjxk/CodeWalker/blob/bc2c7ed762ee39ed51fc2dba942282684c142892/CodeWalker.Core/GameFiles/Resources/Drawable.cs#L3974-L3979

**Comment by fhsjxk** [comment]
> > Vanilla drawable geometries only use 2 bytes of float's 4 bytes for normals
> 
> No, they don't. Check the vertex data of any model. Some rare ones use Dec3N (packed in 32-bits, 10 bits per X,Y,Z component), but the majority simply uses 32-bit floats, 4 bytes each component. ![normals](https://private-user-images.githubusercontent.com/12873137/341952559-7a5263ee-6472-446a-adb2-5bd2ed5015b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNTExMzUsIm5iZiI6MTcxOTA1MDgzNSwicGF0aCI6Ii8xMjg3MzEzNy8zNDE5NTI1NTktN2E1MjYzZWUtNjQ3Mi00NDZhLWFkYjItNWJkMmVkNTAxNWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDEwMDcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljMDllOTRlNDNlMDgxMzgyMzBlOTlkNGI4ZjJmMGFhY2U0NTA0MTY2MDU3MDY1N2ZlZjQ5ODUzNDMxYjNjZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UbaKY3r14GziRkLQr09ExGjPg-uHkMOU2LaKaBJPDK4)
> 
> You cannot just add new entries to and expect it to work, this enum comes from the game engine, the engine just won't know about any new entries. https://github.com/fhsjxk/CodeWalker/blob/bc2c7ed762ee39ed51fc2dba942282684c142892/CodeWalker.Core/GameFiles/Resources/VertexType.cs#L26-L30`VertexComponentType`
> 
> Similarly, you cannot just add a special case in and expect the game to know about it. The game uses that field to know the type of each component. The game will still expect 32-bit floats. https://github.com/fhsjxk/CodeWalker/blob/bc2c7ed762ee39ed51fc2dba942282684c142892/CodeWalker.Core/GameFiles/Resources/Drawable.cs#L4290-L4299`GetComponentType``Types`
> 
> And that's just not how you get a half value from a float value, you don't just copy 2 bytes of the float. https://github.com/fhsjxk/CodeWalker/blob/bc2c7ed762ee39ed51fc2dba942282684c142892/CodeWalker.Core/GameFiles/Resources/Drawable.cs#L3974-L3979

Maybe my expression is not clear, I mean this
![image](https://github.com/Skylumz/Sollumz/assets/79156514/c58f45d4-ec49-4697-923d-621ab5cfc5c6)
For normal, first 2 bytes of every components are zero
And these are dumped vertices normal data of cs_x_array02.ydr
![image](https://github.com/Skylumz/Sollumz/assets/79156514/e80b4c1c-4f39-470a-9f02-662252df6abc)
first 2 bytes are also zero

**Comment by alexguirre** [comment]
So the normals are rounded off. Each component still takes 4 bytes in memory once the resource is loaded by the game, guess it might help with compression with all the repetitive 0s, but compressed file size doesn't matter much.
