### ISSUE TITLE
Importing yft's not responding till i close it with task manager

### ISSUE THREAD

**Issue by RealMrCactus** [Skylumz/Sollumz#927]
when i try importing a yft it just doesnt respond until i kill it with task manager

**Comment by ook3D** [comment]
> when i try importing a yft it just doesnt respond until i kill it with task manager

Can you send the original yfts

**Comment by alexguirre** [comment]
Possibly same issue as #862. It is fixed but not released yet so you can try installing the latest commit.

**Comment by RealMrCactus** [comment]
> > when i try importing a yft it just doesnt respond until i kill it with task manager
> 
> Can you send the original yfts

it was ripples valor i needed models so i could texture in substance

**Comment by ook3D** [comment]
> > > when i try importing a yft it just doesnt respond until i kill it with task manager
> > 
> > 
> > Can you send the original yfts
> 
> it was ripples valor i needed models so i could texture in substance

not really sure what 'ripples valor' is, can you link it?

**Comment by alexguirre** [comment]
Can't fix anything if we can't reproduce it. Anyway, as I mentioned, this is probably a duplicate of #862. Try installing the latest commit (not release) that includes the fix and import again.
