### ISSUE TITLE
YDR Capsule Lights Extents

### ISSUE THREAD

**Issue by KilluaZoldyck0099** [Skylumz/Sollumz#934]
If you export a ydr with lights in it and the light is a capsule then if you for eg set extent to 4.3 in blender on xml file you get 
`<Extent x="4.3" y="1.0" z="1.0" />` and it should be `<Extent x="4.3" y="4.3" z="4.3" />`

**Comment by alexguirre** [comment]
Only the X value in Extent is used, the Y and Z values are ignored by the game.
