### ISSUE TITLE
YTF texture bug

### ISSUE THREAD

**Issue by FilipeCuco** [Skylumz/Sollumz#965]
## Description

supposedly when I export a model the texture format in the .xml is D3DFMT_DXT5 but when I import it into codewalker it is D3DFMT_DXT1
![image](https://github.com/user-attachments/assets/f567e364-68b7-42cd-b94a-691faa882193)
![image](https://github.com/user-attachments/assets/f3b39681-fcab-483c-a5ee-49ae72ad0dd6)

**Comment by alexguirre** [comment]
The format in the XML is irrelevant, it is ignored by CW. It uses the format in the actual DDS file, so whatever format your Untitled.dds is, which should be DXT1 in this case.
